Livre: livre::Configuration Class Reference
livre::Configuration Class Reference
The Configuration class is used to have a dictionary of variadic data types with names.
#include <Configuration.h>
Public Member Functions
template<class T >
void addDescription (const std::string &groupName, const std::string &shortDesc, const std::string &longDesc)
Adds description for a dictionary item.
template<class T >
void addDescription (const std::string &groupName, const std::string &shortDesc, const std::string &longDesc, T defaultValue)
Add description for a dictionary item.
template<class T >
void addDescription (const std::string &groupName, const std::string &shortDesc, const std::string &longDesc, T defaultValue, T implicitValue)
Add description for a dictionary item.
void addDescription (const std::string &groupName, const std::string &shortDesc, const std::string &longDesc, bool defaultValue)
LIVRECORE_API void parseCommandLine (int32_t argc, const char **argv)
Parses command line.
template<class T >
T getValue (const std::string &key, const T &defaultValue) const
Gets the value of a key from the dictionary.
LIVRECORE_API bool getValue (const std::string &key) const
Gets the value of a key from the disctionary.
LIVRECORE_API bool empty () const
LIVRECORE_API void addDescription (const Configuration &config)
Adds global parameters (help, config file ...
LIVRECORE_API const ProgramOptionsDescriptionMap & getDescriptionMap_ () const
LIVRECORE_API Configuration & operator= (const Configuration &)
Friends
LIVRECORE_API friend std::ostream & operator<< (std::ostream &ostream, const Configuration &configuration)
Prints description map for parameters.
Detailed Description
The Configuration class is used to have a dictionary of variadic data types with names.
Definition at line 32 of file Configuration.h.
Member Function Documentation
template<class T > void livre::Configuration::addDescription (const std::string & groupName, const std::string & shortDesc, const std::string & longDesc) inline
Adds description for a dictionary item.
Parameters
groupName The item group.
shortDesc Short description.
longDesc Long description.
Warning
Before file parsing and/or command line parsing descriptions should be added
Definition at line 45 of file Configuration.h.
Referenced by addDescription(), and empty().
template<class T > void livre::Configuration::addDescription (const std::string & groupName, const std::string & shortDesc, const std::string & longDesc, T defaultValue) inline
Add description for a dictionary item.
Parameters
groupName The item group.
shortDesc Short description.
longDesc Long description.
defaultValue Add default value to parameter.
Warning
Before file parsing and/or command line parsing descriptions should be added. The bool type specialization is different and in the cpp file.
Definition at line 65 of file Configuration.h.
template<class T > void livre::Configuration::addDescription (const std::string & groupName, const std::string & shortDesc, const std::string & longDesc, T defaultValue, T implicitValue) inline
Add description for a dictionary item.
Parameters
groupName The item group.
shortDesc Short description.
longDesc Long description.
defaultValue Default value for parameter (arg not given).
implicitValue Implicit value for paramter (arg with no value)
Warning
Before file parsing and/or command line parsing descriptions should be added. The bool type specialization is different and in the cpp file.
Definition at line 87 of file Configuration.h.
References addDescription(), and parseCommandLine().
LIVRECORE_API void livre::Configuration::addDescription (const Configuration & config)
Adds global parameters (help, config file ...
to global configuration)
Parameters
config Configuration that has the description.
LIVRECORE_API bool livre::Configuration::empty () const inline
Returns
True if dictionary is empty.
Definition at line 145 of file Configuration.h.
References addDescription(), getDescriptionMap_(), and operator<<.
LIVRECORE_API const ProgramOptionsDescriptionMap& livre::Configuration::getDescriptionMap_ () const
Returns
The description map.
Referenced by empty().
template<class T > T livre::Configuration::getValue (const std::string & key, const T & defaultValue) const inline
Gets the value of a key from the dictionary.
Parameters
key Key to the value in the dictionary.
defaultValue The default value to use if key not in dictionary
Returns
The value if found in the dictionary, defaultValue otherwise
Definition at line 124 of file Configuration.h.
LIVRECORE_API bool livre::Configuration::getValue (const std::string & key) const inline
Gets the value of a key from the disctionary.
Parameters
key Key to the value in the dictionary.
Returns
True if key is in the dictionary.
Definition at line 137 of file Configuration.h.
LIVRECORE_API void livre::Configuration::parseCommandLine (int32_t argc, const char ** argv)
Parses command line.
Parameters
argc Number of arguments.
argv Arguments array.
Referenced by addDescription().
Friends And Related Function Documentation
LIVRECORE_API friend std::ostream& operator<< (std::ostream & ostream, const Configuration & configuration) friend
Prints description map for parameters.
Returns
the output stream.
Referenced by empty().
The documentation for this class was generated from the following file:
Configuration.h