Livre: livre::LODNode Class Reference
livre::LODNode Class Reference
Defines the spatial structure of a node in terms of world space, size and voxel dimensions.
#include <LODNode.h>
Public Member Functions
LIVRECORE_API LODNode ()
Construct an invalid LODNode.
LIVRECORE_API LODNode (const NodeId &nodeId, const Vector3ui &blockSize, const Vector3ui &levelTotalBlockDimensions)
Compute the world position from given information.
LIVRECORE_API LODNode (const NodeId &nodeId, const Vector3ui &blockSize, const Boxf &worldBox)
Compute the world position from given information.
LIVRECORE_API Vector3ui getAbsolutePosition () const
Get the absolute node position wrt its level.
LIVRECORE_API Vector3f getRelativePosition () const
LIVRECORE_API const Boxui & getVoxelBox () const
LIVRECORE_API const Boxf & getWorldBox () const
LIVRECORE_API uint32_t getRefLevel () const
LIVRECORE_API NodeId getNodeId () const
LIVRECORE_API bool isValid () const
LIVRECORE_API bool operator== (const LODNode &node) const
LIVRECORE_API bool isParent (const LODNode &parentNode) const
LIVRECORE_API const Vector3ui & getBlockSize () const
Detailed Description
Defines the spatial structure of a node in terms of world space, size and voxel dimensions.
Definition at line 33 of file LODNode.h.
Constructor & Destructor Documentation
LIVRECORE_API livre::LODNode::LODNode ()
Construct an invalid LODNode.
LIVRECORE_API livre::LODNode::LODNode (const NodeId & nodeId, const Vector3ui & blockSize, const Vector3ui & levelTotalBlockDimensions)
Compute the world position from given information.
Parameters
nodeId Unique node id.
blockSize Block size in voxels.
levelTotalBlockDimensions Total number of blocks in the corresponding tree level.
LIVRECORE_API livre::LODNode::LODNode (const NodeId & nodeId, const Vector3ui & blockSize, const Boxf & worldBox)
Compute the world position from given information.
Parameters
nodeId Unique node id.
blockSize Block size in voxels.
worldBox Node position in the world space.
Member Function Documentation
LIVRECORE_API Vector3ui livre::LODNode::getAbsolutePosition () const inline
Get the absolute node position wrt its level.
The minimum position are the x,y,z absolute coordinates of the offset of the given node, e.g., on level 2 they are between 0..7.
Returns
Blockwise position level resolution.
Definition at line 69 of file LODNode.h.
References livre::NodeId::getPosition(), and getRelativePosition().
LIVRECORE_API const Vector3ui& livre::LODNode::getBlockSize () const inline
Returns
the size of the block without paddings
Definition at line 112 of file LODNode.h.
LIVRECORE_API NodeId livre::LODNode::getNodeId () const inline
Returns
The unique node id.
Definition at line 92 of file LODNode.h.
LIVRECORE_API uint32_t livre::LODNode::getRefLevel () const inline
Returns
The tree level.
Definition at line 87 of file LODNode.h.
References livre::NodeId::getLevel().
LIVRECORE_API Vector3f livre::LODNode::getRelativePosition () const
Returns
the relative node position in normalized coordinates.
Referenced by getAbsolutePosition().
LIVRECORE_API const Boxui& livre::LODNode::getVoxelBox () const inline
Returns
Voxel extents in reflevel resolution.
Definition at line 77 of file LODNode.h.
LIVRECORE_API const Boxf& livre::LODNode::getWorldBox () const inline
Returns
The box in world coordinates.
Definition at line 82 of file LODNode.h.
LIVRECORE_API bool livre::LODNode::isParent (const LODNode & parentNode) const
Parameters
parentNode Parent node.
Returns
True if the node is parent.
Referenced by operator==().
LIVRECORE_API bool livre::LODNode::isValid () const inline
Returns
True if node is valid.
Definition at line 97 of file LODNode.h.
References livre::NodeId::isValid().
LIVRECORE_API bool livre::LODNode::operator== (const LODNode & node) const inline
Parameters
node The node to compare.
Returns
True if nodeId's are same.
Definition at line 103 of file LODNode.h.
References isParent().
The documentation for this class was generated from the following file:
LODNode.h