Livre: livre::AllocMemoryUnit Class Reference
livre::AllocMemoryUnit Class Reference
The AllocMemoryUnit class shows an allocated memory pointer to keep track of memory consumption.
#include <MemoryUnit.h>
Public Member Functions
template<class T >
void allocAndSetData (const T *sourceData, const uint32_t size)
Allocates and sets the data from the given ptr, with given size.
template<class T >
void allocAndSetData (const std::vector< T > &sourceData)
Allocates and sets the data from the given source data vector, with given size.
void alloc (const uint32_t allocSizePerElement, const uint32_t dataSize) final
Allocates memory.
void release () final
Release memory.
uint32_t getMemSize () const final
uint32_t getAllocSize () const final
Public Member Functions inherited from livre::MemoryUnit
template<class T >
const T * getData () const
template<class T >
T * getData ()
Additional Inherited Members
Detailed Description
The AllocMemoryUnit class shows an allocated memory pointer to keep track of memory consumption.
Definition at line 116 of file MemoryUnit.h.
Member Function Documentation
void livre::AllocMemoryUnit::alloc (const uint32_t allocSizePerElement, const uint32_t dataSize) final virtual
Allocates memory.
Parameters
allocSizePerElement Allocation size per element of the array.
dataSize Number of elements in the array.
Implements livre::MemoryUnit.
Referenced by allocAndSetData().
template<class T > void livre::AllocMemoryUnit::allocAndSetData (const T * sourceData, const uint32_t size) inline
Allocates and sets the data from the given ptr, with given size.
Parameters
sourceData Source data ptr.
size Number of the elements in the source data ptr.
Definition at line 127 of file MemoryUnit.h.
References alloc().
Referenced by allocAndSetData().
template<class T > void livre::AllocMemoryUnit::allocAndSetData (const std::vector< T > & sourceData) inline
Allocates and sets the data from the given source data vector, with given size.
Parameters
sourceData Source data vector.
Definition at line 138 of file MemoryUnit.h.
References allocAndSetData().
uint32_t livre::AllocMemoryUnit::getAllocSize () const final virtual
Returns
The allocated heap size.
Implements livre::MemoryUnit.
uint32_t livre::AllocMemoryUnit::getMemSize () const final virtual
Returns
The size of the memory accessed.
Implements livre::MemoryUnit.
void livre::AllocMemoryUnit::release () final virtual
Release memory.
Implements livre::MemoryUnit.
The documentation for this class was generated from the following file:
MemoryUnit.h