set(HELLO_MATURITY EP)
set(HELLO_DESCRIPTION "Example project for the Blue Brain Project")
set(HELLO_GIT_ROOT_URL https://github.com/BlueBrain/Hello.git)
set(HELLO_PACKAGE_URL https://launchpad.net/~eilemann/+archive/equalizer)
set(HELLO_CI_URL https://travis-ci.org/BlueBrain/Hello)
set(HELLO_CI_PNG https://travis-ci.org/BlueBrain/Hello.png)
set(HELLO_ISSUES_URL https://github.com/BlueBrain/Hello/issues)
