var files =
[
    [ "brion/api.h", "brion_2api_8h.html", "brion_2api_8h" ],
    [ "brain/api.h", "brain_2api_8h.html", "brain_2api_8h" ],
    [ "blueConfig.h", "blue_config_8h_source.html", null ],
    [ "brain.h", "brain_8h_source.html", null ],
    [ "brion.h", "brion_8h_source.html", null ],
    [ "brion/circuit.h", "brion_2circuit_8h_source.html", null ],
    [ "brain/circuit.h", "brain_2circuit_8h_source.html", null ],
    [ "compartmentReport.h", "compartment_report_8h_source.html", null ],
    [ "compartmentReportPlugin.h", "compartment_report_plugin_8h_source.html", null ],
    [ "brion/defines.h", "brion_2defines_8h_source.html", null ],
    [ "brain/jenkins/02/workspace/oss.Brion.documentation/build_type/Debug/platform/cscsviz-vm/build/include/brion/defines.h", "brain_2jenkins_202_2workspace_2oss_8_brion_8documentation_2build__type_2_debug_2platform_2cscsviea586130194654e8e15987abab11e6bf_source.html", null ],
    [ "enums.h", "enums_8h.html", "enums_8h" ],
    [ "mesh.h", "mesh_8h_source.html", null ],
    [ "brion/morphology.h", "brion_2morphology_8h_source.html", null ],
    [ "brain/neuron/morphology.h", "brain_2neuron_2morphology_8h_source.html", null ],
    [ "morphologyPlugin.h", "morphology_plugin_8h_source.html", null ],
    [ "pluginInitData.h", "plugin_init_data_8h_source.html", null ],
    [ "section.h", "section_8h_source.html", null ],
    [ "soma.h", "soma_8h_source.html", null ],
    [ "spikeReport.h", "spike_report_8h_source.html", null ],
    [ "spikeReportPlugin.h", "spike_report_plugin_8h_source.html", null ],
    [ "spikeReportReader.h", "spike_report_reader_8h_source.html", null ],
    [ "spikeReportWriter.h", "spike_report_writer_8h_source.html", null ],
    [ "spikes.h", "spikes_8h_source.html", null ],
    [ "synapse.h", "synapse_8h_source.html", null ],
    [ "synapseSummary.h", "synapse_summary_8h_source.html", null ],
    [ "target.h", "target_8h_source.html", null ],
    [ "brion/types.h", "brion_2types_8h_source.html", null ],
    [ "brain/neuron/types.h", "brain_2neuron_2types_8h_source.html", null ],
    [ "brain/types.h", "brain_2types_8h_source.html", null ],
    [ "brion/version.h", "brion_2version_8h.html", "brion_2version_8h" ],
    [ "brain/version.h", "brain_2version_8h.html", "brain_2version_8h" ]
];