Brayns: brayns::Progress Class Reference
brayns::Progress Class Reference
A progress object which offers thread-safe progress updates and thread-safe consumption of the current progress if it has changed in between.
#include <Progress.h>
Public Member Functions
Progress (const std::string &operation)
void update (const std::string &operation, const float amount)
Update the progress with a new absolute amount.
void increment (const std::string &operation, const float increment)
Update the progress with the given increment.
void consume (std::function< void(std::string, float)> callback)
Call the provided callback with the current progress if it has changed since the last invokation.
Public Member Functions inherited from brayns::BaseObject
bool isModified () const
void resetModified ()
Reset the modified state, typically done after changes have been applied.
void markModified ()
Additional Inherited Members
Protected Member Functions inherited from brayns::BaseObject
template<typename T >
void _updateValue (T &member, const T &newValue)
Helper function for derived classes to update a parameter and mark it modified if it has changed.
Detailed Description
A progress object which offers thread-safe progress updates and thread-safe consumption of the current progress if it has changed in between.
Definition at line 35 of file Progress.h.
Member Function Documentation
void brayns::Progress::increment (const std::string & operation, const float increment) inline
Update the progress with the given increment.
Definition at line 53 of file Progress.h.
References brayns::BaseObject::_updateValue().
void brayns::Progress::update (const std::string & operation, const float amount) inline
Update the progress with a new absolute amount.
Definition at line 45 of file Progress.h.
References brayns::BaseObject::_updateValue().
Referenced by brayns::Task< ModelDescriptorPtr >::get().
The documentation for this class was generated from the following file:
Progress.h