Brayns: brayns::TaskFunctor Class Reference
brayns::TaskFunctor Class Reference
A base class for functors that can be used for Tasks.
#include <TaskFunctor.h>
Public Types
using ProgressFunc = std::function< void(std::string, float, float)>
message, increment, amount
Public Member Functions
void setProgressFunc (const ProgressFunc &progressFunc)
Set the function when progress() is called.
void progress (const std::string &message, const float increment, const float amount)
Report progress using the provided callback from setProgressFunc() and also check if the execution has been cancelled.
void setCancelToken (async::cancellation_token &cancelToken)
Set the cancel token from e.g.
void cancelCheck () const
Checks if the execution has been cancelled.
Detailed Description
A base class for functors that can be used for Tasks.
It provides support for progress reporting and cancellation during execution.
Definition at line 40 of file TaskFunctor.h.
Member Function Documentation
void brayns::TaskFunctor::cancelCheck () const inline
Checks if the execution has been cancelled.
If so, this will throw an exception that is ultimately handled by the task and is stored in the tasks' result.
Definition at line 79 of file TaskFunctor.h.
Referenced by progress().
void brayns::TaskFunctor::progress (const std::string & message, const float increment, const float amount) inline
Report progress using the provided callback from setProgressFunc() and also check if the execution has been cancelled.
Parameters
message the progress message
increment the fractional increment of this progress update
amount the absolute amount of progress at the time of this update
Definition at line 60 of file TaskFunctor.h.
References cancelCheck().
void brayns::TaskFunctor::setCancelToken (async::cancellation_token & cancelToken) inline
Set the cancel token from e.g.
the task that uses this functor.
Definition at line 69 of file TaskFunctor.h.
void brayns::TaskFunctor::setProgressFunc (const ProgressFunc & progressFunc) inline
Set the function when progress() is called.
Definition at line 47 of file TaskFunctor.h.
Referenced by brayns::Task< ModelDescriptorPtr >::get().
The documentation for this class was generated from the following file:
TaskFunctor.h