Brayns: brayns::AbstractParameters Class Reference
brayns::AbstractParameters Class Reference abstract
Base class defining command line parameters.
#include <AbstractParameters.h>
Public Member Functions
AbstractParameters (const std::string &name)
Constructor.
virtual void parse (const po::variables_map &vm)=0
Parses parameters managed by the class.
virtual void print ()
Displays values of registered parameters.
po::options_description & parameters ()
Public Member Functions inherited from brayns::BaseObject
bool isModified () const
void resetModified ()
Reset the modified state, typically done after changes have been applied.
void markModified ()
Protected Attributes
std::string _name
po::options_description _parameters
Additional Inherited Members
Protected Member Functions inherited from brayns::BaseObject
template<typename T >
void _updateValue (T &member, const T &newValue)
Helper function for derived classes to update a parameter and mark it modified if it has changed.
Detailed Description
Base class defining command line parameters.
Definition at line 36 of file AbstractParameters.h.
Constructor & Destructor Documentation
brayns::AbstractParameters::AbstractParameters (const std::string & name) inline
Constructor.
Parameters
name Display name for the set of parameters
Definition at line 43 of file AbstractParameters.h.
References parse(), and print().
Member Function Documentation
virtual void brayns::AbstractParameters::parse (const po::variables_map & vm) pure virtual
Parses parameters managed by the class.
Parameters
vm the variables map of all arguments passed by the user
Implemented in brayns::GeometryParameters, brayns::ApplicationParameters, brayns::RenderingParameters, brayns::VolumeParameters, and brayns::SceneParameters.
Referenced by AbstractParameters().
The documentation for this class was generated from the following file:
AbstractParameters.h