Brayns: brayns::OSPRayEngine Class Reference
brayns::OSPRayEngine Class Reference
OSPRay implementation of the ray-tracing engine.
#include <OSPRayEngine.h>
Public Member Functions
OSPRayEngine (ParametersManager &parametersManager)
EngineType name () const final
void commit () final
Commits changes to the engine.
void preRender () final
Executes engine specific pre-render operations.
Vector2ui getSupportedFrameSize (const Vector2ui &size) const final
Constrain size to multiples of the OSPRay tile size in case of streaming using the DeflectPixelOp.
Vector2ui getMinimumFrameSize () const final
bool haveDeflectPixelOp () const final
FrameBufferPtr createFrameBuffer (const Vector2ui &frameSize, FrameBufferFormat frameBufferFormat, bool accumulation) const final
Factory method to create an engine-specific framebuffer.
ScenePtr createScene (ParametersManager &parametersManager) const final
CameraPtr createCamera () const final
Factory method to create an engine-specific camera.
RendererPtr createRenderer (const AnimationParameters &animationParameters, const RenderingParameters &renderingParameters) const final
Public Member Functions inherited from brayns::Engine
Engine (ParametersManager &parametersManager)
Engine constructor.
void render ()
Renders the current scene and populates the frame buffer accordingly.
virtual void postRender ()
Executes engine specific post-render operations.
Scene & getScene ()
Gets the scene.
auto getScenePtr ()
FrameBuffer & getFrameBuffer ()
Gets the frame buffer.
const Camera & getCamera () const
Gets the camera.
Camera & getCamera ()
Renderer & getRenderer ()
Gets the renderer.
void reshape (const Vector2ui &frameSize)
Reshapes the current frame buffers.
void setDefaultCamera ()
Sets initial camera position for the scene handled by the engine.
void initializeMaterials (MaterialsColorMap colorMap=MaterialsColorMap::none)
Initializes materials for the current scene.
void markRebuildScene (const bool rebuild=true)
Mark the scene for building with Brayns::buildScene().
bool rebuildScene () const
void setKeepRunning (bool keepRunning)
Keep continue to run the engine, aka the user did not request to stop rendering.
bool getKeepRunning () const
Statistics & getStatistics ()
bool continueRendering () const
auto & getParametersManager ()
Additional Inherited Members
Public Attributes inherited from brayns::Engine
std::function< void()> triggerRender {[] {}}
Callback when a new frame shall be triggered.
Protected Member Functions inherited from brayns::Engine
void _render (const RenderInput &renderInput, RenderOutput &renderOutput)
void _render ()
void _writeFrameToFile ()
Protected Attributes inherited from brayns::Engine
ParametersManager & _parametersManager
ScenePtr _scene
CameraPtr _camera
RendererPtr _renderer
Vector2i _frameSize
FrameBufferPtr _frameBuffer
Statistics _statistics
bool _keepRunning {true}
bool _rebuildScene {false}
Detailed Description
OSPRay implementation of the ray-tracing engine.
Definition at line 31 of file OSPRayEngine.h.
Member Function Documentation
void brayns::OSPRayEngine::commit () final virtual
Commits changes to the engine.
This include scene, camera and renderer modifications
Reimplemented from brayns::Engine.
CameraPtr brayns::OSPRayEngine::createCamera () const final virtual
Factory method to create an engine-specific camera.
Implements brayns::Engine.
Referenced by haveDeflectPixelOp().
FrameBufferPtr brayns::OSPRayEngine::createFrameBuffer (const Vector2ui & frameSize, FrameBufferFormat frameBufferFormat, bool accumulation) const final virtual
Factory method to create an engine-specific framebuffer.
Implements brayns::Engine.
Referenced by haveDeflectPixelOp().
Vector2ui brayns::OSPRayEngine::getMinimumFrameSize () const final virtual
Returns
the minimum frame size in pixels supported by this engine.
Implements brayns::Engine.
bool brayns::OSPRayEngine::haveDeflectPixelOp () const inline final virtual
Returns
true if for "--module deflect" the DeflectPixelOp was successfully loaded. Only supported for the OSPRay engine.
Reimplemented from brayns::Engine.
Definition at line 57 of file OSPRayEngine.h.
References createCamera(), and createFrameBuffer().
EngineType brayns::OSPRayEngine::name () const final virtual
Returns
the name of the engine
Implements brayns::Engine.
void brayns::OSPRayEngine::preRender () final virtual
Executes engine specific pre-render operations.
Reimplemented from brayns::Engine.
The documentation for this class was generated from the following file:
OSPRayEngine.h