# Site settings
title: BlueBrain Software Directory
organization: BlueBrain

# Build settings
markdown: kramdown

# Do not exclude doxygen files starting with an underscore
include: [ _*.html ]

# Link to other documentation pages
seealso: eyescale.github.io

# The collection of documentation metadata
collections:
  - projects

# Jekyll extensions
gems:
  - jekyll-redirect-from
