var annotated =
[
    [ "boost", null, [
      [ "serialization", null, [
        [ "implementation_level< std::chrono::duration< Rep, Period > >", "structboost_1_1serialization_1_1implementation__level_3_01std_1_1chrono_1_1duration_3_01_rep_00_01_period_01_4_01_4.html", null ],
        [ "implementation_level< std::chrono::time_point< C, D > >", "structboost_1_1serialization_1_1implementation__level_3_01std_1_1chrono_1_1time__point_3_01_c_00_01_d_01_4_01_4.html", null ],
        [ "is_bitwise_serializable< std::chrono::duration< Rep, Period > >", "structboost_1_1serialization_1_1is__bitwise__serializable_3_01std_1_1chrono_1_1duration_3_01_rep_00_01_period_01_4_01_4.html", null ],
        [ "is_bitwise_serializable< std::chrono::time_point< C, D > >", "structboost_1_1serialization_1_1is__bitwise__serializable_3_01std_1_1chrono_1_1time__point_3_01_c_00_01_d_01_4_01_4.html", null ],
        [ "tracking_level< std::chrono::duration< Rep, Period > >", "structboost_1_1serialization_1_1tracking__level_3_01std_1_1chrono_1_1duration_3_01_rep_00_01_period_01_4_01_4.html", null ],
        [ "tracking_level< std::chrono::time_point< C, D > >", "structboost_1_1serialization_1_1tracking__level_3_01std_1_1chrono_1_1time__point_3_01_c_00_01_d_01_4_01_4.html", null ]
      ] ]
    ] ],
    [ "serialization", "namespaceserialization.html", "namespaceserialization" ],
    [ "tide", null, [
      [ "Version", "classtide_1_1_version.html", "classtide_1_1_version" ]
    ] ],
    [ "BackgroundWidget", "class_background_widget.html", "class_background_widget" ],
    [ "BasicSynchronizer", "class_basic_synchronizer.html", "class_basic_synchronizer" ],
    [ "CachedDataSource", "class_cached_data_source.html", "class_cached_data_source" ],
    [ "CairoDeleter", "struct_cairo_deleter.html", "struct_cairo_deleter" ],
    [ "CairoSurfaceDeleter", "struct_cairo_surface_deleter.html", "struct_cairo_surface_deleter" ],
    [ "CommandLineOptions", "class_command_line_options.html", "class_command_line_options" ],
    [ "CommandLineParameters", "class_command_line_parameters.html", "class_command_line_parameters" ],
    [ "Configuration", "class_configuration.html", "class_configuration" ],
    [ "Content", "class_content.html", "class_content" ],
    [ "ContentAction", "class_content_action.html", "class_content_action" ],
    [ "ContentActionsModel", "class_content_actions_model.html", "class_content_actions_model" ],
    [ "ContentController", "class_content_controller.html", "class_content_controller" ],
    [ "ContentFactory", "class_content_factory.html", "class_content_factory" ],
    [ "ContentLoader", "class_content_loader.html", "class_content_loader" ],
    [ "ContentSynchronizer", "class_content_synchronizer.html", "class_content_synchronizer" ],
    [ "ContentWindow", "class_content_window.html", "class_content_window" ],
    [ "ContentWindowController", "class_content_window_controller.html", "class_content_window_controller" ],
    [ "ContentWindowListWidgetItem", "class_content_window_list_widget_item.html", "class_content_window_list_widget_item" ],
    [ "DataProvider", "class_data_provider.html", "class_data_provider" ],
    [ "DataSource", "class_data_source.html", "class_data_source" ],
    [ "DefaultThumbnailGenerator", "class_default_thumbnail_generator.html", "class_default_thumbnail_generator" ],
    [ "DisplayGroup", "class_display_group.html", "class_display_group" ],
    [ "DisplayGroupController", "class_display_group_controller.html", "class_display_group_controller" ],
    [ "DisplayGroupListWidget", "class_display_group_list_widget.html", "class_display_group_list_widget" ],
    [ "DisplayGroupRenderer", "class_display_group_renderer.html", "class_display_group_renderer" ],
    [ "DisplayGroupView", "class_display_group_view.html", "class_display_group_view" ],
    [ "DoubleTapDetector", "class_double_tap_detector.html", "class_double_tap_detector" ],
    [ "DynamicTextureContent", "class_dynamic_texture_content.html", "class_dynamic_texture_content" ],
    [ "ElapsedTimer", "class_elapsed_timer.html", "class_elapsed_timer" ],
    [ "FFMPEGFrame", "class_f_f_m_p_e_g_frame.html", "class_f_f_m_p_e_g_frame" ],
    [ "FFMPEGMovie", "class_f_f_m_p_e_g_movie.html", "class_f_f_m_p_e_g_movie" ],
    [ "FFMPEGPicture", "class_f_f_m_p_e_g_picture.html", "class_f_f_m_p_e_g_picture" ],
    [ "FFMPEGVideoFrameConverter", "class_f_f_m_p_e_g_video_frame_converter.html", "class_f_f_m_p_e_g_video_frame_converter" ],
    [ "FFMPEGVideoStream", "class_f_f_m_p_e_g_video_stream.html", "class_f_f_m_p_e_g_video_stream" ],
    [ "FolderThumbnailGenerator", "class_folder_thumbnail_generator.html", "class_folder_thumbnail_generator" ],
    [ "FpsCounter", "class_fps_counter.html", "class_fps_counter" ],
    [ "Image", "class_image.html", "class_image" ],
    [ "ImagePyramidContent", "class_image_pyramid_content.html", "class_image_pyramid_content" ],
    [ "ImagePyramidDataSource", "class_image_pyramid_data_source.html", "class_image_pyramid_data_source" ],
    [ "ImagePyramidSynchronizer", "class_image_pyramid_synchronizer.html", "class_image_pyramid_synchronizer" ],
    [ "ImagePyramidThumbnailGenerator", "class_image_pyramid_thumbnail_generator.html", "class_image_pyramid_thumbnail_generator" ],
    [ "ImageSource", "class_image_source.html", "class_image_source" ],
    [ "ImageSynchronizer", "class_image_synchronizer.html", "class_image_synchronizer" ],
    [ "ImageThumbnailGenerator", "class_image_thumbnail_generator.html", "class_image_thumbnail_generator" ],
    [ "JsonOptions", "class_json_options.html", "class_json_options" ],
    [ "KeyboardState", "class_keyboard_state.html", "class_keyboard_state" ],
    [ "LayoutEngine", "class_layout_engine.html", "class_layout_engine" ],
    [ "LodSynchronizer", "class_lod_synchronizer.html", "class_lod_synchronizer" ],
    [ "LodTiler", "class_lod_tiler.html", "class_lod_tiler" ],
    [ "LodTools", "class_lod_tools.html", "class_lod_tools" ],
    [ "LoggingUtility", "class_logging_utility.html", "class_logging_utility" ],
    [ "Markers", "class_markers.html", "class_markers" ],
    [ "MasterApplication", "class_master_application.html", "class_master_application" ],
    [ "MasterConfiguration", "class_master_configuration.html", "class_master_configuration" ],
    [ "MasterFromWallChannel", "class_master_from_wall_channel.html", "class_master_from_wall_channel" ],
    [ "MasterToForkerChannel", "class_master_to_forker_channel.html", "class_master_to_forker_channel" ],
    [ "MasterToWallChannel", "class_master_to_wall_channel.html", "class_master_to_wall_channel" ],
    [ "MasterWindow", "class_master_window.html", "class_master_window" ],
    [ "MovieContent", "class_movie_content.html", "class_movie_content" ],
    [ "MovieSynchronizer", "class_movie_synchronizer.html", "class_movie_synchronizer" ],
    [ "MovieThumbnailGenerator", "class_movie_thumbnail_generator.html", "class_movie_thumbnail_generator" ],
    [ "MovieUpdater", "class_movie_updater.html", "class_movie_updater" ],
    [ "MPIChannel", "class_m_p_i_channel.html", "class_m_p_i_channel" ],
    [ "MPIContext", "class_m_p_i_context.html", "class_m_p_i_context" ],
    [ "MPIHeader", "struct_m_p_i_header.html", "struct_m_p_i_header" ],
    [ "MultitouchArea", "class_multitouch_area.html", "class_multitouch_area" ],
    [ "Options", "class_options.html", "class_options" ],
    [ "PanDetector", "class_pan_detector.html", "class_pan_detector" ],
    [ "PDFBackend", "class_p_d_f_backend.html", "class_p_d_f_backend" ],
    [ "PDFContent", "class_p_d_f_content.html", "class_p_d_f_content" ],
    [ "PDFController", "class_p_d_f_controller.html", "class_p_d_f_controller" ],
    [ "PDFPopplerQtBackend", "class_p_d_f_poppler_qt_backend.html", "class_p_d_f_poppler_qt_backend" ],
    [ "PDFSynchronizer", "class_p_d_f_synchronizer.html", "class_p_d_f_synchronizer" ],
    [ "PDFTiler", "class_p_d_f_tiler.html", "class_p_d_f_tiler" ],
    [ "PinchDetector", "class_pinch_detector.html", "class_pinch_detector" ],
    [ "PixelStreamContent", "class_pixel_stream_content.html", "class_pixel_stream_content" ],
    [ "PixelStreamController", "class_pixel_stream_controller.html", "class_pixel_stream_controller" ],
    [ "PixelStreamer", "class_pixel_streamer.html", "class_pixel_streamer" ],
    [ "PixelStreamerFactory", "class_pixel_streamer_factory.html", "class_pixel_streamer_factory" ],
    [ "PixelStreamerLauncher", "class_pixel_streamer_launcher.html", "class_pixel_streamer_launcher" ],
    [ "PixelStreamSynchronizer", "class_pixel_stream_synchronizer.html", "class_pixel_stream_synchronizer" ],
    [ "PixelStreamUpdater", "class_pixel_stream_updater.html", "class_pixel_stream_updater" ],
    [ "PixelStreamWindowManager", "class_pixel_stream_window_manager.html", "class_pixel_stream_window_manager" ],
    [ "ProbeResult", "struct_probe_result.html", "struct_probe_result" ],
    [ "ProcessForker", "class_process_forker.html", "class_process_forker" ],
    [ "QmlKeyInjector", "class_qml_key_injector.html", "class_qml_key_injector" ],
    [ "QmlWindowRenderer", "class_qml_window_renderer.html", "class_qml_window_renderer" ],
    [ "QtImage", "class_qt_image.html", "class_qt_image" ],
    [ "QuadLineNode", "class_quad_line_node.html", "class_quad_line_node" ],
    [ "QuickRenderer", "class_quick_renderer.html", "class_quick_renderer" ],
    [ "ReceiveBuffer", "class_receive_buffer.html", "class_receive_buffer" ],
    [ "Rectangle", "class_rectangle.html", "class_rectangle" ],
    [ "RenderController", "class_render_controller.html", "class_render_controller" ],
    [ "RestCommand", "class_rest_command.html", "class_rest_command" ],
    [ "RestInterface", "class_rest_interface.html", "class_rest_interface" ],
    [ "RestLogger", "class_rest_logger.html", "class_rest_logger" ],
    [ "RestServer", "class_rest_server.html", "class_rest_server" ],
    [ "State", "class_state.html", "class_state" ],
    [ "StatePreview", "class_state_preview.html", "class_state_preview" ],
    [ "StateSerializationHelper", "class_state_serialization_helper.html", "class_state_serialization_helper" ],
    [ "StateThumbnailGenerator", "class_state_thumbnail_generator.html", "class_state_thumbnail_generator" ],
    [ "StaticContent", "class_static_content.html", "class_static_content" ],
    [ "StreamImage", "class_stream_image.html", "class_stream_image" ],
    [ "SVG", "class_s_v_g.html", "class_s_v_g" ],
    [ "SVGBackend", "class_s_v_g_backend.html", "class_s_v_g_backend" ],
    [ "SVGContent", "class_s_v_g_content.html", "class_s_v_g_content" ],
    [ "SVGGpuImage", "class_s_v_g_gpu_image.html", "class_s_v_g_gpu_image" ],
    [ "SVGQtGpuBackend", "class_s_v_g_qt_gpu_backend.html", "class_s_v_g_qt_gpu_backend" ],
    [ "SVGSynchronizer", "class_s_v_g_synchronizer.html", "class_s_v_g_synchronizer" ],
    [ "SVGTiler", "class_s_v_g_tiler.html", "class_s_v_g_tiler" ],
    [ "SwipeDetector", "class_swipe_detector.html", "class_swipe_detector" ],
    [ "TapAndHoldDetector", "class_tap_and_hold_detector.html", "class_tap_and_hold_detector" ],
    [ "TapDetector", "class_tap_detector.html", "class_tap_detector" ],
    [ "TestPattern", "class_test_pattern.html", "class_test_pattern" ],
    [ "TextureContent", "class_texture_content.html", "class_texture_content" ],
    [ "TextureNode", "class_texture_node.html", "class_texture_node" ],
    [ "TextureUploader", "class_texture_uploader.html", "class_texture_uploader" ],
    [ "ThumbnailGenerator", "class_thumbnail_generator.html", "class_thumbnail_generator" ],
    [ "ThumbnailGeneratorFactory", "class_thumbnail_generator_factory.html", "class_thumbnail_generator_factory" ],
    [ "ThumbnailProvider", "class_thumbnail_provider.html", "class_thumbnail_provider" ],
    [ "TiffPyramidReader", "class_tiff_pyramid_reader.html", "class_tiff_pyramid_reader" ],
    [ "Tile", "class_tile.html", "class_tile" ],
    [ "TiledSynchronizer", "class_tiled_synchronizer.html", "class_tiled_synchronizer" ],
    [ "VectorialContent", "class_vectorial_content.html", "class_vectorial_content" ],
    [ "VisibilityHelper", "class_visibility_helper.html", "class_visibility_helper" ],
    [ "WallApplication", "class_wall_application.html", "class_wall_application" ],
    [ "WallConfiguration", "class_wall_configuration.html", "class_wall_configuration" ],
    [ "WallFromMasterChannel", "class_wall_from_master_channel.html", "class_wall_from_master_channel" ],
    [ "WallToMasterChannel", "class_wall_to_master_channel.html", "class_wall_to_master_channel" ],
    [ "WallToWallChannel", "class_wall_to_wall_channel.html", "class_wall_to_wall_channel" ],
    [ "WallWindow", "class_wall_window.html", "class_wall_window" ],
    [ "WebbrowserContent", "class_webbrowser_content.html", "class_webbrowser_content" ],
    [ "WebbrowserController", "class_webbrowser_controller.html", "class_webbrowser_controller" ],
    [ "WebbrowserHistory", "class_webbrowser_history.html", "class_webbrowser_history" ],
    [ "WebbrowserWidget", "class_webbrowser_widget.html", "class_webbrowser_widget" ],
    [ "WebkitAuthenticationHelper", "class_webkit_authentication_helper.html", "class_webkit_authentication_helper" ],
    [ "WebkitHtmlSelectReplacer", "class_webkit_html_select_replacer.html", "class_webkit_html_select_replacer" ],
    [ "WebkitPixelStreamer", "class_webkit_pixel_streamer.html", "class_webkit_pixel_streamer" ],
    [ "ZoomController", "class_zoom_controller.html", "class_zoom_controller" ],
    [ "ZoomHelper", "class_zoom_helper.html", "class_zoom_helper" ]
];