Brayns: brayns::VolumeHandler Class Reference
brayns::VolumeHandler Class Reference
VolumeHandler object.
#include <VolumeHandler.h>
Classes
class VolumeDescriptor
The VolumeDescriptor class handles the attribute of a single volume.
Public Types
typedef std::shared_ptr< VolumeDescriptor > VolumeDescriptorPtr
Public Member Functions
VolumeHandler (const VolumeParameters &volumeParameters, TimestampMode timestampMode)
Default constructor.
Vector3ui getDimensions () const
Returns the dimension of the 8bit volume.
Vector3f getElementSpacing () const
Returns the voxel size of the 8bit volume.
Vector3f getOffset () const
Returns the position offset of the 8bit volume in world coordinates.
uint64_t getSize () const
Returns the size of the 8bit volume in bytes.
void * getData () const
Returns a pointer to a given frame in the memory mapped file.
float getEpsilon (const Vector3f &elementSpacing, const uint16_t samplesPerRay)
Returns the epsilon that defines the step used to walk along the ray when traversing the volume.
void attachVolumeToFile (const float timestamp, const std::string &volumeFile)
Attaches a memory mapped file to the scene so that renderers can access the data as if it was in memory.
void setTimestampMode (const TimestampMode mode)
Sets the timestamp mode.
TimestampMode getTimestampMode () const
Gets the timestamp mode.
void setTimestamp (const float timestamp)
Sets the timestamp for the volume handler.
void setHistogram (const Histogram &histogram)
Set the histogram of the currently loaded volume.
const Histogram & getHistogram ()
uint64_t getNbFrames () const
void setNbFrames (const uint64_t nbFrames)
Sets the number of frames for the current volume.
Detailed Description
VolumeHandler object.
This object contains handle to one or several 8bit volumes. Files containing volumes are accessed via memory maps and each volume is assigned to a given timestamp.
Definition at line 38 of file VolumeHandler.h.
Constructor & Destructor Documentation
brayns::VolumeHandler::VolumeHandler (const VolumeParameters & volumeParameters, TimestampMode timestampMode)
Default constructor.
Parameters
volumeParameters Parameters for the volume (Offset, Scaling, Space between elements)
timestampMode Specifies the way the timestamp in handled:
DEFAULT: Gets the volume corresponding to the timestamp
MODULO : Gets the volume using the timestamp modulo the number of volumes attached to the handler
BOUNDED: The timestamp is bounded by the timestamp range for the attached volumes
Member Function Documentation
void brayns::VolumeHandler::attachVolumeToFile (const float timestamp, const std::string & volumeFile)
Attaches a memory mapped file to the scene so that renderers can access the data as if it was in memory.
The OS is in charge of dealing with the map file in system memory.
Parameters
timestamp Timestamp for the volume
volumeFile File containing the 8bit volume
Returns
True if the file was successfully attached, false otherwise
void* brayns::VolumeHandler::getData () const
Returns a pointer to a given frame in the memory mapped file.
Returns
Pointer to volume
Vector3ui brayns::VolumeHandler::getDimensions () const
Returns the dimension of the 8bit volume.
Returns
Dimensions of the volume for the specified timestamp
Vector3f brayns::VolumeHandler::getElementSpacing () const
Returns the voxel size of the 8bit volume.
Returns
Voxel size of the volume for the specified timestamp
float brayns::VolumeHandler::getEpsilon (const Vector3f & elementSpacing, const uint16_t samplesPerRay)
Returns the epsilon that defines the step used to walk along the ray when traversing the volume.
The value is defined according to the dimensions and scaling of the volume, and the number of samples per ray
Parameters
elementSpacing Scaling between elements of the volume. This attribute represents the voxel size
samplesPerRay Number of samples per ray
Returns
The epsilon
const Histogram& brayns::VolumeHandler::getHistogram ()
Returns
the histogram of the currently loaded volume.
Referenced by setHistogram().
uint64_t brayns::VolumeHandler::getNbFrames () const inline
Returns
the number of frames of the current volume.
Definition at line 143 of file VolumeHandler.h.
Vector3f brayns::VolumeHandler::getOffset () const
Returns the position offset of the 8bit volume in world coordinates.
Returns
Volume offset position for the specified timestamp
uint64_t brayns::VolumeHandler::getSize () const
Returns the size of the 8bit volume in bytes.
Returns
Size of the volume for the specified timestamp
void brayns::VolumeHandler::setHistogram (const Histogram & histogram) inline
Set the histogram of the currently loaded volume.
Definition at line 136 of file VolumeHandler.h.
References getHistogram().
void brayns::VolumeHandler::setNbFrames (const uint64_t nbFrames) inline
Sets the number of frames for the current volume.
Definition at line 145 of file VolumeHandler.h.
void brayns::VolumeHandler::setTimestamp (const float timestamp)
Sets the timestamp for the volume handler.
If the specified timestamp is different from the current one, the current volume is unmapped and the new one is mapped instead
Parameters
timestamp Timestamp for the volume
Referenced by getTimestampMode().
The documentation for this class was generated from the following file:
VolumeHandler.h