Fivox: fivox::ImageSource< TImage > Class Template Reference
fivox::ImageSource< TImage > Class Template Reference
Base class for any image source to sample data from an event source.
#include <imageSource.h>
Public Types
typedef ImageSource Self
Standard class typedefs.
typedef itk::ImageSource< TImage > Superclass
typedef itk::SmartPointer< Self > Pointer
typedef itk::SmartPointer< const Self > ConstPointer
typedef ImageType::RegionType ImageRegionType
typedef ImageType::Pointer ImagePointer
typedef ImageType::ConstPointer ImageConstPointer
typedef ImageType::PixelType ImagePixelType
Typedef to describe the type of pixel.
typedef ImageType::IndexType ImageIndexType
Typedef to describe the output and input image index and size types.
typedef ImageType::SizeType ImageSizeType
Public Member Functions
itkNewMacro (Self) itkTypeMacro(ImageSource
Method for creation through the object factory.
itkStaticConstMacro (ImageDimension, unsigned int, ImageType::ImageDimension)
ImageDimension enumeration.
void setEventSource (EventSourcePtr source)
Set the event source that is used for sampling into the volume.
EventSourcePtr getEventSource ()
void setup (const URIHandler &params)
Setup size and resolution of output volume depending on user input.
const AABBf & getBoundingBox () const
const Vector3f & getSizeInMicrometer () const
const Vector3ui & getSizeInVoxel () const
const Vector3f & getResolution () const
Public Attributes
itk::ImageSource typedef TImage ImageType
Typedef to describe the output image region types.
Protected Member Functions
ImageSource (const Self &)=delete
void operator= (const Self &)=delete
void PrintSelf (std::ostream &os, itk::Indent indent) const override
Protected Attributes
EventSourcePtr _eventSource
ProgressObserver::Pointer _progressObserver
AABBf _boundingBox
Vector3ui _sizeVoxel
Vector3f _sizeMicrometer
Vector3f _resolution
Detailed Description
template<typename TImage>
class fivox::ImageSource< TImage >
Base class for any image source to sample data from an event source.
Definition at line 35 of file imageSource.h.
Member Typedef Documentation
template<typename TImage > typedef ImageType::IndexType fivox::ImageSource< TImage >::ImageIndexType
Typedef to describe the output and input image index and size types.
Definition at line 61 of file imageSource.h.
template<typename TImage > typedef ImageType::PixelType fivox::ImageSource< TImage >::ImagePixelType
Typedef to describe the type of pixel.
Definition at line 58 of file imageSource.h.
template<typename TImage > typedef ImageSource fivox::ImageSource< TImage >::Self
Standard class typedefs.
Definition at line 39 of file imageSource.h.
Member Function Documentation
template<typename TImage > const AABBf& fivox::ImageSource< TImage >::getBoundingBox () const
Returns
the bounding box of the data in micrometers.
Referenced by fivox::ImageSource< TImage >::getEventSource().
template<typename TImage > EventSourcePtr fivox::ImageSource< TImage >::getEventSource () inline
Returns
the event source used for sampling.
Definition at line 75 of file imageSource.h.
References fivox::ImageSource< TImage >::getBoundingBox(), fivox::ImageSource< TImage >::getResolution(), fivox::ImageSource< TImage >::getSizeInMicrometer(), fivox::ImageSource< TImage >::getSizeInVoxel(), and fivox::ImageSource< TImage >::setup().
template<typename TImage > const Vector3f& fivox::ImageSource< TImage >::getResolution () const
Returns
the resolution of the output volume in voxels per micrometer.
Referenced by fivox::ImageSource< TImage >::getEventSource().
template<typename TImage > const Vector3f& fivox::ImageSource< TImage >::getSizeInMicrometer () const
Returns
the size of the output volume in micrometers.
Referenced by fivox::ImageSource< TImage >::getEventSource().
template<typename TImage > const Vector3ui& fivox::ImageSource< TImage >::getSizeInVoxel () const
Returns
the size of the output volume in voxels.
Referenced by fivox::ImageSource< TImage >::getEventSource().
template<typename TImage > fivox::ImageSource< TImage >::itkNewMacro (Self)
Method for creation through the object factory.
Run-time type information (and related methods).
template<typename TImage > void fivox::ImageSource< TImage >::setEventSource (EventSourcePtr source) inline
Set the event source that is used for sampling into the volume.
Definition at line 69 of file imageSource.h.
template<typename TImage > void fivox::ImageSource< TImage >::setup (const URIHandler & params)
Setup size and resolution of output volume depending on user input.
setEventSource() must be called before.
Referenced by fivox::ImageSource< TImage >::getEventSource().
Member Data Documentation
template<typename TImage > itk::ImageSource typedef TImage fivox::ImageSource< TImage >::ImageType
Typedef to describe the output image region types.
Definition at line 51 of file imageSource.h.
The documentation for this class was generated from the following file:
imageSource.h