Rockets: rockets::jsonrpc::Notifier Class Reference
rockets::jsonrpc::Notifier Class Reference abstract
Emitter of JSON-RPC notifications (requests without an id and no response).
#include <notifier.h>
Public Member Functions
void notify (const std::string &method, const std::string &params)
Emit a notification.
template<typename Params >
void notify (const std::string &method, const Params &params)
Emit a notification using a JSON-serializable object.
Protected Member Functions
virtual void _send (std::string json)=0
Detailed Description
Emitter of JSON-RPC notifications (requests without an id and no response).
Definition at line 32 of file notifier.h.
Member Function Documentation
void rockets::jsonrpc::Notifier::notify (const std::string & method, const std::string & params)
Emit a notification.
Parameters
method to call.
params for the notification.
Referenced by notify(), and rockets::jsonrpc::Requester::request().
template<typename Params > void rockets::jsonrpc::Notifier::notify (const std::string & method, const Params & params) inline
Emit a notification using a JSON-serializable object.
Parameters
method to call.
params object to send.
Definition at line 52 of file notifier.h.
References notify().
The documentation for this class was generated from the following file:
notifier.h