Rockets: rockets::jsonrpc::Requester Class Reference
rockets::jsonrpc::Requester Class Reference
Emitter of JSON-RPC requests.
#include <requester.h>
Public Member Functions
ClientRequest< Response > request (const std::string &method, const std::string &params)
Make a request.
size_t request (const std::string &method, const std::string &params, AsyncResponse callback)
Make a request.
template<typename Params , typename RetVal >
ClientRequest< RetVal > request (const std::string &method, const Params &params)
Make a request with templated parameters and result.
template<typename RetVal >
ClientRequest< RetVal > request (const std::string &method)
Make a request with no parameters, but a typed result.
Public Member Functions inherited from rockets::jsonrpc::Notifier
void notify (const std::string &method, const std::string &params)
Emit a notification.
template<typename Params >
void notify (const std::string &method, const Params &params)
Emit a notification using a JSON-serializable object.
Protected Member Functions
bool processResponse (const std::string &json)
Process a JSON-RPC response, calling the associated callback.
Protected Member Functions inherited from rockets::jsonrpc::Notifier
virtual void _send (std::string json)=0
Detailed Description
Emitter of JSON-RPC requests.
Definition at line 38 of file requester.h.
Member Function Documentation
bool rockets::jsonrpc::Requester::processResponse (const std::string & json) protected
Process a JSON-RPC response, calling the associated callback.
Parameters
json response string in JSON-RPC 2.0 format.
Returns
false if the string is not a valid JSON-RPC response or no pending request matches the response id.
Referenced by request().
ClientRequest<Response> rockets::jsonrpc::Requester::request (const std::string & method, const std::string & params)
Make a request.
Parameters
method to call.
params for the request in json format (optional).
Returns
request with future result, can contain a possible error code, but not throw.
Referenced by request().
size_t rockets::jsonrpc::Requester::request (const std::string & method, const std::string & params, AsyncResponse callback)
Make a request.
Parameters
method to call.
params for the request in json format (optional).
callback to handle the result, including a possible error code.
Returns
ID of the request
template<typename Params , typename RetVal > ClientRequest<RetVal> rockets::jsonrpc::Requester::request (const std::string & method, const Params & params) inline
Make a request with templated parameters and result.
Parameters
method to call.
params for the request, must be serializable to JSON with std::string to_json(const Params&)
Returns
Request containing the result of the request, must be serializable from JSON with bool from_json(RetVal& obj, const std::string& json)
Exceptions
response_error if request returns error or from_json on RetVal failed
Definition at line 79 of file requester.h.
References rockets::jsonrpc::Notifier::notify(), and request().
template<typename RetVal > ClientRequest<RetVal> rockets::jsonrpc::Requester::request (const std::string & method) inline
Make a request with no parameters, but a typed result.
Parameters
method to call.
Returns
Request containing the result of the request, must be serializable from JSON with bool from_json(RetVal& obj, const std::string& json)
Exceptions
response_error if request returns error or from_json on RetVal failed
Definition at line 114 of file requester.h.
References rockets::jsonrpc::Notifier::notify(), processResponse(), and request().
The documentation for this class was generated from the following file:
requester.h