Rockets: rockets::jsonrpc::Receiver Class Reference
rockets::jsonrpc::Receiver Class Reference
A base class for receiver implementations which provides synchronous processing of JSON-RPC requests.
#include <receiver.h>
Public Member Functions
Receiver ()
Constructor.
virtual ~Receiver ()
Destructor.
void connect (const std::string &method, VoidCallback action)
Connect a method to a callback with no response and no payload.
void connect (const std::string &method, NotifyCallback action)
Connect a method to a callback with no response.
template<typename Params >
void connect (const std::string &method, std::function< void(Params)> action)
Connect a method to a callback with request parameters but no response.
void bind (const std::string &method, ResponseCallback action)
Bind a method to a response callback.
template<typename Params >
void bind (const std::string &method, std::function< Response(Params)> action)
Bind a method to a response callback with templated request parameters.
template<typename Params , typename RetVal >
void bind (const std::string &method, std::function< RetVal(Params)> action)
Bind a method to a response callback with templated request parameters and templated return type.
template<typename RetVal >
void bind (const std::string &method, std::function< RetVal()> action)
Bind a method to a callback with no parameters but a response.
std::string process (const Request &request)
Process a JSON-RPC request and block for the result.
Protected Member Functions
Receiver (std::unique_ptr< RequestProcessor > impl)
Protected Attributes
std::unique_ptr< RequestProcessor > _impl
Detailed Description
A base class for receiver implementations which provides synchronous processing of JSON-RPC requests.
Definition at line 36 of file receiver.h.
Constructor & Destructor Documentation
rockets::jsonrpc::Receiver::Receiver ()
Constructor.
Referenced by bind().
virtual rockets::jsonrpc::Receiver::~Receiver () virtual
Destructor.
Member Function Documentation
void rockets::jsonrpc::Receiver::bind (const std::string & method, ResponseCallback action)
Bind a method to a response callback.
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Referenced by bind(), and connect().
template<typename Params > void rockets::jsonrpc::Receiver::bind (const std::string & method, std::function< Response(Params)> action) inline
Bind a method to a response callback with templated request parameters.
The parameters object must be deserializable by a free function: from_json(Params& object, const std::string& json).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 111 of file receiver.h.
References bind().
template<typename Params , typename RetVal > void rockets::jsonrpc::Receiver::bind (const std::string & method, std::function< RetVal(Params)> action) inline
Bind a method to a response callback with templated request parameters and templated return type.
The response callback can throw an exception of type response_error to indicate errors.
The parameters object must be deserializable by a free function: from_json(Params& object, const std::string& json). The return type must be serializable by a free function: std::string to_json(const RetVal&)
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 135 of file receiver.h.
References bind().
template<typename RetVal > void rockets::jsonrpc::Receiver::bind (const std::string & method, std::function< RetVal()> action) inline
Bind a method to a callback with no parameters but a response.
The return type must be serializable by a free function: std::string to_json(const RetVal&)
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 164 of file receiver.h.
References bind(), process(), and Receiver().
void rockets::jsonrpc::Receiver::connect (const std::string & method, VoidCallback action)
Connect a method to a callback with no response and no payload.
This is a convienience function that replies with a default "OK" response if the caller asks for one (jsonrpc request id).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
void rockets::jsonrpc::Receiver::connect (const std::string & method, NotifyCallback action)
Connect a method to a callback with no response.
This is a convienience function that replies with a default "OK" response if the caller asks for one (jsonrpc request id).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
template<typename Params > void rockets::jsonrpc::Receiver::connect (const std::string & method, std::function< void(Params)> action) inline
Connect a method to a callback with request parameters but no response.
The templated Params object must be deserializable by a free function: from_json(Params& object, const std::string& json).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 80 of file receiver.h.
References bind().
std::string rockets::jsonrpc::Receiver::process (const Request & request)
Process a JSON-RPC request and block for the result.
Parameters
request Request object with message in JSON-RPC 2.0 format.
Returns
json response string in JSON-RPC 2.0 format.
Referenced by bind().
The documentation for this class was generated from the following file:
receiver.h