Rockets: rockets::jsonrpc::AsyncReceiver Class Reference
rockets::jsonrpc::AsyncReceiver Class Reference
Extends the synchronous receiver by providing asynchronous processing of requests.
#include <asyncReceiver.h>
Public Member Functions
AsyncReceiver ()
Constructor.
void bindAsync (const std::string &method, DelayedResponseCallback action)
Bind a method to an async response callback.
template<typename Params >
void bindAsync (const std::string &method, std::function< void(Params, AsyncResponse)> action)
Bind a method to an async response callback with templated parameters.
std::future< std::string > processAsync (const Request &request)
Process a JSON-RPC request asynchronously.
void process (const Request &request, AsyncStringResponse callback)
Process a JSON-RPC request asynchronously.
Public Member Functions inherited from rockets::jsonrpc::Receiver
Receiver ()
Constructor.
virtual ~Receiver ()
Destructor.
void connect (const std::string &method, VoidCallback action)
Connect a method to a callback with no response and no payload.
void connect (const std::string &method, NotifyCallback action)
Connect a method to a callback with no response.
template<typename Params >
void connect (const std::string &method, std::function< void(Params)> action)
Connect a method to a callback with request parameters but no response.
void bind (const std::string &method, ResponseCallback action)
Bind a method to a response callback.
template<typename Params >
void bind (const std::string &method, std::function< Response(Params)> action)
Bind a method to a response callback with templated request parameters.
template<typename Params , typename RetVal >
void bind (const std::string &method, std::function< RetVal(Params)> action)
Bind a method to a response callback with templated request parameters and templated return type.
template<typename RetVal >
void bind (const std::string &method, std::function< RetVal()> action)
Bind a method to a callback with no parameters but a response.
std::string process (const Request &request)
Process a JSON-RPC request and block for the result.
Protected Member Functions
AsyncReceiver (std::unique_ptr< RequestProcessor > impl)
Protected Member Functions inherited from rockets::jsonrpc::Receiver
Receiver (std::unique_ptr< RequestProcessor > impl)
Additional Inherited Members
Protected Attributes inherited from rockets::jsonrpc::Receiver
std::unique_ptr< RequestProcessor > _impl
Detailed Description
Extends the synchronous receiver by providing asynchronous processing of requests.
Definition at line 35 of file asyncReceiver.h.
Constructor & Destructor Documentation
rockets::jsonrpc::AsyncReceiver::AsyncReceiver ()
Constructor.
Referenced by bindAsync().
Member Function Documentation
void rockets::jsonrpc::AsyncReceiver::bindAsync (const std::string & method, DelayedResponseCallback action)
Bind a method to an async response callback.
Parameters
method to register.
action to perform that will notify the caller upon completion.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Referenced by bindAsync().
template<typename Params > void rockets::jsonrpc::AsyncReceiver::bindAsync (const std::string & method, std::function< void(Params, AsyncResponse)> action) inline
Bind a method to an async response callback with templated parameters.
The parameters object must be deserializable by a free function: from_json(Params& object, const std::string& json).
Parameters
method to register.
action to perform that will notify the caller upon completion.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 61 of file asyncReceiver.h.
References AsyncReceiver(), bindAsync(), process(), and processAsync().
void rockets::jsonrpc::AsyncReceiver::process (const Request & request, AsyncStringResponse callback)
Process a JSON-RPC request asynchronously.
Parameters
request Request object with message in JSON-RPC 2.0 format.
callback that return a json response string in JSON-RPC 2.0 format upon request completion.
Referenced by bindAsync().
std::future<std::string> rockets::jsonrpc::AsyncReceiver::processAsync (const Request & request)
Process a JSON-RPC request asynchronously.
Parameters
request Request object with message in JSON-RPC 2.0 format.
Returns
future json response string in JSON-RPC 2.0 format.
Referenced by bindAsync().
The documentation for this class was generated from the following file:
asyncReceiver.h