Rockets: rockets::jsonrpc::ReceiverInterface Class Reference
rockets::jsonrpc::ReceiverInterface Class Reference abstract
A base class for receiver implementations which provides synchronous and asynchronous processing of JSON-RPC requests.
#include <receiverInterface.h>
Public Types
Callbacks that can be registered.
using VoidCallback = std::function< void()>
using NotifyCallback = std::function< void(Request)>
using ResponseCallback = std::function< Response(Request)>
using DelayedResponseCallback = std::function< void(Request, AsyncResponse)>
Public Member Functions
ReceiverInterface ()
Constructor.
virtual ~ReceiverInterface ()
Destructor.
void connect (const std::string &method, VoidCallback action)
Connect a method to a callback with no response and no payload.
void connect (const std::string &method, NotifyCallback action)
Connect a method to a callback with no response.
template<typename Params >
void connect (const std::string &method, std::function< void(Params)> action)
Connect a method to a callback with request parameters but no response.
void bind (const std::string &method, ResponseCallback action)
Bind a method to a response callback.
template<typename Params >
void bind (const std::string &method, std::function< Response(Params)> action)
Bind a method to a response callback with templated request parameters.
template<typename Params , typename RetVal >
void bind (const std::string &method, std::function< RetVal(Params)> action)
Bind a method to a response callback with templated request parameters and templated return type.
void bindAsync (const std::string &method, DelayedResponseCallback action)
Bind a method to an async response callback.
template<typename Params >
void bindAsync (const std::string &method, std::function< void(Params, AsyncResponse)> action)
Bind a method to an async response callback with templated parameters.
std::string process (const Request &request)
Process a JSON-RPC request and block for the result.
std::future< std::string > processAsync (const Request &request)
Process a JSON-RPC request asynchronously.
void process (const Request &request, AsyncStringResponse callback)
Process a JSON-RPC request asynchronously.
Detailed Description
A base class for receiver implementations which provides synchronous and asynchronous processing of JSON-RPC requests.
A concrete implementation must provide the actual processing of JSON-RPC request, mainly to not leak a JSON library implementation.
Definition at line 41 of file receiverInterface.h.
Constructor & Destructor Documentation
rockets::jsonrpc::ReceiverInterface::ReceiverInterface ()
Constructor.
virtual rockets::jsonrpc::ReceiverInterface::~ReceiverInterface () virtual
Destructor.
Member Function Documentation
void rockets::jsonrpc::ReceiverInterface::bind (const std::string & method, ResponseCallback action)
Bind a method to a response callback.
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Referenced by bind(), and connect().
template<typename Params > void rockets::jsonrpc::ReceiverInterface::bind (const std::string & method, std::function< Response(Params)> action) inline
Bind a method to a response callback with templated request parameters.
The parameters object must be deserializable by a free function: from_json(Params& object, const std::string& json).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 124 of file receiverInterface.h.
References bind().
template<typename Params , typename RetVal > void rockets::jsonrpc::ReceiverInterface::bind (const std::string & method, std::function< RetVal(Params)> action) inline
Bind a method to a response callback with templated request parameters and templated return type.
The response callback can throw an exception of type response_error to indicate errors.
The parameters object must be deserializable by a free function: from_json(Params& object, const std::string& json). The return type must be serializable by a free function: std::string to_json(const RetVal&)
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 148 of file receiverInterface.h.
References bind(), and bindAsync().
void rockets::jsonrpc::ReceiverInterface::bindAsync (const std::string & method, DelayedResponseCallback action)
Bind a method to an async response callback.
Parameters
method to register.
action to perform that will notify the caller upon completion.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Referenced by bind(), and bindAsync().
template<typename Params > void rockets::jsonrpc::ReceiverInterface::bindAsync (const std::string & method, std::function< void(Params, AsyncResponse)> action) inline
Bind a method to an async response callback with templated parameters.
The parameters object must be deserializable by a free function: from_json(Params& object, const std::string& json).
Parameters
method to register.
action to perform that will notify the caller upon completion.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 186 of file receiverInterface.h.
References bindAsync(), process(), and processAsync().
void rockets::jsonrpc::ReceiverInterface::connect (const std::string & method, VoidCallback action)
Connect a method to a callback with no response and no payload.
This is a convienience function that replies with a default "OK" response if the caller asks for one (jsonrpc request id).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
void rockets::jsonrpc::ReceiverInterface::connect (const std::string & method, NotifyCallback action)
Connect a method to a callback with no response.
This is a convienience function that replies with a default "OK" response if the caller asks for one (jsonrpc request id).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
template<typename Params > void rockets::jsonrpc::ReceiverInterface::connect (const std::string & method, std::function< void(Params)> action) inline
Connect a method to a callback with request parameters but no response.
The templated Params object must be deserializable by a free function: from_json(Params& object, const std::string& json).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 93 of file receiverInterface.h.
References bind().
std::string rockets::jsonrpc::ReceiverInterface::process (const Request & request)
Process a JSON-RPC request and block for the result.
Parameters
request Request object with message in JSON-RPC 2.0 format.
Returns
json response string in JSON-RPC 2.0 format.
Referenced by bindAsync().
void rockets::jsonrpc::ReceiverInterface::process (const Request & request, AsyncStringResponse callback)
Process a JSON-RPC request asynchronously.
Parameters
request Request object with message in JSON-RPC 2.0 format.
callback that return a json response string in JSON-RPC 2.0 format upon request completion.
std::future<std::string> rockets::jsonrpc::ReceiverInterface::processAsync (const Request & request)
Process a JSON-RPC request asynchronously.
Parameters
request Request object with message in JSON-RPC 2.0 format.
Returns
future json response string in JSON-RPC 2.0 format.
Referenced by bindAsync().
The documentation for this class was generated from the following file:
receiverInterface.h