var files =
[
    [ "api.h", "api_8h.html", "api_8h" ],
    [ "http/client.h", "http_2client_8h_source.html", null ],
    [ "jsonrpc/client.h", "jsonrpc_2client_8h_source.html", null ],
    [ "ws/client.h", "ws_2client_8h_source.html", null ],
    [ "defines.h", "defines_8h.html", null ],
    [ "definesLinux.h", "defines_linux_8h_source.html", null ],
    [ "errorCodes.h", "error_codes_8h_source.html", null ],
    [ "filter.h", "filter_8h_source.html", null ],
    [ "helpers.h", "helpers_8h_source.html", null ],
    [ "http/helpers.h", "http_2helpers_8h_source.html", null ],
    [ "jsonrpc/helpers.h", "jsonrpc_2helpers_8h_source.html", null ],
    [ "http.h", "http_8h_source.html", null ],
    [ "notifier.h", "notifier_8h_source.html", null ],
    [ "readWriteSocketNotifier.h", "read_write_socket_notifier_8h_source.html", null ],
    [ "receiver.h", "receiver_8h_source.html", null ],
    [ "request.h", "request_8h_source.html", null ],
    [ "requester.h", "requester_8h_source.html", null ],
    [ "http/response.h", "http_2response_8h_source.html", null ],
    [ "jsonrpc/response.h", "jsonrpc_2response_8h_source.html", null ],
    [ "responseError.h", "response_error_8h_source.html", null ],
    [ "rockets.h", "rockets_8h_source.html", null ],
    [ "jsonrpc/server.h", "jsonrpc_2server_8h_source.html", null ],
    [ "server.h", "server_8h_source.html", null ],
    [ "socketBasedInterface.h", "socket_based_interface_8h_source.html", null ],
    [ "socketListener.h", "socket_listener_8h_source.html", null ],
    [ "socketProcessor.h", "socket_processor_8h_source.html", null ],
    [ "http/types.h", "http_2types_8h_source.html", null ],
    [ "jsonrpc/types.h", "jsonrpc_2types_8h_source.html", null ],
    [ "types.h", "types_8h_source.html", null ],
    [ "ws/types.h", "ws_2types_8h_source.html", null ],
    [ "version.h", "version_8h.html", "version_8h" ]
];