ctools: dms_api.h File Reference
dms_api.h File Reference
User API for Distributed MultiScale graphs.
Data Structures
union dms_value
data transfer type for API get/set functions
Typedefs
typedef struct cut_multiscale * dms_t
this pointer type represents a distributed multiscale object
typedef struct cut_vertex * dms_vertex_t
this pointer type represents a vertex object
typedef struct edge * dms_edge_t
this pointer type represents an edge object
typedef struct cut_edge * dms_half_edge_t
this pointer type represents a half edge object (half of a cross-part edge)
typedef struct vertex_child * dms_half_child_t
this pointer type represents a half child object (placeholder for an off-part child)
typedef struct attributed_data * dms_data_t
this pointer type represents the attribute data of some object
typedef struct attribute * dms_attrib_t
this pointer type represents an attribute
Enumerations
enum dms_attribute { DMS_BOOL, DMS_INT, DMS_RAT, DMS_TEXT }
basic datatype descriptor for attributes
enum dms_direction { DMS_OUT, DMS_IN }
the direction of movement through a graph.
Functions
void dms_start (void)
start distributed operation.
void dms_stop (void)
stop distributed operation.
unsigned long dms_part (void)
get local part id.
unsigned long dms_parts (void)
get total count of parts.
dms_t dms_create (void)
create a new distributed multiscale object.
void dms_delete (dms_t m)
delete a distributed multiscale object.
dms_vertex_t dms_add_vertex (dms_t m)
add a vertex to a distributed multiscale graph.
void dms_delete_vertex (dms_vertex_t v)
delete a vertex from a graph.
dms_vertex_t dms_roots (dms_t m)
get the first root vertex of a graph.
dms_vertex_t dms_orphans (dms_t m)
get the first orphan vertex of a graph
dms_vertex_t dms_move_up (dms_vertex_t from)
get a vertex's parent
dms_vertex_t dms_move_down (dms_vertex_t from)
get a vertex's first child vertex
dms_vertex_t dms_move_across (dms_vertex_t from)
get a vertex's next sibling.
void dms_make_child (dms_vertex_t child, dms_vertex_t parent)
move a vertex to make it the child of another vertex
int dms_is_orphan (dms_vertex_t v)
check whether a vertex is an orphan
unsigned long dms_orphan_part (dms_vertex_t v)
get an orphan vertex's parent part id
dms_half_child_t dms_orphan_other (dms_vertex_t v)
get the address of an orphan's matching half child
dms_edge_t dms_add_edge (dms_vertex_t from, dms_vertex_t to)
add an edge
void dms_delete_edge (dms_edge_t e)
delete an edge
dms_edge_t dms_edges (dms_vertex_t v, enum dms_direction d)
begin edges in one direction from a vertex
dms_edge_t dms_next_edge (dms_edge_t e, enum dms_direction d)
get the next edge in one direction from a vertex
dms_vertex_t dms_edge_vertex (dms_edge_t e, enum dms_direction d)
from an edge, get one of its vertices
dms_half_edge_t dms_half_edges (dms_vertex_t v, enum dms_direction d)
get the first half edge in one direction from a vertex
dms_half_edge_t dms_next_half_edge (dms_half_edge_t e)
get the next half edge in one direction from a vertex
dms_vertex_t dms_half_edge_vertex (dms_half_edge_t e, enum dms_direction d)
get the vertex to which a half edge is attached
unsigned long dms_half_edge_part (dms_half_edge_t e)
get the part number of a half edge's other half
dms_half_edge_t dms_half_edge_other (dms_half_edge_t e)
get the part number of a half edge's other half
dms_half_child_t dms_half_children (dms_vertex_t v)
get the first half child of a vertex
dms_half_child_t dms_next_half_child (dms_half_child_t c)
get the next half child of a vertex
dms_vertex_t dms_half_child_parent (dms_half_child_t c)
get the parent vertex of a half child
unsigned long dms_half_child_part (dms_half_child_t c)
get the part number where a half child's matching child vertex is
dms_vertex_t dms_half_child_other (dms_half_child_t c)
get the address of a half child's matching child vertex
dms_attrib_t dms_add_attribute (dms_t ms, enum dms_attribute type, unsigned long count)
create a new attribute of a distributed multiscale graph
dms_attrib_t dms_attributes (dms_t ms)
get the first attribute of a distributed multiscale graph
dms_attrib_t dms_next_attribute (dms_attrib_t a)
get the next attribute of a distributed multiscale graph
enum dms_attribute dms_attribute_type (dms_attrib_t a)
return the basic type of an attribute
unsigned long dms_attribute_count (dms_attrib_t a)
return the element count of an attribute
dms_data_t dms_vertex_data (dms_vertex_t v)
return the data object of a vertex
dms_data_t dms_edge_data (dms_edge_t e)
return the data object of an edge
dms_data_t dms_half_edge_data (dms_half_edge_t e)
return the data object of a half edge
dms_data_t dms_half_child_data (dms_half_child_t c)
return the data object of a half child
void dms_add_data (dms_data_t data, dms_attrib_t a)
add data for an attribute in a data object
void dms_set_data (dms_data_t data, dms_attrib_t a, unsigned long i, union dms_value val)
set the value of an element in attribute data
int dms_has_data (dms_data_t data, dms_attrib_t a)
return nonzero iff a data object has data for a given attribute
void dms_delete_data (dms_data_t data, dms_attrib_t a)
remove the data for a given attribute from a data object
union dms_value dms_get_data (dms_data_t data, dms_attrib_t a, unsigned long i)
get the value of an element in attribute data
void dms_copy_data (dms_t m, dms_data_t from, dms_data_t to)
copy all data from one data object to another.
void dms_mark_for_migration (dms_t ms)
set a distributed multiscale graph up for collective migration
void dms_mark_destination (dms_vertex_t v, unsigned long part)
set the migration destination of a vertex
unsigned long dms_get_destination (dms_vertex_t v)
get the migration destination of a vertex
void dms_migrate (void)
collective migration operation
void dms_print_malloc_stats (void)
Detailed Description
User API for Distributed MultiScale graphs.
This file contains the external API for working with distributed multiscale graphs as supported by the ctools library. It does not include any internals of ctools, so provides a clean, self-contained header file interface for distributed multiscale graphs. Users should only look at the contents of this file (and the documentation generated from it) to use distributed multiscale graphs.
Graph Concept
The graph implementation in ctools represents what graph theory would classify as a bidirectional multigraph. The vertices and edges are first-class objects, and are represented in the API as pointers to opaque structures. Edges are bidirectional in the sense that both vertices can be accessed given an edge reference, and each vertex can access lists of its incoming and outgoing edges. Edges are asymmetric in that there is a clearly defined directionality for edges, and a separation between incoming and outgoing edge lists.
Distributed Graph Concept
Such a graph may be distributed among multiple processes, or parts, such that every vertex in the graph exists on exactly one part. The additional complication of distributing a graph is representing the edges between two parts. These edges are cut in half, and represented by two objects: one half edge on each part. Pairs of half edges point to each other, which means any half edge knows the part number and on-part address of its other half.
Forest Concept
The forest as implemented in ctools is a collection of objects called branches. each branch may have any number of children, which are also branches. Branch A is a parent of B iff B is a child of A. Every branch has zero or one parent branches. A root is a branch that has no parent. When working with a forest, one can access the roots of the forest as one list, and then access the rest of the branches by recursively traversing lists of children.
Distributed Forest Concept
Like graphs, forests may be distributed among multiple parts (processes). Each branch belongs on one part, and parent/child links between different parts are the only complication to manage. An orphan is a branch whose parent exists on a different part. Since orphans cannot be accessed from their parents on the same part, they are stored in a separate orphan list. Each part of a distributed forest has a list of roots and a list of orphans. All the other branches on that part can be reached by traversing down from the roots and the orphans (orphans may still have children on the same part). When a parent/child link is broken between parts, one part ends up with an orphan and the part that has the parent also gets a half-child object. These half-children are placeholders for children on different parts. From any given branch, users may access lists of children and half-children. Each half-child points to the real child branch, which is an orphan somewhere on another part. Similarly, each orphan branch points to its matching half-child object.
Multilevel Graph Concept
A Multilevel Graph is a combination of the Graph and Forest concepts. First, notice that a forest may be separated into levels according to the depth from the roots. A branch is in level N if it takes N moves up the tree to reach the roots. Now, we treat each level as a Graph. That means that branches become vertices as well, and edges may connect them together. The purpose of this complex structure is to represent several models of the same thing, each being more detailed than the last. An object in a simple model is decomposed into many objects in a more complex model, thus the tree structure. Objects in the same model may be arbitrarily associated with one another, thus the graph structure in a level. These objects are still called vertices, as in the graph, but each one is now a combination of a graph vertex and a forest branch.
Distributed Multilevel Graph Concept
Since a Multilevel Graph is a combination of a graph and a forest, and both graphs and forests can be distributed as described above, then the whole multilevel graph can also be distributed. Each vertex of a multilevel graph belongs on one part, edges between parts are handled as described in the Distributed Graph Concept, and parent/child relationships between parts are handled as described in the Distributed Forest Concept. Since the forest provides a good iteration mechanism, this is the way multilevel graph vertices are accessed: by root, orphan, and child lists.
Definition in file dms_api.h.
Enumeration Type Documentation
enum dms_attribute
basic datatype descriptor for attributes
this enum identifies the basic datatype of an attribute
Enumerator:
DMS_BOOL
bit
DMS_INT
signed word-width integer
DMS_RAT
double (rational number)
DMS_TEXT
character
Definition at line 95 of file dms_api.h.
enum dms_direction
the direction of movement through a graph.
directionality is defined as follows: an edge e=(u,v) is in out(u) and in(v), out(e)=v and in(e)=u. The enum below gives clear names to the identifiers for in/out.
Definition at line 149 of file dms_api.h.
Function Documentation
dms_attrib_t dms_add_attribute (dms_t ms, enum dms_attribute type, unsigned long count)
create a new attribute of a distributed multiscale graph
Parameters:
ms the multiscale graph
type the basic type of the attribute
count the number of elements in the attribute
Returns:
the new attribute
Definition at line 279 of file dms_api.c.
References cut_multiscale::attributes.
void dms_add_data (dms_data_t data, dms_attrib_t a)
add data for an attribute in a data object
Parameters:
data the data object
a the attribute
Definition at line 333 of file dms_api.c.
dms_edge_t dms_add_edge (dms_vertex_t from, dms_vertex_t to)
add an edge
create an edge between two vertices on this part.
Parameters:
from the source vertex
to the sink vertex
Returns:
the new edge
Definition at line 158 of file dms_api.c.
dms_vertex_t dms_add_vertex (dms_t m)
add a vertex to a distributed multiscale graph.
the vertex is added as a root and returned by the function.
Parameters:
m the multiscale graph
Returns:
a new root vertex in the graph
Definition at line 66 of file dms_api.c.
unsigned long dms_attribute_count (dms_attrib_t a)
return the element count of an attribute
Parameters:
a the attribute
Returns:
its number of elements
Definition at line 308 of file dms_api.c.
enum dms_attribute dms_attribute_type (dms_attrib_t a)
return the basic type of an attribute
Parameters:
a the attribute
Returns:
its basic type identifier
Definition at line 303 of file dms_api.c.
dms_attrib_t dms_attributes (dms_t ms)
get the first attribute of a distributed multiscale graph
Remarks:
this is used to start iterating over attributes of a graph
Parameters:
ms the multiscale graph
Returns:
the first attribute
Definition at line 293 of file dms_api.c.
References cut_multiscale::attributes.
void dms_copy_data (dms_t m, dms_data_t from, dms_data_t to)
copy all data from one data object to another.
this will make the 'to' object an exact copy of the source, even removing data not found on the 'from' object.
Parameters:
m the multiscale object in which both data objects are
from the object to copy data from
to the object to copy data to
Definition at line 381 of file dms_api.c.
References cut_multiscale::attributes.
dms_t dms_create (void)
create a new distributed multiscale object.
this should be called on every process that plans to share the dms_t object.
Returns:
a new dms_t object
Definition at line 32 of file dms_api.c.
void dms_delete (dms_t m)
delete a distributed multiscale object.
this should be called by every process that called dms_create to make the object.
Parameters:
m the dms_t object to delete
Definition at line 40 of file dms_api.c.
void dms_delete_data (dms_data_t data, dms_attrib_t a)
remove the data for a given attribute from a data object
Parameters:
data the data object
a the attribute
Definition at line 376 of file dms_api.c.
void dms_delete_edge (dms_edge_t e)
delete an edge
removes an edge in constant time from the graph.
Parameters:
e the edge to delete
Definition at line 165 of file dms_api.c.
void dms_delete_vertex (dms_vertex_t v)
delete a vertex from a graph.
this will delete all edges in and out of that vertex and move all of its children to be the children of its parent, or roots if it has no parent. We currently do not provide a good mechanism for this function when the vertex has half edges, half children, or is an orphan.
Definition at line 74 of file dms_api.c.
dms_data_t dms_edge_data (dms_edge_t e)
return the data object of an edge
Parameters:
e the edge
Returns:
the edge's data object
Definition at line 318 of file dms_api.c.
dms_vertex_t dms_edge_vertex (dms_edge_t e, enum dms_direction d)
from an edge, get one of its vertices
Parameters:
e the edge
d the direction from the edge
Returns:
the vertex in that direction from that edge
Definition at line 180 of file dms_api.c.
dms_edge_t dms_edges (dms_vertex_t v, enum dms_direction d)
begin edges in one direction from a vertex
this will return the first edge in the given direction from the given vertex. It is used to start an iteration of edges from a vertex.
Parameters:
v the vertex
d the direction from the vertex
Returns:
the first edge, or NULL
Definition at line 170 of file dms_api.c.
union dms_value dms_get_data (dms_data_t data, dms_attrib_t a, unsigned long i) [write]
get the value of an element in attribute data
Parameters:
data the data object
a the attribute
i the index of the element in the attribute data
Returns:
the value of that data element
Definition at line 386 of file dms_api.c.
unsigned long dms_get_destination (dms_vertex_t v)
get the migration destination of a vertex
Remarks:
the vertex must be in the graph set up for migration with dms_mark_for_migration. This will return the local part number or the part number set with dms_mark_destination.
Parameters:
v the vertex
Returns:
the destination part number
Definition at line 35 of file migrate.c.
References dms_get_destination().
Referenced by dms_get_destination().
dms_data_t dms_half_child_data (dms_half_child_t c)
return the data object of a half child
Parameters:
c the half child
Returns:
the half child's data object
Definition at line 328 of file dms_api.c.
References vertex_child::data.
dms_vertex_t dms_half_child_other (dms_half_child_t c)
get the address of a half child's matching child vertex
Remarks:
this address is only valid on the child vertex's part
Parameters:
c the half child
Returns:
the address of its matching child vertex
Definition at line 274 of file dms_api.c.
dms_vertex_t dms_half_child_parent (dms_half_child_t c)
get the parent vertex of a half child
Parameters:
c the half child
Returns:
the half child's parent vertex
Definition at line 264 of file dms_api.c.
unsigned long dms_half_child_part (dms_half_child_t c)
get the part number where a half child's matching child vertex is
Parameters:
c the half child
Returns:
the matching child vertex's part number
Definition at line 269 of file dms_api.c.
dms_half_child_t dms_half_children (dms_vertex_t v)
get the first half child of a vertex
this is used to start an iteration over half children from a vertex.
Parameters:
v the vertex
Returns:
its first half child
Definition at line 254 of file dms_api.c.
dms_data_t dms_half_edge_data (dms_half_edge_t e)
return the data object of a half edge
Parameters:
e the half edge
Returns:
the half edge's data object
Definition at line 323 of file dms_api.c.
References cut_edge::data.
dms_half_edge_t dms_half_edge_other (dms_half_edge_t e)
get the part number of a half edge's other half
Parameters:
e the half edge
Returns:
the part number where its other half is
Definition at line 227 of file dms_api.c.
unsigned long dms_half_edge_part (dms_half_edge_t e)
get the part number of a half edge's other half
Parameters:
e the half edge
Returns:
the part number where its other half is
Definition at line 222 of file dms_api.c.
dms_vertex_t dms_half_edge_vertex (dms_half_edge_t e, enum dms_direction d)
get the vertex to which a half edge is attached
Parameters:
e the half edge
d the half edge to vertex direction (only the direction to the local vertex is valid)
Returns:
the vertex
Definition at line 217 of file dms_api.c.
dms_half_edge_t dms_half_edges (dms_vertex_t v, enum dms_direction d)
get the first half edge in one direction from a vertex
this is used to start an iteration over half edges from a vertex.
Parameters:
v a vertex
d the direction from the vertex
Returns:
the first half edge in that direction from that vertex
Definition at line 207 of file dms_api.c.
int dms_has_data (dms_data_t data, dms_attrib_t a)
return nonzero iff a data object has data for a given attribute
Parameters:
data the data object
a the attribute
Returns:
0 iff there is no data
Definition at line 371 of file dms_api.c.
int dms_is_orphan (dms_vertex_t v)
check whether a vertex is an orphan
Parameters:
v a vertex
Returns:
zero iff v is not an orphan
Definition at line 135 of file dms_api.c.
void dms_make_child (dms_vertex_t child, dms_vertex_t parent)
move a vertex to make it the child of another vertex
Parameters:
child the vertex to move, will become a child
parent the parent vertex
Definition at line 130 of file dms_api.c.
void dms_mark_destination (dms_vertex_t v, unsigned long part)
set the migration destination of a vertex
Remarks:
the vertex must be in the graph set up for migration with dms_mark_for_migration.
Parameters:
v the vertex
part the destination part number
Definition at line 16 of file migrate.c.
References dms_mark_destination(), and cut_vertex::migrating.
Referenced by dms_mark_destination().
void dms_mark_for_migration (dms_t ms)
set a distributed multiscale graph up for collective migration
all parts must call this function with the correct graph object before marking vertex destinations with dms_mark_destination.
Parameters:
ms the distributed multiscale graph
Definition at line 11 of file migrate.c.
References dms_mark_for_migration().
Referenced by dms_mark_for_migration().
void dms_migrate (void)
collective migration operation
Remarks:
migrate all vertices marked with dms_mark_destination, in the graph marked with dms_mark_for_migration
Postcondition:
all vertices are on their destination parts of the graph, conversions to and from half edges, half children, and orphans are carried out as necessary.
Definition at line 244 of file migrate.c.
References dms_migrate().
Referenced by dms_migrate().
dms_vertex_t dms_move_across (dms_vertex_t from)
get a vertex's next sibling.
this is the way to iterate through the children of a vertex, the roots of a graph, and the orphans of a graph.
Parameters:
from a vertex
Returns:
that vertex's next sibling
Definition at line 125 of file dms_api.c.
dms_vertex_t dms_move_down (dms_vertex_t from)
get a vertex's first child vertex
Parameters:
from a vertex
Returns:
that vertex's first child
Definition at line 120 of file dms_api.c.
dms_vertex_t dms_move_up (dms_vertex_t from)
get a vertex's parent
Parameters:
from a vertex
Returns:
the vertex's parent, or NULL
Definition at line 115 of file dms_api.c.
dms_attrib_t dms_next_attribute (dms_attrib_t a)
get the next attribute of a distributed multiscale graph
Remarks:
this is used to iterate over attributes of a graph
Parameters:
a the current attribute
Returns:
the next attribute
Definition at line 298 of file dms_api.c.
dms_edge_t dms_next_edge (dms_edge_t e, enum dms_direction d)
get the next edge in one direction from a vertex
this is used to continue an iteration over edges from a vertex
Parameters:
e the current edge
d the direction from the vertex
Returns:
the next edge, or NULL
Definition at line 175 of file dms_api.c.
dms_half_child_t dms_next_half_child (dms_half_child_t c)
get the next half child of a vertex
this is used to iterate over half children from a vertex.
Parameters:
c the current half child
Returns:
the next half child
Definition at line 259 of file dms_api.c.
dms_half_edge_t dms_next_half_edge (dms_half_edge_t e)
get the next half edge in one direction from a vertex
this is used to iterate over half edges from a vertex.
Parameters:
e the current half edge
Returns:
the next half edge in that direction from that vertex
Definition at line 212 of file dms_api.c.
dms_half_child_t dms_orphan_other (dms_vertex_t v)
get the address of an orphan's matching half child
given an orphan vertex, this returns the address of the half child object connected to it. Since these objects are on different parts, the address returned is not valid on this part and should only be used for coordination in higher-level algorithms.
Parameters:
v an orphan vertex
Returns:
on-part address of the matching half child
Definition at line 145 of file dms_api.c.
unsigned long dms_orphan_part (dms_vertex_t v)
get an orphan vertex's parent part id
Parameters:
v an orphan vertex
Returns:
part id or the vertex's parent
Definition at line 140 of file dms_api.c.
dms_vertex_t dms_orphans (dms_t m)
get the first orphan vertex of a graph
Parameters:
m a distributed multiscale graph
Returns:
the first orphan vertex in that graph, or NULL
Definition at line 110 of file dms_api.c.
unsigned long dms_part (void)
get local part id.
for the moment, this is the cached value of MPI_Comm_rank.
Returns:
local part id
Definition at line 22 of file dms_api.c.
unsigned long dms_parts (void)
get total count of parts.
For the moment, this is the cache value of MPI_Comm_size.
Returns:
total part count
Definition at line 27 of file dms_api.c.
dms_vertex_t dms_roots (dms_t m)
get the first root vertex of a graph.
there are no separate iterators in this API, vertices are traversed using their own pointers.
Parameters:
m a distributed multiscale graph
Returns:
the first root vertex in that graph, or NULL
Definition at line 105 of file dms_api.c.
void dms_set_data (dms_data_t data, dms_attrib_t a, unsigned long i, union dms_value val)
set the value of an element in attribute data
Parameters:
data the data object where the data is
a the attribute of the data
i the element index in the data
val the value to set
Definition at line 366 of file dms_api.c.
void dms_start (void)
start distributed operation.
this function initializes all the internal parallel systems. (It calls MPI_Init if needed). It is required to call this function before calling any other dms function.
Definition at line 12 of file dms_api.c.
void dms_stop (void)
stop distributed operation.
this function finalizes all the internal parallel systems. (It calls MPI_Finalize if needed). It is required to call this function after all other dms function calls.
Definition at line 17 of file dms_api.c.
dms_data_t dms_vertex_data (dms_vertex_t v)
return the data object of a vertex
Parameters:
v the vertex
Returns:
the vertex's data object
Definition at line 313 of file dms_api.c.
References cut_vertex::data.