Tide: Image Class Reference
Image Class Reference abstract
An interface to provide necessary image information for the texture upload.
#include <Image.h>
Public Member Functions
virtual int getWidth () const =0
virtual int getHeight () const =0
virtual QSize getTextureSize (uint texture=0) const
virtual const uint8_t * getData (uint texture=0) const =0
virtual size_t getDataSize (const uint texture=0) const
virtual deflect::RowOrder getRowOrder () const
virtual TextureFormat getFormat () const =0
virtual ColorSpace getColorSpace () const
virtual uint getGLPixelFormat () const =0
virtual bool isGpuImage () const
virtual bool generateGpuImage ()
Generate the GPU image.
Detailed Description
An interface to provide necessary image information for the texture upload.
Valid image formats are:
RGBA: 1 texture plane, 32 bits per pixel (in any GL-compatible arrangement)
YUV: 3 texture planes, 8 bits per pixel
Derived classes must comply with this requirement.
Definition at line 55 of file Image.h.
Member Function Documentation
virtual bool Image::generateGpuImage () inline virtual
Generate the GPU image.
This method will be called on a thread with an active OpenGL context if isGpuImage() is true;
Reimplemented in SVGGpuImage.
Definition at line 104 of file Image.h.
virtual ColorSpace Image::getColorSpace () const inline virtual
Returns
the color space of the image.
Reimplemented in StreamImage, and FFMPEGPicture.
Definition at line 93 of file Image.h.
References getGLPixelFormat().
virtual const uint8_t* Image::getData (uint texture = 0) const pure virtual
Returns
the pointer to the pixels of the given texture plane.
Implemented in QtImage, FFMPEGPicture, SVGGpuImage, and StreamImage.
Referenced by getTextureSize().
virtual size_t Image::getDataSize (const uint texture = 0) const inline virtual
Returns
the size of the pixel data buffer of the given texture plane.
Reimplemented in FFMPEGPicture.
Definition at line 76 of file Image.h.
References getFormat(), and getTextureSize().
virtual TextureFormat Image::getFormat () const pure virtual
Returns
the format of the image.
Implemented in QtImage, StreamImage, FFMPEGPicture, and SVGGpuImage.
Referenced by getDataSize(), and getRowOrder().
virtual uint Image::getGLPixelFormat () const pure virtual
Returns
the OpenGL pixel format of the image data.
Implemented in QtImage, SVGGpuImage, and YUVImage.
Referenced by getColorSpace().
virtual int Image::getHeight () const pure virtual
Returns
the height of the image.
Implemented in QtImage, FFMPEGPicture, SVGGpuImage, and StreamImage.
Referenced by getTextureSize().
virtual deflect::RowOrder Image::getRowOrder () const inline virtual
Returns
the row order of the image data.
Reimplemented in StreamImage.
Definition at line 84 of file Image.h.
References getFormat().
virtual QSize Image::getTextureSize (uint texture = 0) const inline virtual
Returns
the dimensions of the given texture plane.
Reimplemented in YUVImage.
Definition at line 67 of file Image.h.
References getData(), getHeight(), and getWidth().
Referenced by getDataSize().
virtual int Image::getWidth () const pure virtual
Returns
the width of the image.
Implemented in QtImage, FFMPEGPicture, SVGGpuImage, and StreamImage.
Referenced by getTextureSize().
virtual bool Image::isGpuImage () const inline virtual
Returns
true if the image is a GPU image and need special processing.
Reimplemented in SVGGpuImage.
Definition at line 98 of file Image.h.
The documentation for this class was generated from the following file:
Image.h