Tide: MovieUpdater Class Reference
MovieUpdater Class Reference
Updates Movies synchronously across different processes.
#include <MovieUpdater.h>
Signals
void pictureUpdated ()
Emitted when a new picture has become available.
Public Member Functions
MovieUpdater (const QString &uri)
bool isDynamic () const final
ImagePtr getTileImage (uint tileIndex, deflect::View view) const final
Get a tile image by its id for a given view.
QRect getTileRect (uint tileIndex) const final
Get the coordinates of a tile.
QSize getTilesArea (uint lod) const final
Indices computeVisibleSet (const QRectF &visibleTilesArea, uint lod) const final
Compute the indices of the tiles which are visible in the given area.
uint getMaxLod () const final
void update (const MovieContent &movie)
Update this datasource according to visibility and movie content.
void synchronizeFrameAdvance (WallToWallChannel &channel)
Synchronize frame advance accross all processes.
void getNextFrame ()
Indicates that the last requested frame was consumed and we can advance to the next frame.
QString getStatistics () const
qreal getPosition () const
bool isSkipping () const
bool isPaused () const
qreal getSkipPosition () const
Additional Inherited Members
Public Attributes inherited from DataSource
std::set< ContentSynchronizer * > synchronizers
The synchronizers linked to this shared data source.
Detailed Description
Updates Movies synchronously across different processes.
A single movie is designed to provide images to multiple windows on each process.
Definition at line 57 of file MovieUpdater.h.
Member Function Documentation
Indices MovieUpdater::computeVisibleSet (const QRectF & visibleTilesArea, uint lod) const final virtual
Compute the indices of the tiles which are visible in the given area.
Implements DataSource.
Referenced by isDynamic().
uint MovieUpdater::getMaxLod () const final virtual
Returns
the max LOD level (top of pyramid, lowest resolution).
Implements DataSource.
Referenced by isDynamic().
qreal MovieUpdater::getPosition () const
Returns
current position of the movie, normalized between [0.0, 1.0].
Referenced by isDynamic().
qreal MovieUpdater::getSkipPosition () const
Returns
skip position of the movie, normalized between [0.0, 1.0].
Referenced by isDynamic().
QString MovieUpdater::getStatistics () const
Returns
current / max fps, movie position in percentage.
Referenced by isDynamic().
ImagePtr MovieUpdater::getTileImage (uint tileIndex, deflect::View view) const final virtual
Get a tile image by its id for a given view.
Called asynchronously but not concurrently. threadsafe. threadsafe
Implements DataSource.
Referenced by isDynamic().
QRect MovieUpdater::getTileRect (uint tileIndex) const final virtual
Get the coordinates of a tile.
Implements DataSource.
Referenced by isDynamic().
QSize MovieUpdater::getTilesArea (uint lod) const final virtual
Returns
the image size for the requested lod.
Implements DataSource.
Referenced by isDynamic().
bool MovieUpdater::isDynamic () const inline final virtual
Returns
true if the data source produces dynamic contents.
Reimplemented from DataSource.
Definition at line 67 of file MovieUpdater.h.
References computeVisibleSet(), getMaxLod(), getNextFrame(), getPosition(), getSkipPosition(), getStatistics(), getTileImage(), getTileRect(), getTilesArea(), isPaused(), isSkipping(), pictureUpdated(), synchronizeFrameAdvance(), and update().
bool MovieUpdater::isPaused () const
Returns
true if the movie is paused.
Referenced by isDynamic().
bool MovieUpdater::isSkipping () const
Returns
true if the user is currently skipping the movie.
Referenced by isDynamic().
void MovieUpdater::pictureUpdated () signal
Emitted when a new picture has become available.
Referenced by isDynamic().
void MovieUpdater::synchronizeFrameAdvance (WallToWallChannel & channel)
Synchronize frame advance accross all processes.
Referenced by isDynamic().
void MovieUpdater::update (const MovieContent & movie)
Update this datasource according to visibility and movie content.
Referenced by isDynamic().
The documentation for this class was generated from the following file:
MovieUpdater.h