Tide: TextureNodeRGBA Class Reference
TextureNodeRGBA Class Reference
A node with a double buffered texture.
#include <TextureNodeRGBA.h>
Public Member Functions
TextureNodeRGBA (QQuickWindow &window, bool dynamic)
Create a textured rectangle for rendering RGBA images on the GPU.
void setMipmapFiltering (QSGTexture::Filtering filtering)
QRectF getCoord () const final
void setCoord (const QRectF &coord) final
Set the surface of the node.
void uploadTexture (const Image &image) final
Upload the given image to the back PBO.
void swap () final
Swap the PBOs and update the texture with the back PBO's contents.
Detailed Description
A node with a double buffered texture.
Initially it displays an empty black texture (id 0). Users can upload data asynchronously to the texture and call swap() on the next frame rendering to display the results.
The texture can be either static or dynamic:
In the dynamic case, two PBOs are used for real-time texture updates.
In the static case, a single PBO is used for the initial texture upload and then released in the first call to swap() so that no memory is wasted.
Definition at line 63 of file TextureNodeRGBA.h.
Constructor & Destructor Documentation
TextureNodeRGBA::TextureNodeRGBA (QQuickWindow & window, bool dynamic)
Create a textured rectangle for rendering RGBA images on the GPU.
Parameters
window a reference to the quick window for generating textures.
dynamic true if the texture is going to be updated more than once.
Member Function Documentation
QRectF TextureNodeRGBA::getCoord () const inline final virtual
Returns
the surface of the node.
Implements TextureNode.
Definition at line 76 of file TextureNodeRGBA.h.
void TextureNodeRGBA::setCoord (const QRectF & coord) inline final virtual
Set the surface of the node.
Implements TextureNode.
Definition at line 77 of file TextureNodeRGBA.h.
References swap(), and uploadTexture().
void TextureNodeRGBA::setMipmapFiltering (QSGTexture::Filtering filtering)
See also
QSGOpaqueTextureMaterial::setMipmapFiltering
void TextureNodeRGBA::swap () final virtual
Swap the PBOs and update the texture with the back PBO's contents.
Implements TextureNode.
Referenced by setCoord().
void TextureNodeRGBA::uploadTexture (const Image & image) final virtual
Upload the given image to the back PBO.
Implements TextureNode.
Referenced by setCoord().
The documentation for this class was generated from the following file:
TextureNodeRGBA.h