Tide: PixelStreamUpdater Class Reference
PixelStreamUpdater Class Reference
Synchronize the update of PixelStreams and send new frame requests.
#include <PixelStreamUpdater.h>
Public Slots
void updatePixelStream (deflect::FramePtr frame)
Update the appropriate PixelStream with the given frame.
Signals
void pictureUpdated ()
Emitted when a new picture has become available.
void requestFrame (QString uri)
Emitted to request a new frame after a successful swap.
Public Member Functions
PixelStreamUpdater ()
Constructor.
~PixelStreamUpdater ()
Destructor.
bool isDynamic () const final
ImagePtr getTileImage (uint tileIndex, deflect::View view) const final
Get a tile image by its id for a given view.
QRect getTileRect (uint tileIndex) const final
Get the coordinates of a tile.
QSize getTilesArea (uint lod) const final
Indices computeVisibleSet (const QRectF &visibleTilesArea, uint lod) const final
Compute the indices of the tiles which are visible in the given area.
uint getMaxLod () const final
void synchronizeFrameAdvance (WallToWallChannel &channel)
Synchronize the advance to the next frame of the stream.
void getNextFrame ()
Allow advancing to the next frame of the stream (flow control).
Additional Inherited Members
Public Attributes inherited from DataSource
std::set< ContentSynchronizer * > synchronizers
The synchronizers linked to this shared data source.
Detailed Description
Synchronize the update of PixelStreams and send new frame requests.
Definition at line 56 of file PixelStreamUpdater.h.
Constructor & Destructor Documentation
PixelStreamUpdater::PixelStreamUpdater ()
Constructor.
PixelStreamUpdater::~PixelStreamUpdater ()
Destructor.
Member Function Documentation
Indices PixelStreamUpdater::computeVisibleSet (const QRectF & visibleTilesArea, uint lod) const final virtual
Compute the indices of the tiles which are visible in the given area.
Implements DataSource.
Referenced by isDynamic().
uint PixelStreamUpdater::getMaxLod () const final virtual
Returns
the max LOD level (top of pyramid, lowest resolution).
Implements DataSource.
Referenced by isDynamic().
void PixelStreamUpdater::getNextFrame ()
Allow advancing to the next frame of the stream (flow control).
Referenced by isDynamic().
ImagePtr PixelStreamUpdater::getTileImage (uint tileIndex, deflect::View view) const final virtual
Get a tile image by its id for a given view.
Called asynchronously but not concurrently. threadsafe. threadsafe
Implements DataSource.
Referenced by isDynamic().
QRect PixelStreamUpdater::getTileRect (uint tileIndex) const final virtual
Get the coordinates of a tile.
Implements DataSource.
Referenced by isDynamic().
QSize PixelStreamUpdater::getTilesArea (uint lod) const final virtual
Returns
the image size for the requested lod.
Implements DataSource.
Referenced by isDynamic().
bool PixelStreamUpdater::isDynamic () const inline final virtual
Returns
true if the data source produces dynamic contents.
Reimplemented from DataSource.
Definition at line 69 of file PixelStreamUpdater.h.
References computeVisibleSet(), getMaxLod(), getNextFrame(), getTileImage(), getTileRect(), getTilesArea(), pictureUpdated(), requestFrame(), synchronizeFrameAdvance(), and updatePixelStream().
void PixelStreamUpdater::pictureUpdated () signal
Emitted when a new picture has become available.
Referenced by isDynamic().
void PixelStreamUpdater::requestFrame (QString uri) signal
Emitted to request a new frame after a successful swap.
Referenced by isDynamic().
void PixelStreamUpdater::synchronizeFrameAdvance (WallToWallChannel & channel)
Synchronize the advance to the next frame of the stream.
Referenced by isDynamic().
void PixelStreamUpdater::updatePixelStream (deflect::FramePtr frame) slot
Update the appropriate PixelStream with the given frame.
Referenced by isDynamic().
The documentation for this class was generated from the following file:
PixelStreamUpdater.h