Tide: JsonRpc Class Reference
JsonRpc Class Reference
JSON-RPC 2.0 request processor.
#include <JsonRpc.h>
Classes
struct Response
Response to a well-formed RPC request.
Public Types
Asynchronous response to a request.
using AsyncResponse = std::function< void(Response)>
using ProcessAsyncCallback = std::function< void(std::string)>
Callbacks that can be registered.
using ResponseCallback = std::function< Response(const std::string &)>
using ResponseCallbackAsync = std::function< void(const std::string &, AsyncResponse)>
using NotifyCallback = std::function< void(const std::string &)>
using VoidCallback = std::function< void()>
Public Member Functions
JsonRpc ()
Constructor.
~JsonRpc ()
Destructor.
void bind (const std::string &method, ResponseCallback action)
Bind a method to a response callback.
template<typename Params >
void bind (const std::string &method, std::function< Response(Params)> action)
Bind a method to a response callback with templated request parameters.
void bindAsync (const std::string &method, ResponseCallbackAsync action)
Bind a method to an async response callback.
template<typename Params >
void bindAsync (const std::string &method, std::function< void(Params, AsyncResponse)> action)
Bind a method to an async response callback with templated parameters.
template<typename Params >
void notify (const std::string &method, std::function< void(Params)> action)
Bind a method to a callback with request parameters but no response.
void notify (const std::string &method, NotifyCallback action)
Bind a method to a callback with no response.
void notify (const std::string &method, VoidCallback action)
Bind a method to a callback with no response and no payload.
std::string process (const std::string &request)
Process a JSON-RPC request and block for the result.
std::future< std::string > processAsync (const std::string &request)
Process a JSON-RPC request asynchronously.
void process (const std::string &request, ProcessAsyncCallback callback)
Process a JSON-RPC request asynchronously.
Detailed Description
JSON-RPC 2.0 request processor.
See specification: http://www.jsonrpc.org/specification
Definition at line 53 of file JsonRpc.h.
Constructor & Destructor Documentation
JsonRpc::JsonRpc ()
Constructor.
JsonRpc::~JsonRpc ()
Destructor.
Member Function Documentation
void JsonRpc::bind (const std::string & method, ResponseCallback action)
Bind a method to a response callback.
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Referenced by bind(), and notify().
template<typename Params > void JsonRpc::bind (const std::string & method, std::function< Response(Params)> action) inline
Bind a method to a response callback with templated request parameters.
The parameters object must be deserializable by a free function: from_json(Params& object, const std::string& json).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 119 of file JsonRpc.h.
References bind(), and bindAsync().
void JsonRpc::bindAsync (const std::string & method, ResponseCallbackAsync action)
Bind a method to an async response callback.
Parameters
method to register.
action to perform that will notify the caller upon completion.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Referenced by bind(), and bindAsync().
template<typename Params > void JsonRpc::bindAsync (const std::string & method, std::function< void(Params, AsyncResponse)> action) inline
Bind a method to an async response callback with templated parameters.
The parameters object must be deserializable by a free function: from_json(Params& object, const std::string& json).
Parameters
method to register.
action to perform that will notify the caller upon completion.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 149 of file JsonRpc.h.
References bindAsync().
template<typename Params > void JsonRpc::notify (const std::string & method, std::function< void(Params)> action) inline
Bind a method to a callback with request parameters but no response.
The templated Params object must be deserializable by a free function: from_json(Params& object, const std::string& json).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
Definition at line 173 of file JsonRpc.h.
References bind(), process(), and processAsync().
void JsonRpc::notify (const std::string & method, NotifyCallback action)
Bind a method to a callback with no response.
This is a convienience function that replies with a default "OK" response if the caller asks for one (jsonrpc request id).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
void JsonRpc::notify (const std::string & method, VoidCallback action)
Bind a method to a callback with no response and no payload.
This is a convienience function that replies with a default "OK" response if the caller asks for one (jsonrpc request id).
Parameters
method to register.
action to perform.
Exceptions
std::invalid_argument if the method name starts with "rpc."
std::string JsonRpc::process (const std::string & request)
Process a JSON-RPC request and block for the result.
Parameters
request string in JSON-RPC 2.0 format.
Returns
json response string in JSON-RPC 2.0 format.
Referenced by notify().
void JsonRpc::process (const std::string & request, ProcessAsyncCallback callback)
Process a JSON-RPC request asynchronously.
Parameters
request string in JSON-RPC 2.0 format.
callback that return a json response string in JSON-RPC 2.0 format upon request completion.
std::future<std::string> JsonRpc::processAsync (const std::string & request)
Process a JSON-RPC request asynchronously.
Parameters
request string in JSON-RPC 2.0 format.
Returns
future json response string in JSON-RPC 2.0 format.
Referenced by notify().
The documentation for this class was generated from the following file:
JsonRpc.h