Tide: WindowController Class Reference
WindowController Class Reference
Controller for moving and resizing windows.
#include <WindowController.h>
Public Types
enum Coordinates { STANDARD, FOCUSED, FULLSCREEN, AUTO }
The set of window coordinates that the controller acts upon.
Public Member Functions
WindowController (Window &window, const DisplayGroup &group, Coordinates target=Coordinates::AUTO)
Create a controller for a window.
Q_INVOKABLE void resize (const QSizeF &size, WindowPoint fixedPoint=TOP_LEFT)
Resize the window.
Q_INVOKABLE void resizeRelative (const QPointF &delta)
Resize the window relative to the current active window border.
Q_INVOKABLE void scale (const QPointF &center, double pixelDelta)
Scale the window by the given pixel delta (around the given center).
Q_INVOKABLE void scale (const QPointF &center, const QPointF &pixelDelta)
void adjustSize (const SizeState state)
Adjust the window coordinates to match the desired state.
Q_INVOKABLE void toogleFullscreenMaxSize ()
Toggle between SIZE_FULLSCREEN and SIZE_FULLSCREEN_MAX.
Q_INVOKABLE void toggleSelected ()
Toggle the selected state of the window.
Q_INVOKABLE void moveTo (const QPointF &position, WindowPoint handle=TOP_LEFT)
Move the window to the desired position.
void moveCenterTo (const QPointF &position)
Move the center of the window to the desired position.
Q_INVOKABLE void moveBy (const QPointF &delta)
Move the window by the given delta.
QSizeF getMinSize () const
QSizeF getMaxSize () const
void constrainSize (QSizeF &windowSize) const
Constrain the given size between getMinSize() and getMaxSize().
QSizeF getMinSizeAspectRatioCorrect () const
UI resize handle events.
Q_INVOKABLE void startResizing (const Window::ResizeHandle handle)
Q_INVOKABLE void toggleResizeMode ()
Q_INVOKABLE void stopResizing ()
Detailed Description
Controller for moving and resizing windows.
Definition at line 69 of file WindowController.h.
Constructor & Destructor Documentation
WindowController::WindowController (Window & window, const DisplayGroup & group, Coordinates target = Coordinates::AUTO)
Create a controller for a window.
Parameters
window the target window
group the group to which the window belongs
target the set of coordinates to modify (default: AUTO)
Member Function Documentation
void WindowController::adjustSize (const SizeState state)
Adjust the window coordinates to match the desired state.
void WindowController::constrainSize (QSizeF & windowSize) const
Constrain the given size between getMinSize() and getMaxSize().
Referenced by moveCenterTo().
QSizeF WindowController::getMaxSize () const
Returns
the maximum size of the window, considering max size of content, wall size and current content zoom.
Referenced by moveCenterTo().
QSizeF WindowController::getMinSize () const
Returns
the minimum size of the window, 5% of wall size or 300px.
Referenced by moveCenterTo().
QSizeF WindowController::getMinSizeAspectRatioCorrect () const
Returns
the minimum size of the window respecting its aspect ratio.
Referenced by moveCenterTo().
Q_INVOKABLE void WindowController::moveBy (const QPointF & delta)
Move the window by the given delta.
Referenced by moveCenterTo().
void WindowController::moveCenterTo (const QPointF & position) inline
Move the center of the window to the desired position.
Definition at line 127 of file WindowController.h.
References constrainSize(), getMaxSize(), getMinSize(), getMinSizeAspectRatioCorrect(), moveBy(), and moveTo().
Q_INVOKABLE void WindowController::moveTo (const QPointF & position, WindowPoint handle = TOP_LEFT)
Move the window to the desired position.
Referenced by moveCenterTo().
Q_INVOKABLE void WindowController::resize (const QSizeF & size, WindowPoint fixedPoint = TOP_LEFT)
Resize the window.
Q_INVOKABLE void WindowController::scale (const QPointF & center, double pixelDelta)
Scale the window by the given pixel delta (around the given center).
Q_INVOKABLE void WindowController::toggleSelected ()
Toggle the selected state of the window.
Q_INVOKABLE void WindowController::toogleFullscreenMaxSize ()
Toggle between SIZE_FULLSCREEN and SIZE_FULLSCREEN_MAX.
The documentation for this class was generated from the following file:
WindowController.h