Tide: Background Class Reference
Background Class Reference
Background color and content.
#include <Background.h>
Signals
void updated (BackgroundPtr)
Emitted when any value is changed by one of the setters.
Public Member Functions
~Background ()
Destructor.
QColor getColor () const
Get the color of the background.
QString getText () const
Get the text to display on the background.
QString getUri () const
Get the uri of the background content.
void setColor (QColor color)
Set the color of the background.
void setText (const QString &text)
Set the text to display on the background.
void setUri (const QString &uri)
Set the background content from a uri.
Accessors for internal properties, used on the wall only.
const Content * getContent () const
const QUuid & getContentUUID () const
Static Public Member Functions
static BackgroundPtr create ()
Create a shared Options object.
Friends
class boost::serialization::access
Detailed Description
Background color and content.
Can be serialized and distributed to the Wall applications.
Definition at line 55 of file Background.h.
Constructor & Destructor Documentation
Background::~Background ()
Destructor.
Referenced by create().
Member Function Documentation
static BackgroundPtr Background::create () inline static
Create a shared Options object.
Definition at line 63 of file Background.h.
References getColor(), getText(), getUri(), setColor(), setText(), setUri(), updated(), and ~Background().
QColor Background::getColor () const
Get the color of the background.
Referenced by create().
QString Background::getText () const
Get the text to display on the background.
Referenced by create().
QString Background::getUri () const
Get the uri of the background content.
Referenced by create().
void Background::setColor (QColor color)
Set the color of the background.
Referenced by create().
void Background::setText (const QString & text)
Set the text to display on the background.
Referenced by create().
void Background::setUri (const QString & uri)
Set the background content from a uri.
Parameters
uri The uri of the content to set. If the uri is invalid, the content is not modified. An empty uri removes the content.
Referenced by create().
void Background::updated (BackgroundPtr) signal
Emitted when any value is changed by one of the setters.
Referenced by create().
The documentation for this class was generated from the following file:
Background.h