Tide: ScreenLock Class Reference
ScreenLock Class Reference
Allow wall lock preventing unwanted streams from opening and making Web Interface view-only.
#include <ScreenLock.h>
Signals
void lockChanged (bool locked)
Emitted when the state of the lock changes.
void streamListChanged ()
Emitted when the list of stream changes.
void modified (ScreenLockPtr lock)
Emitted when the lock changes.
void streamAccepted (QString uri)
Emitted when a single stream is to be opened (accepted by user).
void streamRejected (QString uri)
Emitted when a single stream is to be closed (rejected by user).
Public Member Functions
Q_INVOKABLE void lock ()
Lock the screen.
Q_INVOKABLE void unlock ()
Unlock the screen.
bool isLocked () const
Check the state of the lock.
Q_INVOKABLE void acceptStream (QString uri)
Accept the specified stream.
Q_INVOKABLE void rejectStream (QString uri)
Reject the specified stream.
void requestStreamAcceptance (QString uri)
Request a new stream acceptance.
void cancelStreamAcceptance (QString uri)
Cancel acceptance of the specified stream.
QStringList getPendingStreams () const
Get the list of registered streams.
Static Public Member Functions
static ScreenLockPtr create ()
Create a shared ScreenLock object.
Properties
bool locked
QStringList streamList
Friends
class boost::serialization::access
Detailed Description
Allow wall lock preventing unwanted streams from opening and making Web Interface view-only.
Definition at line 52 of file ScreenLock.h.
Member Function Documentation
Q_INVOKABLE void ScreenLock::acceptStream (QString uri)
Accept the specified stream.
Referenced by create().
void ScreenLock::cancelStreamAcceptance (QString uri)
Cancel acceptance of the specified stream.
Referenced by create().
static ScreenLockPtr ScreenLock::create () inline static
Create a shared ScreenLock object.
Definition at line 63 of file ScreenLock.h.
References acceptStream(), cancelStreamAcceptance(), getPendingStreams(), isLocked(), lock(), lockChanged(), modified(), rejectStream(), requestStreamAcceptance(), streamAccepted(), streamListChanged(), streamRejected(), and unlock().
Q_INVOKABLE void ScreenLock::lock ()
Lock the screen.
Notify about incoming streams and disallow Web Interface to controll the wall
Referenced by create().
void ScreenLock::lockChanged (bool locked) signal
Emitted when the state of the lock changes.
Referenced by create().
void ScreenLock::modified (ScreenLockPtr lock) signal
Emitted when the lock changes.
Referenced by create().
Q_INVOKABLE void ScreenLock::rejectStream (QString uri)
Reject the specified stream.
Referenced by create().
void ScreenLock::requestStreamAcceptance (QString uri)
Request a new stream acceptance.
Referenced by create().
void ScreenLock::streamAccepted (QString uri) signal
Emitted when a single stream is to be opened (accepted by user).
Referenced by create().
void ScreenLock::streamListChanged () signal
Emitted when the list of stream changes.
Referenced by create().
void ScreenLock::streamRejected (QString uri) signal
Emitted when a single stream is to be closed (rejected by user).
Referenced by create().
Q_INVOKABLE void ScreenLock::unlock ()
Unlock the screen.
Open pending streams and allow wall control from Web Interface
Referenced by create().
The documentation for this class was generated from the following file:
ScreenLock.h