Tide: DataSource Class Reference
DataSource Class Reference abstract
Base interface for shared data sources.
#include <DataSource.h>
Public Member Functions
virtual bool isDynamic () const
virtual void update (const Content &content)
Update the state of the data source.
virtual ImagePtr getTileImage (uint tileId, deflect::View view) const =0
Get a tile image by its id for a given view.
virtual QRect getTileRect (uint tileId) const =0
virtual QSize getTilesArea (uint lod, uint channel) const =0
virtual Indices computeVisibleSet (const QRectF &visibleTilesArea, uint lod, uint channel) const =0
virtual uint getMaxLod () const =0
virtual uint getPreviewTileId () const
virtual void allowNextFrame ()
Allow advancing to the next frame (synchronization / flow control).
virtual void synchronizeFrameAdvance (WallToWallChannel &channel)
Synchronize the advance to the next frame of the data.
Public Attributes
ContentSynchronizers synchronizers
The synchronizers linked to this shared data source.
Detailed Description
Base interface for shared data sources.
The DataProvider expects derived classes to always be constructible (no-throw constructor) and the public functions to behave correctly even if the source is unavailable for some reason (file access problem, etc...).
Definition at line 53 of file DataSource.h.
Member Function Documentation
virtual void DataSource::allowNextFrame () inline virtual
Allow advancing to the next frame (synchronization / flow control).
Reimplemented in PixelStreamUpdater, and MovieUpdater.
Definition at line 85 of file DataSource.h.
virtual Indices DataSource::computeVisibleSet (const QRectF & visibleTilesArea, uint lod, uint channel) const pure virtual
Returns
the indices of the tiles which are visible in the given area.
Implemented in PixelStreamUpdater, MovieUpdater, PDFTiler, ImageSource, and LodTiler.
Referenced by update().
virtual uint DataSource::getMaxLod () const pure virtual
Returns
the max LOD level (top of pyramid, lowest resolution).
Implemented in PixelStreamUpdater, MovieUpdater, ImageSource, and LodTiler.
Referenced by update().
virtual uint DataSource::getPreviewTileId () const inline virtual
Returns
the index of the tile to use for a preview.
Reimplemented in PDFTiler, and ImagePyramidDataSource.
Definition at line 83 of file DataSource.h.
virtual ImagePtr DataSource::getTileImage (uint tileId, deflect::View view) const pure virtual
Get a tile image by its id for a given view.
Called asynchronously but not concurrently. threadsafe. Implementations can return nullptr or throw an exception on error.
Implemented in PixelStreamUpdater, MovieUpdater, SVGTiler, and CachedDataSource.
Referenced by update().
virtual QRect DataSource::getTileRect (uint tileId) const pure virtual
Returns
the coordinates of a tile.
Implemented in PixelStreamUpdater, MovieUpdater, PDFTiler, ImageSource, ImagePyramidDataSource, and LodTiler.
Referenced by update().
virtual QSize DataSource::getTilesArea (uint lod, uint channel) const pure virtual
Returns
the image size for the requested lod and channel.
Implemented in PixelStreamUpdater, MovieUpdater, ImageSource, and LodTiler.
Referenced by update().
virtual bool DataSource::isDynamic () const inline virtual
Returns
true if the data source produces dynamic contents.
Reimplemented in PixelStreamUpdater, and MovieUpdater.
Definition at line 59 of file DataSource.h.
virtual void DataSource::synchronizeFrameAdvance (WallToWallChannel & channel) inline virtual
Synchronize the advance to the next frame of the data.
Reimplemented in PixelStreamUpdater, and MovieUpdater.
Definition at line 87 of file DataSource.h.
virtual void DataSource::update (const Content & content) inline virtual
Update the state of the data source.
Reimplemented in MovieUpdater, and PDFTiler.
Definition at line 61 of file DataSource.h.
References computeVisibleSet(), getMaxLod(), getTileImage(), getTileRect(), and getTilesArea().
Member Data Documentation
ContentSynchronizers DataSource::synchronizers
The synchronizers linked to this shared data source.
Definition at line 93 of file DataSource.h.
The documentation for this class was generated from the following file:
DataSource.h