Tide: ContentSynchronizer Class Reference
ContentSynchronizer Class Reference abstract
Interface for synchronizing QML content rendering.
#include <ContentSynchronizer.h>
Public Slots
virtual void onSwapReady (TilePtr tile)=0
Called when a tile is ready to swap.
void onRequestNextFrame (TilePtr tile)
Called when a tile has to be updated, re-emits requestTileUpdate.
void setZoomContextVisible (const bool zoomContextVisible)
Set by the Qml ZoomContext element.
Signals
void tilesAreasChanged ()
Notifier for the tiles areas property.
void statisticsChanged ()
Notifier for the statistics property.
void zoomContextVisibleChanged ()
Notifier for the zoomContextVisible property.
void addTile (TilePtr tile, uint zOrder)
Notify the window to add a tile.
void removeTile (uint tileId)
Notify the window to remove a tile.
void updateTile (uint tileId, QRect coordinates)
Notify to update a tile's coordinates.
void requestTileUpdate (TilePtr tile, deflect::View view)
Request an update of a specific tile.
void zoomContextTileChanged (bool visible)
Notify that the zoom context tile has changed and must be recreated.
void lodChanged (uint lod)
Notify that the level of detail has changed.
Public Member Functions
ContentSynchronizer ()=default
Constructor.
virtual ~ContentSynchronizer ()=default
Virtual destructor.
virtual void update (const Window &window, const QRectF &visibleArea)=0
Update the Content.
virtual void updateTiles ()=0
Update the tiles.
virtual void swapTiles ()=0
Swap the image before rendering (useful only for synchronized contents).
virtual bool canSwapTiles () const =0
Q_INVOKABLE QSize getTilesArea (const uint lod) const
virtual QString getStatistics () const =0
Get statistics about this Content.
bool getZoomContextVisible () const
Check if the zoom context tile is visible in Qml.
virtual const DataSource & getDataSource () const =0
Get the data source.
virtual TilePtr createZoomContextTile () const
virtual deflect::View getView () const
Get the view for this synchronizer.
virtual bool hasVisibleTiles () const =0
virtual uint getLod () const
virtual uint getLodCount () const
Properties
QString statistics
bool zoomContextVisible
uint lod
uint lodCount
Detailed Description
Interface for synchronizing QML content rendering.
ContentSynchronizer informs the QML engine when new frames are ready and swaps them synchronously.
Definition at line 53 of file ContentSynchronizer.h.
Member Function Documentation
void ContentSynchronizer::addTile (TilePtr tile, uint zOrder) signal
Notify the window to add a tile.
Referenced by setZoomContextVisible().
virtual bool ContentSynchronizer::canSwapTiles () const pure virtual
Returns
true if tiles are ready to be swapped.
Implemented in TiledSynchronizer, and BasicSynchronizer.
virtual TilePtr ContentSynchronizer::createZoomContextTile () const inline virtual
Returns
a new tile for the zoom context, or nullptr if unsupported.
Reimplemented in BasicSynchronizer, and LodSynchronizer.
Definition at line 110 of file ContentSynchronizer.h.
virtual const DataSource& ContentSynchronizer::getDataSource () const pure virtual
Get the data source.
Implemented in PixelStreamSynchronizer.
Referenced by getZoomContextVisible().
virtual uint ContentSynchronizer::getLod () const inline virtual
Returns
the current level of detail.
Reimplemented in LodSynchronizer.
Definition at line 117 of file ContentSynchronizer.h.
virtual uint ContentSynchronizer::getLodCount () const inline virtual
Returns
the number of level of detail.
Reimplemented in LodSynchronizer.
Definition at line 119 of file ContentSynchronizer.h.
References onSwapReady().
Referenced by getTilesArea().
virtual QString ContentSynchronizer::getStatistics () const pure virtual
Get statistics about this Content.
Implemented in MovieSynchronizer, PixelStreamSynchronizer, BasicSynchronizer, LodSynchronizer, and PDFSynchronizer.
Referenced by getTilesArea().
Q_INVOKABLE QSize ContentSynchronizer::getTilesArea (const uint lod) const inline
Returns
the total area covered by the tiles for a given LOD.
Note
has to be a method + notifier instead of Q_PROPERTY because there is no support for QList<QSize> in Qml.
Definition at line 94 of file ContentSynchronizer.h.
References getLodCount(), and getStatistics().
virtual deflect::View ContentSynchronizer::getView () const inline virtual
Get the view for this synchronizer.
Reimplemented in BasicSynchronizer, MovieSynchronizer, and PixelStreamSynchronizer.
Definition at line 112 of file ContentSynchronizer.h.
References hasVisibleTiles().
Referenced by onRequestNextFrame().
bool ContentSynchronizer::getZoomContextVisible () const inline
Check if the zoom context tile is visible in Qml.
Definition at line 105 of file ContentSynchronizer.h.
References getDataSource().
virtual bool ContentSynchronizer::hasVisibleTiles () const pure virtual
Returns
true if at least one tile is visible for this synchronizer.
Implemented in TiledSynchronizer, and BasicSynchronizer.
Referenced by getView().
void ContentSynchronizer::lodChanged (uint lod) signal
Notify that the level of detail has changed.
Referenced by setZoomContextVisible().
void ContentSynchronizer::onRequestNextFrame (TilePtr tile) inline slot
Called when a tile has to be updated, re-emits requestTileUpdate.
Definition at line 129 of file ContentSynchronizer.h.
References getView(), and requestTileUpdate().
virtual void ContentSynchronizer::onSwapReady (TilePtr tile) pure virtual slot
Called when a tile is ready to swap.
Specfific implementation can choose to swap the tile immediately or delay the swap until a later synchronization point.
Implemented in BasicSynchronizer, and TiledSynchronizer.
Referenced by getLodCount().
void ContentSynchronizer::removeTile (uint tileId) signal
Notify the window to remove a tile.
Referenced by setZoomContextVisible().
void ContentSynchronizer::requestTileUpdate (TilePtr tile, deflect::View view) signal
Request an update of a specific tile.
Referenced by onRequestNextFrame(), and setZoomContextVisible().
void ContentSynchronizer::setZoomContextVisible (const bool zoomContextVisible) inline slot
Set by the Qml ZoomContext element.
Definition at line 135 of file ContentSynchronizer.h.
References addTile(), lodChanged(), removeTile(), requestTileUpdate(), statisticsChanged(), tilesAreasChanged(), updateTile(), zoomContextTileChanged(), and zoomContextVisibleChanged().
void ContentSynchronizer::statisticsChanged () signal
Notifier for the statistics property.
Referenced by setZoomContextVisible().
virtual void ContentSynchronizer::swapTiles () pure virtual
Swap the image before rendering (useful only for synchronized contents).
Called only when canSwapTiles returns true on all processes.
Implemented in TiledSynchronizer, MovieSynchronizer, PixelStreamSynchronizer, and BasicSynchronizer.
void ContentSynchronizer::tilesAreasChanged () signal
Notifier for the tiles areas property.
See also
getTilesArea()
Referenced by setZoomContextVisible().
virtual void ContentSynchronizer::update (const Window & window, const QRectF & visibleArea) pure virtual
Update the Content.
Implemented in MovieSynchronizer, PixelStreamSynchronizer, PDFSynchronizer, BasicSynchronizer, and LodSynchronizer.
void ContentSynchronizer::updateTile (uint tileId, QRect coordinates) signal
Notify to update a tile's coordinates.
Referenced by setZoomContextVisible().
virtual void ContentSynchronizer::updateTiles () pure virtual
Update the tiles.
Call addTile, updateTile and zoomContextTileChanged only in this method.
Implemented in TiledSynchronizer, BasicSynchronizer, and LodSynchronizer.
void ContentSynchronizer::zoomContextTileChanged (bool visible) signal
Notify that the zoom context tile has changed and must be recreated.
Referenced by setZoomContextVisible().
void ContentSynchronizer::zoomContextVisibleChanged () signal
Notifier for the zoomContextVisible property.
Referenced by setZoomContextVisible().
The documentation for this class was generated from the following file:
ContentSynchronizer.h