Tide: json Namespace Reference
json Namespace Reference
Json helper functions.
Functions
QJsonObject parse (const std::string &data)
Parse a json document.
QJsonObject read (const QString &filename)
Parse a file to an object.
void write (const QJsonObject &object, const QString &filename)
Write an object to a file.
std::string dump (const QJsonArray &array)
Serialize a json array.
std::string dump (const QJsonObject &object)
Serialize a json object.
QByteArray pack (const QJsonObject &object)
Pack a json object to Qt's binary format.
QJsonObject unpack (const QByteArray &binaryData)
Unpack a json object in Qt's binary format.
template<typename T >
QJsonArray serialize (const std::vector< T > &collection)
Serialize a vector of objects to a JSON array.
template<typename SerializableT >
std::string dump (const SerializableT &object)
template<typename SerializableT >
QByteArray pack (const SerializableT &object)
template<typename DeserializableT >
DeserializableT create (const QJsonObject &object)
template<typename T >
void deserialize (const QJsonValue &value, std::vector< T > &result)
Deserialize a vector of objects from a JSON array.
template<typename DeserializableT >
bool deserialize (const std::string &json, DeserializableT &object)
Deserialize an object from a JSON text representation.
Helpers for QUuid (strip '{}' in JSON form).
QString url_encode (const QUuid &uuid)
QUuid url_decode (const QString &uuid)
Serialize custom enum types as JSON value.
QJsonValue serialize (SwapSync result)
QJsonValue serialize (deflect::View result)
Get a value as a specific type.
void deserialize (const QJsonValue &value, bool &result)
void deserialize (const QJsonValue &value, int &result)
void deserialize (const QJsonValue &value, uint &result)
void deserialize (const QJsonValue &value, ushort &result)
void deserialize (const QJsonValue &value, double &result)
void deserialize (const QJsonValue &value, QString &result)
void deserialize (const QJsonValue &value, SwapSync &result)
void deserialize (const QJsonValue &value, deflect::View &result)
JSON serialization of objects.
QJsonArray serialize (const QSize &size)
QJsonObject serializeAsObject (const QSize &size)
QJsonObject serialize (const Background &background)
QJsonObject serialize (const Options &options)
QJsonObject serialize (const Configuration &config)
QJsonObject serialize (const Process &process)
QJsonObject serialize (const Screen &screen)
QJsonObject serialize (const SurfaceConfig &surface)
JSON deserialization of objects.
bool deserialize (const QJsonValue &value, QSize &size)
bool deserialize (const QJsonArray &array, QSize &size)
bool deserialize (const QJsonObject &object, QSize &size)
bool deserialize (const QJsonObject &object, Background &background)
bool deserialize (const QJsonObject &object, Options &options)
bool deserialize (const QJsonObject &object, Configuration &config)
bool deserialize (const QJsonObject &object, Process &process)
bool deserialize (const QJsonObject &object, Screen &screen)
bool deserialize (const QJsonObject &object, SurfaceConfig &surface)
JSON serialization of objects for the REST interface.
QJsonObject serialize (ContentWindowPtr window, const DisplayGroup &group)
QJsonObject serialize (const DisplayGroup &group)
QJsonObject serialize (const Surface &surface)
QJsonArray serialize (const Scene &scene)
QJsonObject serialize (const LoggingUtility &logger)
QJsonObject serializeForRest (const Configuration &config)
Detailed Description
Json helper functions.
JSON templated helper functions.
Must be inluded after all (de)serialize() definitions.
Function Documentation
template<typename DeserializableT > DeserializableT json::create (const QJsonObject & object)
Returns
deserializable object parsed from a JSON object.
Definition at line 95 of file core/json/templates.h.
Referenced by pack().
template<typename T > void json::deserialize (const QJsonValue & value, std::vector< T > & result)
Deserialize a vector of objects from a JSON array.
Definition at line 82 of file core/json/templates.h.
template<typename DeserializableT > bool json::deserialize (const std::string & json, DeserializableT & object)
Deserialize an object from a JSON text representation.
Definition at line 104 of file core/json/templates.h.
References parse().
template<typename SerializableT > std::string json::dump (const SerializableT & object)
Returns
json text representation of a serializable object.
Definition at line 64 of file core/json/templates.h.
References dump().
std::string json::dump (const QJsonArray & array)
Serialize a json array.
Parameters
array json array to serialize.
Returns
json string.
Referenced by dump().
std::string json::dump (const QJsonObject & object)
Serialize a json object.
Parameters
object json object to serialize.
Returns
json string.
template<typename SerializableT > QByteArray json::pack (const SerializableT & object)
Returns
binary json representation of a serializable object.
Definition at line 71 of file core/json/templates.h.
References create(), and pack().
QByteArray json::pack (const QJsonObject & object)
Pack a json object to Qt's binary format.
Parameters
object json object to pack.
Returns
binaray data.
Referenced by pack().
QJsonObject json::parse (const std::string & data)
Parse a json document.
Parameters
data json document to parse.
Returns
json object, empty on error.
Referenced by deserialize().
QJsonObject json::read (const QString & filename)
Parse a file to an object.
Parameters
filename of a json file to parse.
Returns
json object.
Exceptions
std::runtime_error on failure.
template<typename T > QJsonArray json::serialize (const std::vector< T > & collection)
Serialize a vector of objects to a JSON array.
Definition at line 54 of file core/json/templates.h.
DeserializableT json::unpack (const QByteArray & binaryData)
Unpack a json object in Qt's binary format.
Deserialize an object from a binary JSON representation.
Parameters
binaryData json data to parse.
Returns
json object, empty on error.
Definition at line 111 of file core/json/templates.h.
void json::write (const QJsonObject & object, const QString & filename)
Write an object to a file.
Parameters
object json object to write.
filename to write.
Exceptions
std::runtime_error on failure.