Tide: geometry Namespace Reference
geometry Namespace Reference
Set of geometry functions.
Functions
template<typename Source , typename Target >
QSizeF getAdjustedSize (const Source &source, const Target &target)
Get the size of a surface scaled to fit inside another one.
template<typename Source , typename Target >
QSizeF getExpandedSize (const Source &source, const Target &target)
Get the size of a surface scaled to fit around another one.
template<typename Source , typename Target >
QRectF adjustAndCenter (const Source &source, const Target &target)
Adjust a surface to exactly fit inside another one, preserving aspect ratio.
QRectF resizeAroundPosition (const QRectF &rect, const QPointF &position, const QSizeF &size)
Resize a rectangle around a point of interest.
QRectF scaleAroundCenter (const QRectF &rect, const qreal factor)
Resize a rectangle around its center.
QSizeF constrain (const QSizeF &size, const QSizeF &min, const QSizeF &max)
Constrain a size between min and max values.
Detailed Description
Set of geometry functions.
Function Documentation
template<typename Source , typename Target > QRectF geometry::adjustAndCenter (const Source & source, const Target & target)
Adjust a surface to exactly fit inside another one, preserving aspect ratio.
Parameters
source the source surface
target the destination surface
Returns
the adjusted rectangle
Definition at line 83 of file geometry.h.
References constrain(), getAdjustedSize(), resizeAroundPosition(), and scaleAroundCenter().
QSizeF geometry::constrain (const QSizeF & size, const QSizeF & min, const QSizeF & max)
Constrain a size between min and max values.
Parameters
size the size to constrain
min the minimum size (ignored if not valid)
max the maximum size (ignored if not valid)
Returns
the size comprised between min and max
Referenced by adjustAndCenter().
template<typename Source , typename Target > QSizeF geometry::getAdjustedSize (const Source & source, const Target & target) inline
Get the size of a surface scaled to fit inside another one.
Parameters
source the source size
target the target size
Returns
the adjusted size
Definition at line 57 of file geometry.h.
Referenced by adjustAndCenter().
template<typename Source , typename Target > QSizeF geometry::getExpandedSize (const Source & source, const Target & target) inline
Get the size of a surface scaled to fit around another one.
Parameters
source the source size
target the target size
Returns
the adjusted size
Definition at line 70 of file geometry.h.
QRectF geometry::resizeAroundPosition (const QRectF & rect, const QPointF & position, const QSizeF & size)
Resize a rectangle around a point of interest.
Parameters
rect the rectangle to resize
position the point of interest to resize around
size the new absolute size to resize to
Returns
the resized rectangle
Referenced by adjustAndCenter().
QRectF geometry::scaleAroundCenter (const QRectF & rect, const qreal factor)
Resize a rectangle around its center.
Parameters
rect the rectangle to resize.
factor the resize factor to apply.
Returns
the resized rectangle.
Referenced by adjustAndCenter().