Tide: PixelStreamContent Class Reference
PixelStreamContent Class Reference
Signals
void notify (deflect::Event event)
Emitted when an Event occured.
Signals inherited from Content
void modified ()
Emitted by any Content subclass when its state has been modified.
void titleChanged (QString title)
void interactionPolicyChanged ()
void captureInteractionChanged ()
void dimensionsChanged ()
Public Member Functions
PixelStreamContent (const QString &uri, bool keyboard=true)
Constructor.
CONTENT_TYPE getType () const override
Get the content type.
bool readMetadata () override
Content method overload, not used for PixelStreams.
bool hasEventReceivers () const
Does this content already have registered EventReceiver(s)
void incrementEventReceiverCount ()
Register to receive events on this content.
Interaction getInteractionPolicy () const final
virtual void parseData (QByteArray data)
Parse data received from the deflect::Stream.
Public Member Functions inherited from Content
Content (const QString &uri)
Constructor.
const QString & getURI () const
Get the content URI.
virtual QString getTitle () const
Get the title of the content.
QSize getDimensions () const
Get the dimensions.
int width () const
Get the width.
int height () const
Get the height.
QSize getMinDimensions () const
QSize getPreferredDimensions () const
virtual QSize getMaxDimensions () const
void setDimensions (const QSize &dimensions)
Set the dimensions.
qreal getAspectRatio () const
Get the aspect ratio.
virtual bool hasFixedAspectRatio () const
virtual bool canBeZoomed () const
const QRectF & getZoomRect () const
Get the zoom rectangle in normalized coordinates, [0,0,1,1] default.
void setZoomRect (const QRectF &zoomRect)
Set the zoom rectangle in normalized coordinates.
Q_INVOKABLE void resetZoom ()
Resets the zoom to [0,0,1,1].
ContentActionsModel * getActions ()
Get the actions from QML.
virtual QString getQmlControls () const
Get content-specific qml controls file (default: empty).
KeyboardState * getKeyboardState ()
Get the keyboard state from QML.
void setSizeHints (const deflect::SizeHints &sizeHints)
Set optional size hints to constrain resize/scale and 1:1 size.
bool getCaptureInteraction () const
void setCaptureInteraction (bool enable)
Tell the content to capture interaction (only for Policy::AUTO).
Protected Member Functions
PixelStreamContent (const bool keyboard=true)
Protected Member Functions inherited from Content
template<class Archive >
void serialize (Archive &ar, const unsigned int)
Serialize for sending to Wall applications.
template<class Archive >
void serialize_members_xml (Archive &ar, const unsigned int version)
Serialize for saving to an xml file.
void serialize_for_xml (boost::archive::xml_iarchive &ar, const unsigned int version)
Loading from xml.
void serialize_for_xml (boost::archive::xml_oarchive &ar, const unsigned int version)
Saving to xml.
void _init ()
Friends
class boost::serialization::access
Additional Inherited Members
Public Types inherited from Content
enum Interaction { AUTO, ON, OFF }
The different types of interaction.
Static Public Member Functions inherited from Content
static void setMaxScale (qreal value)
Set the maximum factor for zoom and resize; value times content size.
static qreal getMaxScale ()
Protected Attributes inherited from Content
QString _uri
QSize _size
QRectF _zoomRect
ContentActionsModel _actions
KeyboardState _keyboardState
deflect::SizeHints _sizeHints
bool _captureInteraction
Static Protected Attributes inherited from Content
static qreal _maxScale
Properties inherited from Content
QString title
QSize size
qreal aspectRatio
bool hasFixedAspectRatio
QRectF zoomRect
ContentActionsModel actions
QString qmlControls
KeyboardState keyboard
Interaction interactionPolicy
bool captureInteraction
Detailed Description
Definition at line 49 of file PixelStreamContent.h.
Constructor & Destructor Documentation
PixelStreamContent::PixelStreamContent (const QString & uri, bool keyboard = true) explicit
Constructor.
Parameters
uri The unique stream identifier.
keyboard Show the keyboard action.
Referenced by parseData().
Member Function Documentation
Interaction PixelStreamContent::getInteractionPolicy () const final virtual
Returns
ON when hasEventReceivers() is true, otherwise OFF.
Reimplemented from Content.
void PixelStreamContent::incrementEventReceiverCount ()
Register to receive events on this content.
void PixelStreamContent::notify (deflect::Event event) signal
Emitted when an Event occured.
Referenced by parseData().
virtual void PixelStreamContent::parseData (QByteArray data) inline virtual
Parse data received from the deflect::Stream.
Reimplemented in WebbrowserContent.
Definition at line 80 of file PixelStreamContent.h.
References notify(), and PixelStreamContent().
bool PixelStreamContent::readMetadata () override virtual
Content method overload, not used for PixelStreams.
Returns
always returns true
Implements Content.
The documentation for this class was generated from the following file:
PixelStreamContent.h