Tide: ContentWindowController Class Reference
ContentWindowController Class Reference
Controller for moving and resizing windows.
#include <ContentWindowController.h>
Public Types
enum Coordinates { STANDARD, FOCUSED, FULLSCREEN, AUTO }
The set of window coordinates that the controller acts upon.
Public Member Functions
ContentWindowController (ContentWindow &contentWindow, const DisplayGroup &displayGroup, Coordinates target=Coordinates::AUTO)
Create a controller for a window.
Q_INVOKABLE void resize (QSizeF size, WindowPoint fixedPoint=TOP_LEFT)
Resize the window.
Q_INVOKABLE void resizeRelative (const QPointF &delta)
Resize the window relative to the current active window border.
Q_INVOKABLE void scale (const QPointF &center, double pixelDelta)
Scale the window by the given pixel delta (around the given center).
void adjustSize (const SizeState state)
Adjust the window coordinates to match the desired state.
Q_INVOKABLE void adjustSizeOneToOne ()
Adjust the window coordinates to match the Content dimensions.
Q_INVOKABLE void toogleFullscreenMaxSize ()
Toggle between SIZE_FULLSCREEN and SIZE_FULLSCREEN_MAX.
Q_INVOKABLE void moveTo (const QPointF &position, WindowPoint handle=TOP_LEFT)
Move the window to the desired position.
void moveCenterTo (const QPointF &position)
Move the center of the window to the desired position.
Q_INVOKABLE void moveBy (const QPointF &delta)
Move the window by the given delta.
QSizeF getMinSize () const
QSizeF getMaxSize () const
void constrainSize (QSizeF &windowSize) const
Constrain the given size between getMinSize() and getMaxSize().
QSizeF getMinSizeAspectRatioCorrect () const
Detailed Description
Controller for moving and resizing windows.
Definition at line 67 of file ContentWindowController.h.
Constructor & Destructor Documentation
ContentWindowController::ContentWindowController (ContentWindow & contentWindow, const DisplayGroup & displayGroup, Coordinates target = Coordinates::AUTO)
Create a controller for a window.
Parameters
contentWindow the target window
displayGroup the display group to which the window belongs
target the set of coordinates to modify (default: AUTO)
Member Function Documentation
void ContentWindowController::adjustSize (const SizeState state)
Adjust the window coordinates to match the desired state.
Referenced by adjustSizeOneToOne().
Q_INVOKABLE void ContentWindowController::adjustSizeOneToOne () inline
Adjust the window coordinates to match the Content dimensions.
Definition at line 107 of file ContentWindowController.h.
References adjustSize(), moveTo(), and toogleFullscreenMaxSize().
void ContentWindowController::constrainSize (QSizeF & windowSize) const
Constrain the given size between getMinSize() and getMaxSize().
Referenced by moveCenterTo().
QSizeF ContentWindowController::getMaxSize () const
Returns
the maximum size of the window, considering max size of content, wall size and current content zoom.
Referenced by moveCenterTo().
QSizeF ContentWindowController::getMinSize () const
Returns
the minimum size of the window, 5% of wall size or 300px.
Referenced by moveCenterTo().
QSizeF ContentWindowController::getMinSizeAspectRatioCorrect () const
Returns
the minimum size of the window respecting its aspect ratio.
Referenced by moveCenterTo().
Q_INVOKABLE void ContentWindowController::moveBy (const QPointF & delta)
Move the window by the given delta.
Referenced by moveCenterTo().
void ContentWindowController::moveCenterTo (const QPointF & position) inline
Move the center of the window to the desired position.
Definition at line 117 of file ContentWindowController.h.
References constrainSize(), getMaxSize(), getMinSize(), getMinSizeAspectRatioCorrect(), moveBy(), and moveTo().
Q_INVOKABLE void ContentWindowController::moveTo (const QPointF & position, WindowPoint handle = TOP_LEFT)
Move the window to the desired position.
Referenced by adjustSizeOneToOne(), and moveCenterTo().
Q_INVOKABLE void ContentWindowController::resize (QSizeF size, WindowPoint fixedPoint = TOP_LEFT)
Resize the window.
Q_INVOKABLE void ContentWindowController::scale (const QPointF & center, double pixelDelta)
Scale the window by the given pixel delta (around the given center).
Q_INVOKABLE void ContentWindowController::toogleFullscreenMaxSize ()
Toggle between SIZE_FULLSCREEN and SIZE_FULLSCREEN_MAX.
Referenced by adjustSizeOneToOne().
The documentation for this class was generated from the following file:
ContentWindowController.h