Brion: brion::PluginInitData Class Reference
brion::PluginInitData Class Reference
Basic plugin init data for Brion plugin classes.
#include <pluginInitData.h>
Public Member Functions
PluginInitData (const URI &uri, const int accessMode=MODE_READ)
Create a PluginInitData object given a URI and access mode.
const URI & getURI () const
int getAccessMode () const
Protected Attributes
URI _uri
int _accessMode
Detailed Description
Basic plugin init data for Brion plugin classes.
SpikeReportInitData and CompartmentReportInitData classes extend this class to initialize the plugins through the factory.
With the help of the PluginInitData class, the plugins can do the plugin initialization in their constructor.
Version
1.4
Definition at line 36 of file pluginInitData.h.
Constructor & Destructor Documentation
brion::PluginInitData::PluginInitData (const URI & uri, const int accessMode = MODE_READ) inline explicit
Create a PluginInitData object given a URI and access mode.
Parameters
uri URI to plugin. The report type is deduced from here.
accessMode the brion::AccessMode bitmask
Version
1.4
Definition at line 47 of file pluginInitData.h.
Member Function Documentation
int brion::PluginInitData::getAccessMode () const inline
Returns
Returns the access mode.
Version
1.4
Definition at line 60 of file pluginInitData.h.
const URI& brion::PluginInitData::getURI () const inline
Returns
the URI.
Version
1.4
Definition at line 54 of file pluginInitData.h.
Referenced by brion::CompartmentReportPlugin::getIndex(), brion::MorphologyPlugin::getPerimeters(), and brion::SpikeReportPlugin::write().
The documentation for this class was generated from the following file:
pluginInitData.h