Brion: brion::CompartmentReportPlugin Class Reference
brion::CompartmentReportPlugin Class Reference abstract
Base interface for compartment report readers and writers.
#include <compartmentReportPlugin.h>
Public Types
typedef CompartmentReportPlugin InterfaceT
typedef CompartmentReportInitData InitDataT
Public Member Functions
size_t getIndex (const uint32_t gid) const
Abstract interface
virtual double getStartTime () const =0
virtual double getEndTime () const =0
virtual double getTimestep () const =0
virtual const std::string & getDataUnit () const =0
virtual const std::string & getTimeUnit () const =0
virtual size_t getCellCount () const
virtual const GIDSet & getGIDs () const =0
virtual const SectionOffsets & getOffsets () const =0
Get the current mapping of each section of each neuron in each simulation frame buffer.
virtual size_t getNumCompartments (size_t index) const =0
Get the number of compartments for the given neuron.
virtual const CompartmentCounts & getCompartmentCounts () const =0
Get the number of compartments for each section of each neuron provided by the GID set via updateMapping().
virtual size_t getFrameSize () const =0
virtual size_t getFrameCount () const =0
virtual floatsPtr loadFrame (double timestamp) const =0
Load report values at the given time stamp.
virtual Frames loadFrames (double start, double end) const =0
Load all frames inside a given time window.
virtual floatsPtr loadNeuron (uint32_t gid BRION_UNUSED) const
virtual void updateMapping (const GIDSet &gids)=0
Update compartment mapping wrt the given GIDs.
virtual void setBufferSize (size_t size)
Set the size of the stream buffer for loaded frames.
virtual void clearBuffer ()
Clears all buffered frames to free memory.
virtual size_t getBufferSize () const
virtual void writeHeader (double startTime, double endTime, double timestep, const std::string &dunit, const std::string &tunit)=0
Write the header information of this report.
virtual bool writeCompartments (uint32_t gid, const uint16_ts &counts)=0
Write the compartment counts for each section for one cell.
virtual bool writeFrame (uint32_t gid, const float *values, size_t size, double timestamp)=0
virtual bool writeFrame (const GIDSet &gid, const float *values, const size_ts &sizes, double timestamp)=0
virtual bool flush ()=0
Flush data to output.
virtual bool erase ()
Remove all data of the report from storage.
Detailed Description
Base interface for compartment report readers and writers.
The following example creates a new report, initializes and registers it:
class MyReport : CompartmentReportPlugin
{
    MyReport( const CompartmentReportInitData& pluginInitData );
    static bool handles( const CompartmentReportInitData& pluginInitData );
    ...
};
...
// in the .cpp file
namespace
{
    lunchbox::PluginRegisterer< MyReport > registerer;
}
Version
1.4
Definition at line 101 of file compartmentReportPlugin.h.
Member Function Documentation
clearBuffer()
virtual void brion::CompartmentReportPlugin::clearBuffer () inline virtual
Clears all buffered frames to free memory.
Version
1.0
Definition at line 168 of file compartmentReportPlugin.h.
erase()
virtual bool brion::CompartmentReportPlugin::erase () inline virtual
Remove all data of the report from storage.
May not be implemented by all backends, such as file-based reports.
Returns
true if data was removed.
Version
1.0
Definition at line 195 of file compartmentReportPlugin.h.
flush()
virtual bool brion::CompartmentReportPlugin::flush () pure virtual
Flush data to output.
Returns
true on success.
Version
1.0
getBufferSize()
virtual size_t brion::CompartmentReportPlugin::getBufferSize () const inline virtual
Returns
the number of the simulation frame buffers.
Version
1.0
Definition at line 170 of file compartmentReportPlugin.h.
getCellCount()
virtual size_t brion::CompartmentReportPlugin::getCellCount () const inline virtual
Returns
the number of considered cells. Maybe much faster than getGIDs().size()
Version
3.0
Definition at line 130 of file compartmentReportPlugin.h.
References getGIDs().
getCompartmentCounts()
virtual const CompartmentCounts& brion::CompartmentReportPlugin::getCompartmentCounts () const pure virtual
Get the number of compartments for each section of each neuron provided by the GID set via updateMapping().
The neuron index is derived from the order in the GID set provided by updateMapping().
Returns
the compartment counts for each section for each neuron
Version
1.0
getDataUnit()
virtual const std::string& brion::CompartmentReportPlugin::getDataUnit () const pure virtual
Returns
the data unit of the report.
Version
1.0
getEndTime()
virtual double brion::CompartmentReportPlugin::getEndTime () const pure virtual
Returns
the current end time of the report.
Version
1.0
getFrameCount()
virtual size_t brion::CompartmentReportPlugin::getFrameCount () const pure virtual
Returns
the total frame count in the report.
Version
2.1
getFrameSize()
virtual size_t brion::CompartmentReportPlugin::getFrameSize () const pure virtual
Returns
the number of values of a loaded report frame.
Version
1.0
getGIDs()
virtual const GIDSet& brion::CompartmentReportPlugin::getGIDs () const pure virtual
Returns
the current considered GIDs.
Version
1.0
Referenced by getCellCount(), and getIndex().
getIndex()
size_t brion::CompartmentReportPlugin::getIndex (const uint32_t gid) const inline
Returns
the index of the given gid.
Version
1.0
Exceptions
std::runtime_error if the gid is not mapped
Definition at line 199 of file compartmentReportPlugin.h.
References getGIDs().
getNumCompartments()
virtual size_t brion::CompartmentReportPlugin::getNumCompartments (size_t index) const pure virtual
Get the number of compartments for the given neuron.
The neuron index is derived from the order in the GID set provided by updateMapping().
Parameters
index neuron index per current GID set
Returns
number of compartments for the given neuron
Version
1.0
getOffsets()
virtual const SectionOffsets& brion::CompartmentReportPlugin::getOffsets () const pure virtual
Get the current mapping of each section of each neuron in each simulation frame buffer.
For instance, getOffsets()[1][15] retrieves the lookup index for the frame buffer for section 15 of neuron with index 1. The neuron index is derived from the order in the GID set provided by updateMapping().
Returns
the offset for each section for each neuron
Version
1.0
getStartTime()
virtual double brion::CompartmentReportPlugin::getStartTime () const pure virtual
Returns
the current start time of the report.
Version
1.0
getTimestep()
virtual double brion::CompartmentReportPlugin::getTimestep () const pure virtual
Returns
the sampling time interval of the report.
Version
1.0
getTimeUnit()
virtual const std::string& brion::CompartmentReportPlugin::getTimeUnit () const pure virtual
Returns
the time unit of the report.
Version
1.0
loadFrame()
virtual floatsPtr brion::CompartmentReportPlugin::loadFrame (double timestamp) const pure virtual
Load report values at the given time stamp.
Parameters
timestamp the time stamp of interest
Returns
the report values if found at timestamp, nullptr otherwise
Note
Until the completion of this operation, the report shouldn't be modified
Version
2.0
loadFrames()
virtual Frames brion::CompartmentReportPlugin::loadFrames (double start, double end) const pure virtual
Load all frames inside a given time window.
The result will be empty if the window is invalid or falls outside the report window.
Parameters
start close left side of the time interval
end open right side of time interval
Returns
a future with the frames overlapped by the time window [start, end) and the start timestamps of these frames.
Version
2.0
loadNeuron()
virtual floatsPtr brion::CompartmentReportPlugin::loadNeuron (uint32_t gid BRION_UNUSED) const inline virtual
See also
brion::CompartmentReport::loadNeuron
Definition at line 156 of file compartmentReportPlugin.h.
setBufferSize()
virtual void brion::CompartmentReportPlugin::setBufferSize (size_t size) inline virtual
Set the size of the stream buffer for loaded frames.
Configures the number of simulation frame buffers for stream readers. When the consumer is slower than the producer, the producer will block once these buffers are exhausted, otherwise the consumer will block on data availability. A minimum of 1 frame is buffered.
Parameters
size the new size of the frame buffer.
Version
1.0
Definition at line 165 of file compartmentReportPlugin.h.
updateMapping()
virtual void brion::CompartmentReportPlugin::updateMapping (const GIDSet & gids) pure virtual
Update compartment mapping wrt the given GIDs.
Must be called at least once before loading any data or accessing the mapping is no GIDs were not provided at construction time.
Allows to change the GIDs in an open report without throwing away the already opened data, i.e., avoiding the overhead of always creating a new compartment report object when the desired GID set changes. An empty gids set loads all data from the report.
Parameters
gids the neurons of interest, may be empty.
Version
1.0
writeCompartments()
virtual bool brion::CompartmentReportPlugin::writeCompartments (uint32_t gid, const uint16_ts & counts) pure virtual
Write the compartment counts for each section for one cell.
This should only be called after writeHeader().
Parameters
gid the GID of the cell
counts the number of compartments per section
Returns
false if saving was not successful, true otherwise
Version
1.0
writeFrame() [1/2]
virtual bool brion::CompartmentReportPlugin::writeFrame (uint32_t gid, const float * values, size_t size, double timestamp) pure virtual
writeFrame() [2/2]
virtual bool brion::CompartmentReportPlugin::writeFrame (const GIDSet & gid, const float * values, const size_ts & sizes, double timestamp) pure virtual
writeHeader()
virtual void brion::CompartmentReportPlugin::writeHeader (double startTime, double endTime, double timestep, const std::string & dunit, const std::string & tunit) pure virtual
Write the header information of this report.
Parameters
startTime the start time of the report
endTime the end time of the report
timestep the timestep between report frames
dunit the unit of the data, e.g. mV
tunit the unit of the time, e.g. ms
Exceptions
std::invalid_argument if any passed argument is invalid
Version
1.0
The documentation for this class was generated from the following file:
compartmentReportPlugin.h