Deflect: deflect::Stream Class Reference
deflect::Stream Class Reference
Stream visual data to a deflect::Server.
#include <Stream.h>
Public Member Functions
Stream (unsigned short port=defaultPortNumber)
Open a new connection to the Server using environment variables.
Stream (const std::string &id, const std::string &host, unsigned short port=defaultPortNumber)
Open a new connection to the Server.
virtual ~Stream ()
Destruct the Stream, closing the connection.
Public Member Functions inherited from deflect::Observer
Observer (unsigned short port=defaultPortNumber)
Open a new connection to the Server using environment variables.
Observer (const std::string &id, const std::string &host, unsigned short port=defaultPortNumber)
Open a new connection to the Server.
virtual ~Observer ()
Destruct the Observer, closing the connection.
bool isConnected () const
const std::string & getId () const
const std::string & getHost () const
bool registerForEvents (bool exclusive=false)
Register to receive Events.
bool isRegisteredForEvents () const
Is this observer registered to receive events.
int getDescriptor () const
Get the native descriptor for the data stream.
bool hasEvent () const
Check if a new Event is available.
Event getEvent ()
Get the next Event.
void setDisconnectedCallback (std::function< void()> callback)
Set a function to be be called just after the observer gets disconnected.
void sendSizeHints (const SizeHints &hints)
Send size hints to the stream server to indicate sizes that should be respected by resize operations on the server side.
bool sendData (const char *data, size_t count)
Send data to the Server.
Friends
class deflect::test::Application
Asynchronous send API
using Future = std::future< bool >
Future signaling success of asyncSend().
Future send (const ImageWrapper &image)
Send an image asynchronously.
Future finishFrame ()
Asynchronously notify that all the images for this frame have been sent.
Future sendAndFinish (const ImageWrapper &image)
Send an image and finish the frame asynchronously.
Future asyncSend (const ImageWrapper &image)
Additional Inherited Members
Static Public Attributes inherited from deflect::Observer
static const unsigned short defaultPortNumber
The default communication port.
Protected Member Functions inherited from deflect::Observer
Observer (const Observer &)=delete
const Observer & operator= (const Observer &)=delete
Observer (StreamPrivate *impl)
Protected Attributes inherited from deflect::Observer
std::unique_ptr< StreamPrivate > _impl
Detailed Description
Stream visual data to a deflect::Server.
A Stream can be subdivided into one or more images and eye passes. This allows to have different applications each responsible for sending one part of the global image.
The methods in this class are reentrant (all instances are independant) but are not thread-safe.
Definition at line 62 of file Stream.h.
Member Typedef Documentation
using deflect::Stream::Future = std::future<bool>
Future signaling success of asyncSend().
Version
1.5
Definition at line 109 of file Stream.h.
Constructor & Destructor Documentation
deflect::Stream::Stream (unsigned short port = defaultPortNumber) explicit
Open a new connection to the Server using environment variables.
DEFLECT_HOST The address of the target Server instance (required). DEFLECT_ID The identifier for the stream. If not provided, a random unique identifier will be used.
Parameters
port Port of the Server instance, default 1701.
Exceptions
std::runtime_error if DEFLECT_HOST was not provided or no connection to server could be established
Version
1.3
Referenced by asyncSend().
deflect::Stream::Stream (const std::string & id, const std::string & host, unsigned short port = defaultPortNumber)
Open a new connection to the Server.
The user can check if the connection was successfully established with isConnected().
Different Streams can contribute to a single window by using the same identifier. All the Streams which contribute to the same window should be created before any of them starts sending images.
Parameters
id The identifier for the stream. If left empty, the environment variable DEFLECT_ID will be used. If both values are empty, a random unique identifier will be used.
host The address of the target Server instance. It can be a hostname like "localhost" or an IP in string format like "192.168.1.83". If left empty, the environment variable DEFLECT_HOST will be used instead.
port Port of the Server instance, default 1701.
Exceptions
std::runtime_error if no host was provided or no connection to server could be established
Version
1.0
virtual deflect::Stream::~Stream () virtual
Destruct the Stream, closing the connection.
Version
1.0
Member Function Documentation
Future deflect::Stream::asyncSend (const ImageWrapper & image) inline
Deprecated:
Definition at line 160 of file Stream.h.
References sendAndFinish(), and Stream().
Future deflect::Stream::finishFrame ()
Asynchronously notify that all the images for this frame have been sent.
This method must be called everytime this Stream instance has finished sending its image(s) for the current frame. The receiver will display the images once all the senders which use the same identifier have finished a frame. This is only to be called once per frame, even for stereo rendering.
See also
send()
Version
1.6
Future deflect::Stream::send (const ImageWrapper & image)
Send an image asynchronously.
Parameters
image The image to send. Note that the image is not copied, so the referenced must remain valid until the send is finished.
Returns
true if the image data could be sent, false otherwise
Exceptions
std::invalid_argument if not RGBA and uncompressed
std::invalid_argument if invalid JPEG compression arguments
std::runtime_error if pending finishFrame() has not been completed
std::runtime_error if JPEG compression failed
Version
1.6
See also
finishFrame()
Future deflect::Stream::sendAndFinish (const ImageWrapper & image)
Send an image and finish the frame asynchronously.
The send (and the optional compression) and finishFrame() are executed in a different thread. The result of this operation can be obtained by the returned future object.
Parameters
image The image to send. Note that the image is not copied, so the referenced must remain valid until the send is finished
Returns
true if the image data could be sent, false otherwise.
Exceptions
std::invalid_argument if RGBA and uncompressed
std::invalid_argument if invalid JPEG compression arguments
std::runtime_error if pending finishFrame() has not been completed
std::runtime_error if JPEG compression failed
See also
send()
Version
1.6
Referenced by asyncSend().
The documentation for this class was generated from the following file:
Stream.h