var files =
[
    [ "api.h", "api_8h.html", "api_8h" ],
    [ "qt/api.h", "qt_2api_8h.html", "qt_2api_8h" ],
    [ "config.h", "config_8h_source.html", null ],
    [ "defines.h", "defines_8h.html", null ],
    [ "definesLinux.h", "defines_linux_8h_source.html", null ],
    [ "deflect.h", "deflect_8h_source.html", null ],
    [ "Event.h", "_event_8h_source.html", null ],
    [ "EventReceiver.h", "_event_receiver_8h_source.html", null ],
    [ "Frame.h", "_frame_8h_source.html", null ],
    [ "ImageWrapper.h", "_image_wrapper_8h_source.html", null ],
    [ "Observer.h", "_observer_8h_source.html", null ],
    [ "OffscreenQuickView.h", "_offscreen_quick_view_8h_source.html", null ],
    [ "QmlStreamer.h", "_qml_streamer_8h_source.html", null ],
    [ "qt.h", "qt_8h_source.html", null ],
    [ "QuickRenderer.h", "_quick_renderer_8h_source.html", null ],
    [ "Segment.h", "_segment_8h_source.html", null ],
    [ "SegmentDecoder.h", "_segment_decoder_8h_source.html", null ],
    [ "SegmentParameters.h", "_segment_parameters_8h_source.html", null ],
    [ "Server.h", "_server_8h_source.html", null ],
    [ "SizeHints.h", "_size_hints_8h_source.html", null ],
    [ "Stream.h", "_stream_8h_source.html", null ],
    [ "TouchInjector.h", "_touch_injector_8h_source.html", null ],
    [ "types.h", "types_8h_source.html", null ],
    [ "qt/version.h", "qt_2version_8h.html", "qt_2version_8h" ],
    [ "version.h", "version_8h.html", "version_8h" ]
];