DASH: dash::Context Class Reference
dash::Context Class Reference
The contextual view on the data.
#include <context.h>
Public Member Functions
Data visibility
void map (dash::NodePtr node, const Context &to)
Map the given node and all children from this context to the 'to' context.
void unmap (dash::NodePtr node)
Release all references of the node tree in this context.
void map (dash::AttributePtr attribute, const Context &to)
Map the given attribute from this context to the 'to' context.
void unmap (dash::AttributePtr attribute)
Release all references of the attribute in this context.
Versioning
Commit commit ()
Return the changes since the last commit.
void apply (const Commit &commit)
Apply a change set to this context.
Internal
detail::Context & getImpl ()
Context management
static Context & getMain (const int argc=0, char **argv=0)
Get the root context.
static Context & getCurrent ()
Get the current context.
Context ()
Create an auxiliary context.
~Context ()
Destroy the given context.
Context & setCurrent ()
Set the context for the current thread.
Detailed Description
The contextual view on the data.
The Context provides an isolated view on data. Each thread can have a different context and multiple threads may use the same context. Each Context provides one distributed memory view for all data stored in nodes and attributes.
Read and write access to Node and Attribute from multiple contexts is thread-safe. Access from multiple threads using the same context to a concrete Node or Attribute instance is not thread-safe. Writes are only visible to the current context. They are propagated to child contexts using Context::commit() and applied to a concrete child context using Context::sync(). The commit and sync operation are thread-safe with any operation in another context, but not thread-safe with operations on the same context.
Definition at line 49 of file context.h.
Constructor & Destructor Documentation
dash::Context::Context ()
Create an auxiliary context.
Does not change the current context. Note that there is always a main context usable by the application.
Version:
0.1
Definition at line 51 of file context.cpp.
Referenced by getMain().
dash::Context::~Context ()
Destroy the given context.
The context has not to be current in any thread anymore. DASH does not check this, destroying a current context has undefined behaviour.
Destroying the main context has to be done after all dash objects, including non-main contexts and all commits, have been released. Subsequent dash calls will cause re-initialization of the main context.
Version:
0.1
Definition at line 55 of file context.cpp.
Member Function Documentation
void dash::Context::apply (const Commit & commit)
Apply a change set to this context.
Not thread-safe with any other dash operation using this context, i.e., any other thread using this context should be idle.
Parameters:
commit the change list.
Version:
0.1
Definition at line 148 of file context.cpp.
References setCurrent().
Commit dash::Context::commit ()
Return the changes since the last commit.
Not thread-safe with any other dash operation using this context, i.e., any other thread using this context should be idle.
Returns:
the change list.
Version:
0.1
Definition at line 143 of file context.cpp.
Context & dash::Context::getCurrent () [static]
Get the current context.
If no current context is set, the main context will be made current and returned as a result.
Returns:
the current context.
Version:
0.1
Definition at line 101 of file context.cpp.
References getMain().
Referenced by setCurrent().
Context & dash::Context::getMain (const int argc = 0, char ** argv = 0) [static]
Get the root context.
Command line arguments are used only if this method is called before any other dash call. Otherwise, dash will initialize the main context with default values.
Parameters:
argc the command line argument count.
argv the command line argument values.
Returns:
the root context.
Version:
0.1
Definition at line 73 of file context.cpp.
References Context(), and dash::Version::getString().
Referenced by getCurrent().
void dash::Context::map (dash::NodePtr node, const Context & to)
Map the given node and all children from this context to the 'to' context.
Traverses the node tree and synchronizes the view from the this context to the 'to' context. The from context need to have no pending changes, that is, it should be fully committed. Not thread-safe with any other operation on this context.
Parameters:
node the tree to map.
to the context to make the node visible in.
Version:
0.1
Definition at line 115 of file context.cpp.
References setCurrent().
void dash::Context::map (dash::AttributePtr attribute, const Context & to)
Map the given attribute from this context to the 'to' context.
Synchronizes the view from this context to the 'to' context. This context need to have no pending changes, that is, it should be fully committed. Not thread-safe with any other operation on this context.
Parameters:
attribute the tree to map.
to the context to make the attribute visible in.
Version:
0.1
Definition at line 129 of file context.cpp.
References setCurrent().
Context & dash::Context::setCurrent ()
Set the context for the current thread.
One context may be current in multiple threads. Concurrent access to a single context is not thread-safe.
Returns:
the previous current context.
Version:
0.1
Definition at line 94 of file context.cpp.
References getCurrent().
Referenced by apply(), map(), and unmap().
void dash::Context::unmap (dash::NodePtr node)
Release all references of the node tree in this context.
Resets the view of this context. Used to release copies held by this context for all nodes and attributes of the given node tree. Accessing the node, or any of its children, after unmapping it results in undefined behaviour.
Parameters:
node the tree to unmap.
Version:
0.1
Definition at line 122 of file context.cpp.
References setCurrent().
void dash::Context::unmap (dash::AttributePtr attribute)
Release all references of the attribute in this context.
Resets the view of this context. Used to release copies held by this context for the attribute. Accessing the attribute, or any of its children, after unmapping it results in undefined behaviour.
Parameters:
attribute the tree to unmap.
Version:
0.1
Definition at line 136 of file context.cpp.
References setCurrent().
The documentation for this class was generated from the following files:
context.h
context.cpp