var annotated_dup =
[
    [ "brayns", null, [
      [ "obj", null, [
        [ "ExtendedOBJMaterial", "structbrayns_1_1obj_1_1_extended_o_b_j_material.html", "structbrayns_1_1obj_1_1_extended_o_b_j_material" ]
      ] ],
      [ "AbstractManipulator", "classbrayns_1_1_abstract_manipulator.html", "classbrayns_1_1_abstract_manipulator" ],
      [ "AbstractParameters", "classbrayns_1_1_abstract_parameters.html", "classbrayns_1_1_abstract_parameters" ],
      [ "AbstractRenderer", "classbrayns_1_1_abstract_renderer.html", "classbrayns_1_1_abstract_renderer" ],
      [ "AbstractSimulationHandler", "classbrayns_1_1_abstract_simulation_handler.html", "classbrayns_1_1_abstract_simulation_handler" ],
      [ "ActionInterface", "classbrayns_1_1_action_interface.html", "classbrayns_1_1_action_interface" ],
      [ "AnimationParameters", "classbrayns_1_1_animation_parameters.html", "classbrayns_1_1_animation_parameters" ],
      [ "ApplicationParameters", "classbrayns_1_1_application_parameters.html", "classbrayns_1_1_application_parameters" ],
      [ "BadParameter", "classbrayns_1_1_bad_parameter.html", "classbrayns_1_1_bad_parameter" ],
      [ "BaseObject", "classbrayns_1_1_base_object.html", "classbrayns_1_1_base_object" ],
      [ "BasicRenderer", "classbrayns_1_1_basic_renderer.html", "classbrayns_1_1_basic_renderer" ],
      [ "Brayns", "classbrayns_1_1_brayns.html", "classbrayns_1_1_brayns" ],
      [ "CADiffusionSimulationHandler", "classbrayns_1_1_c_a_diffusion_simulation_handler.html", "classbrayns_1_1_c_a_diffusion_simulation_handler" ],
      [ "Camera", "classbrayns_1_1_camera.html", "classbrayns_1_1_camera" ],
      [ "CircuitConfiguration", "structbrayns_1_1_circuit_configuration.html", "structbrayns_1_1_circuit_configuration" ],
      [ "Cone", "structbrayns_1_1_cone.html", "structbrayns_1_1_cone" ],
      [ "ConnectivityConfiguration", "structbrayns_1_1_connectivity_configuration.html", "structbrayns_1_1_connectivity_configuration" ],
      [ "Cylinder", "structbrayns_1_1_cylinder.html", "structbrayns_1_1_cylinder" ],
      [ "DirectionalLight", "classbrayns_1_1_directional_light.html", "classbrayns_1_1_directional_light" ],
      [ "Engine", "classbrayns_1_1_engine.html", "classbrayns_1_1_engine" ],
      [ "Exception", "classbrayns_1_1_exception.html", "classbrayns_1_1_exception" ],
      [ "ExtensionPlugin", "classbrayns_1_1_extension_plugin.html", "classbrayns_1_1_extension_plugin" ],
      [ "FlyingModeManipulator", "classbrayns_1_1_flying_mode_manipulator.html", "classbrayns_1_1_flying_mode_manipulator" ],
      [ "FrameBuffer", "classbrayns_1_1_frame_buffer.html", "classbrayns_1_1_frame_buffer" ],
      [ "GeometryParameters", "classbrayns_1_1_geometry_parameters.html", "classbrayns_1_1_geometry_parameters" ],
      [ "Histogram", "structbrayns_1_1_histogram.html", "structbrayns_1_1_histogram" ],
      [ "ImageManager", "classbrayns_1_1_image_manager.html", "classbrayns_1_1_image_manager" ],
      [ "InspectCenterManipulator", "classbrayns_1_1_inspect_center_manipulator.html", "classbrayns_1_1_inspect_center_manipulator" ],
      [ "KeyboardHandler", "classbrayns_1_1_keyboard_handler.html", "classbrayns_1_1_keyboard_handler" ],
      [ "Light", "classbrayns_1_1_light.html", "classbrayns_1_1_light" ],
      [ "Material", "classbrayns_1_1_material.html", "classbrayns_1_1_material" ],
      [ "MeshLoader", "classbrayns_1_1_mesh_loader.html", "classbrayns_1_1_mesh_loader" ],
      [ "MetaballsGenerator", "classbrayns_1_1_metaballs_generator.html", "classbrayns_1_1_metaballs_generator" ],
      [ "MolecularSystemReader", "classbrayns_1_1_molecular_system_reader.html", "classbrayns_1_1_molecular_system_reader" ],
      [ "MorphologyLayout", "structbrayns_1_1_morphology_layout.html", "structbrayns_1_1_morphology_layout" ],
      [ "OSPRayCamera", "classbrayns_1_1_o_s_p_ray_camera.html", "classbrayns_1_1_o_s_p_ray_camera" ],
      [ "OSPRayEngine", "classbrayns_1_1_o_s_p_ray_engine.html", "classbrayns_1_1_o_s_p_ray_engine" ],
      [ "OSPRayFrameBuffer", "classbrayns_1_1_o_s_p_ray_frame_buffer.html", "classbrayns_1_1_o_s_p_ray_frame_buffer" ],
      [ "OSPRayRenderer", "classbrayns_1_1_o_s_p_ray_renderer.html", "classbrayns_1_1_o_s_p_ray_renderer" ],
      [ "OSPRayScene", "classbrayns_1_1_o_s_p_ray_scene.html", "classbrayns_1_1_o_s_p_ray_scene" ],
      [ "ParametersManager", "classbrayns_1_1_parameters_manager.html", "classbrayns_1_1_parameters_manager" ],
      [ "ParticleRenderer", "classbrayns_1_1_particle_renderer.html", "classbrayns_1_1_particle_renderer" ],
      [ "PluginAPI", "classbrayns_1_1_plugin_a_p_i.html", "classbrayns_1_1_plugin_a_p_i" ],
      [ "PointLight", "classbrayns_1_1_point_light.html", "classbrayns_1_1_point_light" ],
      [ "Progress", "classbrayns_1_1_progress.html", "classbrayns_1_1_progress" ],
      [ "ProgressReporter", "classbrayns_1_1_progress_reporter.html", "classbrayns_1_1_progress_reporter" ],
      [ "ProteinLoader", "classbrayns_1_1_protein_loader.html", "classbrayns_1_1_protein_loader" ],
      [ "ProximityRenderer", "classbrayns_1_1_proximity_renderer.html", "classbrayns_1_1_proximity_renderer" ],
      [ "Renderer", "classbrayns_1_1_renderer.html", "classbrayns_1_1_renderer" ],
      [ "RenderingParameters", "classbrayns_1_1_rendering_parameters.html", "classbrayns_1_1_rendering_parameters" ],
      [ "RenderInput", "structbrayns_1_1_render_input.html", "structbrayns_1_1_render_input" ],
      [ "RenderOutput", "structbrayns_1_1_render_output.html", "structbrayns_1_1_render_output" ],
      [ "Scene", "classbrayns_1_1_scene.html", "classbrayns_1_1_scene" ],
      [ "SceneLoader", "classbrayns_1_1_scene_loader.html", "classbrayns_1_1_scene_loader" ],
      [ "SceneParameters", "classbrayns_1_1_scene_parameters.html", "classbrayns_1_1_scene_parameters" ],
      [ "ShortcutInformation", "structbrayns_1_1_shortcut_information.html", "structbrayns_1_1_shortcut_information" ],
      [ "SimulationRenderer", "classbrayns_1_1_simulation_renderer.html", "classbrayns_1_1_simulation_renderer" ],
      [ "SnapshotParams", "structbrayns_1_1_snapshot_params.html", "structbrayns_1_1_snapshot_params" ],
      [ "Sphere", "structbrayns_1_1_sphere.html", "structbrayns_1_1_sphere" ],
      [ "SpikeSimulationHandler", "classbrayns_1_1_spike_simulation_handler.html", "classbrayns_1_1_spike_simulation_handler" ],
      [ "Statistics", "classbrayns_1_1_statistics.html", "classbrayns_1_1_statistics" ],
      [ "StreamParameters", "classbrayns_1_1_stream_parameters.html", "classbrayns_1_1_stream_parameters" ],
      [ "Texture2D", "classbrayns_1_1_texture2_d.html", "classbrayns_1_1_texture2_d" ],
      [ "Timer", "classbrayns_1_1_timer.html", "classbrayns_1_1_timer" ],
      [ "TransferFunction", "classbrayns_1_1_transfer_function.html", "classbrayns_1_1_transfer_function" ],
      [ "TransferFunctionLoader", "classbrayns_1_1_transfer_function_loader.html", "classbrayns_1_1_transfer_function_loader" ],
      [ "TrianglesMesh", "structbrayns_1_1_triangles_mesh.html", "structbrayns_1_1_triangles_mesh" ],
      [ "Version", "classbrayns_1_1_version.html", "classbrayns_1_1_version" ],
      [ "VolumeHandler", "classbrayns_1_1_volume_handler.html", "classbrayns_1_1_volume_handler" ],
      [ "VolumeParameters", "classbrayns_1_1_volume_parameters.html", "classbrayns_1_1_volume_parameters" ],
      [ "XYZBLoader", "classbrayns_1_1_x_y_z_b_loader.html", "classbrayns_1_1_x_y_z_b_loader" ]
    ] ],
    [ "ospray", null, [
      [ "ClippedPerspectiveCamera", "structospray_1_1_clipped_perspective_camera.html", "structospray_1_1_clipped_perspective_camera" ],
      [ "ExtendedCones", "structospray_1_1_extended_cones.html", "structospray_1_1_extended_cones" ],
      [ "ExtendedCylinders", "structospray_1_1_extended_cylinders.html", "structospray_1_1_extended_cylinders" ],
      [ "ExtendedSpheres", "structospray_1_1_extended_spheres.html", "structospray_1_1_extended_spheres" ]
    ] ]
];