Livre: livre::MemoryUnit Class Reference
livre::MemoryUnit Class Reference abstract
The MemoryUnit class the base class for carrying memory information.
#include <MemoryUnit.h>
Public Member Functions
virtual void alloc (const uint32_t allocSizePerElement, const uint32_t dataSize)=0
Allocate memory.
virtual void release ()=0
Release memory.
template<class T >
const T * getData () const
template<class T >
T * getData ()
virtual uint32_t getMemSize () const =0
virtual uint32_t getAllocSize () const =0
Protected Member Functions
virtual const uint8_t * getData_ () const =0
virtual uint8_t * getData_ ()=0
Detailed Description
The MemoryUnit class the base class for carrying memory information.
Definition at line 34 of file MemoryUnit.h.
Member Function Documentation
virtual void livre::MemoryUnit::alloc (const uint32_t allocSizePerElement, const uint32_t dataSize) pure virtual
Allocate memory.
Parameters
allocSizePerElement Allocation size per element of the array.
dataSize Number of elements in the array.
Implemented in livre::AllocMemoryUnit, livre::ConstMemoryUnit, and livre::NoMemoryUnit.
virtual uint32_t livre::MemoryUnit::getAllocSize () const pure virtual
Returns
The allocated heap size.
Implemented in livre::AllocMemoryUnit, livre::ConstMemoryUnit, and livre::NoMemoryUnit.
template<class T > const T* livre::MemoryUnit::getData () const inline
Returns
The memory ptr in type T.
Definition at line 53 of file MemoryUnit.h.
References getData_().
template<class T > T* livre::MemoryUnit::getData () inline
Returns
The memory ptr in type T.
Definition at line 57 of file MemoryUnit.h.
References getData_().
virtual const uint8_t* livre::MemoryUnit::getData_ () const protected pure virtual
Returns
The unsigned char memory ptr to data
Implemented in livre::ConstMemoryUnit.
Referenced by getData().
virtual uint8_t* livre::MemoryUnit::getData_ () protected pure virtual
Returns
The unsigned char memory ptr to data
Implemented in livre::ConstMemoryUnit.
virtual uint32_t livre::MemoryUnit::getMemSize () const pure virtual
Returns
The size of the memory accessed.
Implemented in livre::AllocMemoryUnit, livre::ConstMemoryUnit, and livre::NoMemoryUnit.
The documentation for this class was generated from the following file:
MemoryUnit.h