Lunchbox: lunchbox::PerThread< T, D > Class Template Reference
lunchbox::PerThread< T, D > Class Template Reference
Implements thread-specific storage for C++ objects.
#include <perThread.h>
Public Member Functions
PerThread ()
Construct a new per-thread variable.
~PerThread ()
Destruct the per-thread variable.
PerThread< T, D > & operator= (const T *data)
Assign an object to the thread-local storage.
PerThread< T, D > & operator= (const PerThread< T, D > &rhs)
Assign an object from another thread-local storage.
T * get ()
const T * get () const
T * operator-> ()
Access the thread-local object.
const T * operator-> () const
Access the thread-local object.
T & operator* ()
const T & operator* () const
bool operator== (const PerThread &rhs) const
bool operator== (const T *rhs) const
bool operator!= (const T *rhs) const
bool operator! () const
bool isValid () const
Detailed Description
template<class T, void(*)(T *) D = &perThreadDelete< T >>
class lunchbox::PerThread< T, D >
Implements thread-specific storage for C++ objects.
The default destructor function deletes the object on thread exit.
Parameters
T the type of data to store in thread-local storage
D the destructor callback function.
Deprecated:
Use boost::thread_specific_ptr
Example:
/* Copyright (c) 2011-2014, Stefan Eilemann <eile@eyescale.ch>
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 2.1 as published
 * by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
#ifdef WARN_DEPRECATED
#  undef WARN_DEPRECATED
#endif
#include <pthread.h>
#include <test.h>
#include <lunchbox/atomic.h>
#include <lunchbox/perThread.h>
#include <lunchbox/sleep.h>
#include <lunchbox/rng.h>
#define NTHREADS 1024
lunchbox::a_int32_t _threads;
void destructor(size_t*) { --_threads; }
lunchbox::PerThread< size_t, &destructor > _tls1;
lunchbox::PerThread< size_t > _tls2;
lunchbox::PerThread< size_t, &destructor > _tls3;
class Thread : public lunchbox::Thread
{
public:
    virtual ~Thread() {}
    virtual void run()
        {
            ++_threads;
            lunchbox::RNG rng;
            size_t i = rng.get< size_t >();
            size_t* data = new size_t( i );
            _tls1 = data;
            _tls2 = data;
            _tls3 = _tls1;
            TEST( _tls1.get() == data );
            TEST( *_tls1 == i );
            TEST( _tls2.get() == data );
            TEST( *_tls2 == i );
            TEST( *_tls1 == *_tls2 );
            TEST( *_tls1 == *_tls3 );
            _tls3 = 0;
            TEST( _tls3 == 0 );
        }
};
int main(int argc, char **argv)
{
    TEST( lunchbox::init( argc, argv ));
    Thread threads[NTHREADS];
    TESTINFO( _threads == 0, _threads );
    for( size_t i=0; i<NTHREADS; ++i )
        TEST( threads[i].start( ));
    for( size_t i=0; i<NTHREADS; ++i )
        TEST( threads[i].join( ));
    lunchbox::sleep( 10 ); // ms, needed for tls exit handlers to run
    TESTINFO( _threads == 0, _threads );
    TEST( lunchbox::exit( ));
    return EXIT_SUCCESS;
}
Definition at line 46 of file perThread.h.
Constructor & Destructor Documentation
template<class T , void(*)(T *) D> lunchbox::PerThread< T, D >::PerThread ()
Construct a new per-thread variable.
Version
1.0
Definition at line 20 of file perThread.ipp.
template<class T , void(*)(T *) D> lunchbox::PerThread< T, D >::~PerThread ()
Destruct the per-thread variable.
Version
1.0
Definition at line 24 of file perThread.ipp.
Member Function Documentation
template<class T , void(*)(T *) D> T * lunchbox::PerThread< T, D >::get ()
Returns
the held object pointer.
Version
1.0
Definition at line 41 of file perThread.ipp.
Referenced by lunchbox::PerThread< T, D >::operator==().
template<class T , void(*)(T *) D> const T * lunchbox::PerThread< T, D >::get () const
Returns
the held object pointer.
Version
1.0
Definition at line 46 of file perThread.ipp.
template<class T , void(*)(T *) D> bool lunchbox::PerThread< T, D >::isValid () const
Returns
true if the thread-local storage holds a non-0 pointer.
Version
1.0
Definition at line 67 of file perThread.ipp.
template<class T , void(*)(T *) D> bool lunchbox::PerThread< T, D >::operator! () const
Returns
true if the thread-local storage holds a 0 pointer.
Version
1.0
Definition at line 62 of file perThread.ipp.
template<class T, void(*)(T *) D = &perThreadDelete< T >> bool lunchbox::PerThread< T, D >::operator!= (const T * rhs) const inline
Returns
true if the thread-local variable holds another object.
Version
1.0
Definition at line 92 of file perThread.h.
template<class T, void(*)(T *) D = &perThreadDelete< T >> T& lunchbox::PerThread< T, D >::operator* () inline
Returns
the held object reference.
Version
1.0
Definition at line 69 of file perThread.h.
References lunchbox::className().
template<class T, void(*)(T *) D = &perThreadDelete< T >> const T& lunchbox::PerThread< T, D >::operator* () const inline
Returns
the held object reference.
Version
1.0
Definition at line 72 of file perThread.h.
References lunchbox::className().
template<class T , void(*)(T *) D> T * lunchbox::PerThread< T, D >::operator-> ()
Access the thread-local object.
Version
1.0
Definition at line 51 of file perThread.ipp.
template<class T , void(*)(T *) D> const T * lunchbox::PerThread< T, D >::operator-> () const
Access the thread-local object.
Version
1.0
Definition at line 57 of file perThread.ipp.
template<class T , void(*)(T *) D> PerThread< T, D > & lunchbox::PerThread< T, D >::operator= (const T * data)
Assign an object to the thread-local storage.
Version
1.0
Definition at line 28 of file perThread.ipp.
template<class T , void(*)(T *) D> PerThread< T, D > & lunchbox::PerThread< T, D >::operator= (const PerThread< T, D > & rhs)
Assign an object from another thread-local storage.
Version
1.0
Definition at line 35 of file perThread.ipp.
References lunchbox::TLS::get().
template<class T, void(*)(T *) D = &perThreadDelete< T >> bool lunchbox::PerThread< T, D >::operator== (const PerThread< T, D > & rhs) const inline
Returns
true if the thread-local variables hold the same object.
Version
1.0
Definition at line 79 of file perThread.h.
References lunchbox::PerThread< T, D >::get().
template<class T, void(*)(T *) D = &perThreadDelete< T >> bool lunchbox::PerThread< T, D >::operator== (const T * rhs) const inline
Returns
true if the thread-local variable holds the same object.
Version
1.0
Definition at line 86 of file perThread.h.
The documentation for this class was generated from the following files:
perThread.h
perThread.ipp