Brayns: brayns::Engine Class Reference
brayns::Engine Class Reference abstract
Abstract implementation of the ray-tracing engine.
#include <Engine.h>
Public Member Functions
Engine (ParametersManager &parametersManager)
Engine constructor.
virtual EngineType name () const =0
virtual void commit ()
Commits changes to the engine.
void render ()
Renders the current scene and populates the frame buffer accordingly.
virtual void preRender ()
Executes engine specific pre-render operations.
virtual void postRender ()
Executes engine specific post-render operations.
Scene & getScene ()
Gets the scene.
auto getScenePtr ()
FrameBuffer & getFrameBuffer ()
Gets the frame buffer.
const Camera & getCamera () const
Gets the camera.
Camera & getCamera ()
Renderer & getRenderer ()
Gets the renderer.
void reshape (const Vector2ui &frameSize)
Reshapes the current frame buffers.
void initializeMaterials (MaterialsColorMap colorMap=MaterialsColorMap::none)
Initializes materials for the current scene.
virtual Vector2ui getSupportedFrameSize (const Vector2ui &size) const =0
Adapts the size of the frame buffer according to camera requirements.
virtual Vector2ui getMinimumFrameSize () const =0
virtual bool haveDeflectPixelOp () const
void setKeepRunning (bool keepRunning)
Keep continue to run the engine, aka the user did not request to stop rendering.
bool getKeepRunning () const
Statistics & getStatistics ()
bool continueRendering () const
virtual FrameBufferPtr createFrameBuffer (const Vector2ui &frameSize, FrameBufferFormat frameBufferFormat, bool accumulation) const =0
Factory method to create an engine-specific framebuffer.
virtual ScenePtr createScene (ParametersManager &parametersManager) const =0
virtual CameraPtr createCamera () const =0
Factory method to create an engine-specific camera.
virtual RendererPtr createRenderer (const AnimationParameters &animationParameters, const RenderingParameters &renderingParameters) const =0
auto & getParametersManager ()
Public Attributes
std::function< void()> triggerRender {[] {}}
Callback when a new frame shall be triggered.
Protected Member Functions
void _render (const RenderInput &renderInput, RenderOutput &renderOutput)
void _render ()
void _writeFrameToFile ()
Protected Attributes
ParametersManager & _parametersManager
ScenePtr _scene
CameraPtr _camera
RendererPtr _renderer
Vector2i _frameSize
FrameBufferPtr _frameBuffer
Statistics _statistics
bool _keepRunning {true}
Detailed Description
Abstract implementation of the ray-tracing engine.
What we call the ray-tracing engine is a 3rd party acceleration library, typically OSPRay, Optix or FireRays, that provides hardware acceleration. An engine holds a native implementation of a scene, a camera, a frame buffer and of one or several renderers according to the capatilities of the acceleration library.
Definition at line 38 of file Engine.h.
Constructor & Destructor Documentation
brayns::Engine::Engine (ParametersManager & parametersManager) explicit
Engine constructor.
Parameters
parametersManager holds all engine parameters (geometry, rendering, etc)
Member Function Documentation
virtual void brayns::Engine::commit () virtual
Commits changes to the engine.
This include scene, camera and renderer modifications
bool brayns::Engine::continueRendering () const
Returns
true if render() calls shall be continued, based on current accumulation settings.
See also
RenderingParameters::setMaxAccumFrames
Referenced by getKeepRunning().
virtual CameraPtr brayns::Engine::createCamera () const pure virtual
Factory method to create an engine-specific camera.
Referenced by getKeepRunning().
virtual FrameBufferPtr brayns::Engine::createFrameBuffer (const Vector2ui & frameSize, FrameBufferFormat frameBufferFormat, bool accumulation) const pure virtual
Factory method to create an engine-specific framebuffer.
Referenced by getKeepRunning().
bool brayns::Engine::getKeepRunning () const inline
Returns
true if the user wants to continue rendering, false otherwise.
Definition at line 120 of file Engine.h.
References continueRendering(), createCamera(), and createFrameBuffer().
virtual Vector2ui brayns::Engine::getMinimumFrameSize () const pure virtual
Returns
the minimum frame size in pixels supported by this engine.
virtual Vector2ui brayns::Engine::getSupportedFrameSize (const Vector2ui & size) const pure virtual
Adapts the size of the frame buffer according to camera requirements.
Typically, in case of 3D stereo vision, the frame buffer width has to be an even number. Can be overridden by the engine implementation for specific requirements.
Parameters
size New size of the frame buffer
Returns
Size that matches the camera requirements
virtual bool brayns::Engine::haveDeflectPixelOp () const inline virtual
Returns
true if for "--module deflect" the DeflectPixelOp was successfully loaded. Only supported for the OSPRay engine.
Definition at line 111 of file Engine.h.
void brayns::Engine::initializeMaterials (MaterialsColorMap colorMap = MaterialsColorMap::none)
Initializes materials for the current scene.
Parameters
colorMap Predefined color map
Referenced by getCamera().
virtual EngineType brayns::Engine::name () const pure virtual
Returns
the name of the engine
void brayns::Engine::reshape (const Vector2ui & frameSize)
Reshapes the current frame buffers.
Parameters
frameSize New size for the buffers
Referenced by getCamera().
Member Data Documentation
std::function<void()> brayns::Engine::triggerRender {[] {}}
Callback when a new frame shall be triggered.
Currently called by event plugins Deflect and Rockets.
Definition at line 91 of file Engine.h.
The documentation for this class was generated from the following file:
Engine.h