DASH: dash::Node Class Reference
dash::Node Class Reference
A node of a dash graph.
#include <node.h>
Public Member Functions
Node ()
Construct a new empty node.
Node (const Node &from)
Construct a shallow, parent-less copy.
virtual ~Node ()
Destruct this node.
Node & operator= (const Node &from)
Perform a shallow, parent-less assignment.
bool operator== (const Node &rhs) const
Check this Node on equality w/o traversing the children.
bool operator!= (const Node &rhs) const
Check this Node on inequality w/o traversing the children.
VisitorResult accept (Visitor &visitor)
Traverse this node tree using the given visitor.
VisitorResult accept (ConstVisitor &visitor) const
Traverse this const node tree using the given visitor.
Node hierarchy
void insert (NodePtr child)
Establish a relationship between the two nodes.
void erase (NodePtr child)
Break the relationship between the two nodes.
bool hasParents () const
size_t getNParents () const
NodePtr getParent (const size_t i)
const NodePtr getParent (const size_t i) const
ConstParentIterator parentsBegin () const
ConstParentIterator parentsEnd () const
ParentIterator parentsBegin ()
ParentIterator parentsEnd ()
size_t getNChildren () const
NodePtr getChild (const size_t i)
ConstNodePtr getChild (const size_t i) const
ConstChildIterator childrenBegin () const
ConstChildIterator childrenEnd () const
ChildIterator childrenBegin ()
ChildIterator childrenEnd ()
Attribute data storage
void insert (AttributePtr attribute)
Add an attribute to this node.
void erase (AttributePtr attribute)
Remove an attribute from this node.
size_t getNAttributes () const
AttributePtr getAttribute (const size_t i)
ConstAttributePtr getAttribute (const size_t i) const
ConstAttributeIterator attributesBegin () const
ConstAttributeIterator attributesEnd () const
AttributeIterator attributesBegin ()
AttributeIterator attributesEnd ()
Internal
detail::Node * getImpl ()
const detail::Node * getImpl () const
Public Types
typedef NodeVisitor< NodePtr,
AttributePtr > Visitor
Node tree visitor.
typedef NodeVisitor
< ConstNodePtr,
ConstAttributePtr > ConstVisitor
Const node tree visitor.
typedef detail::ParentIterator
< Node > ParentIterator
An iterator over the parent vector.
typedef detail::ParentIterator
< const Node > ConstParentIterator
A const iterator over the parent vector.
typedef detail::ChildIterator
< Node > ChildIterator
An iterator over the child vector.
typedef detail::ChildIterator
< const Node > ConstChildIterator
A const iterator over the child vector.
typedef
detail::AttributeIterator
< Node, Attribute > AttributeIterator
An iterator over the attribute vector.
typedef
detail::AttributeIterator
< const Node, const Attribute > ConstAttributeIterator
A const iterator over the attribute vector.
Detailed Description
A node of a dash graph.
Nodes form directed acyclic graphs (DAG) in dash. They hold one or more Attribute data items. All data access to a Node is thread-safe as long as it happens with different contexts. Modifying a Node is not visible to other contexts until a Commit is applied to the Context.
Nodes are by default only visible in the Context they are constructed in. They are made visible in other contexts using Context::map().
Definition at line 51 of file node.h.
Member Typedef Documentation
typedef detail::AttributeIterator< Node, Attribute > dash::Node::AttributeIterator
An iterator over the attribute vector.
Definition at line 71 of file node.h.
typedef detail::ChildIterator< Node > dash::Node::ChildIterator
An iterator over the child vector.
Definition at line 66 of file node.h.
typedef detail::AttributeIterator< const Node, const Attribute > dash::Node::ConstAttributeIterator
A const iterator over the attribute vector.
Definition at line 74 of file node.h.
typedef detail::ChildIterator< const Node > dash::Node::ConstChildIterator
A const iterator over the child vector.
Definition at line 68 of file node.h.
typedef detail::ParentIterator< const Node > dash::Node::ConstParentIterator
A const iterator over the parent vector.
Definition at line 63 of file node.h.
typedef detail::ParentIterator< Node > dash::Node::ParentIterator
An iterator over the parent vector.
Definition at line 61 of file node.h.
Constructor & Destructor Documentation
dash::Node::Node ()
Construct a new empty node.
Version:
0.1
Definition at line 33 of file node.cpp.
dash::Node::Node (const Node & from)
Construct a shallow, parent-less copy.
Version:
0.1
Definition at line 43 of file node.cpp.
dash::Node::~Node () virtual
Destruct this node.
Version:
0.1
Definition at line 53 of file node.cpp.
Member Function Documentation
VisitorResult dash::Node::accept (Visitor & visitor)
Traverse this node tree using the given visitor.
Returns:
the result of the last visit.
Version:
1.0
Definition at line 113 of file node.cpp.
VisitorResult dash::Node::accept (ConstVisitor & visitor) const
Traverse this const node tree using the given visitor.
Returns:
the result of the last visit.
Version:
1.0
Definition at line 118 of file node.cpp.
Node::ConstAttributeIterator dash::Node::attributesBegin () const
Returns:
iterator pointing to the first attribute.
Version:
0.1
Definition at line 235 of file node.cpp.
Node::AttributeIterator dash::Node::attributesBegin ()
Returns:
iterator pointing to the start of the attributes.
Version:
0.1
Definition at line 245 of file node.cpp.
Node::ConstAttributeIterator dash::Node::attributesEnd () const
Returns:
iterator pointing to the end of the attributes.
Version:
0.1
Definition at line 240 of file node.cpp.
References getNAttributes().
Node::AttributeIterator dash::Node::attributesEnd ()
Returns:
iterator pointing to the end of the attributes.
Version:
0.1
Definition at line 250 of file node.cpp.
References getNAttributes().
Node::ConstChildIterator dash::Node::childrenBegin () const
Returns:
an iterator pointing to the start of the children.
Version:
0.1
Definition at line 189 of file node.cpp.
Node::ChildIterator dash::Node::childrenBegin ()
Returns:
an iterator pointing to the start of the children.
Version:
0.1
Definition at line 199 of file node.cpp.
Node::ConstChildIterator dash::Node::childrenEnd () const
Returns:
an iterator pointing to the end of the children.
Version:
0.1
Definition at line 194 of file node.cpp.
References getNChildren().
Node::ChildIterator dash::Node::childrenEnd ()
Returns:
an iterator pointing to the end of the children.
Version:
0.1
Definition at line 204 of file node.cpp.
References getNChildren().
void dash::Node::erase (NodePtr child)
Break the relationship between the two nodes.
Version:
0.1
Definition at line 129 of file node.cpp.
void dash::Node::erase (AttributePtr attribute)
Remove an attribute from this node.
Version:
0.1
Definition at line 215 of file node.cpp.
AttributePtr dash::Node::getAttribute (const size_t i)
Returns:
the attribute at the given position.
Version:
0.1
Definition at line 225 of file node.cpp.
ConstAttributePtr dash::Node::getAttribute (const size_t i) const
Returns:
the const attribute at the given position.
Version:
0.1
Definition at line 230 of file node.cpp.
NodePtr dash::Node::getChild (const size_t i)
Returns:
the child at the given position.
Version:
0.1
Definition at line 179 of file node.cpp.
ConstNodePtr dash::Node::getChild (const size_t i) const
Returns:
the child at the given position.
Version:
0.1
Definition at line 184 of file node.cpp.
size_t dash::Node::getNAttributes () const
Returns:
the current number of attributes.
Version:
0.1
Definition at line 220 of file node.cpp.
Referenced by attributesEnd().
size_t dash::Node::getNChildren () const
Returns:
the current number of children.
Version:
0.1
Definition at line 174 of file node.cpp.
Referenced by childrenEnd().
size_t dash::Node::getNParents () const
Returns:
the current number of parents.
Version:
0.1
Definition at line 139 of file node.cpp.
Referenced by parentsEnd().
NodePtr dash::Node::getParent (const size_t i)
Returns:
the parent at the given position.
Version:
0.1
Definition at line 144 of file node.cpp.
const NodePtr dash::Node::getParent (const size_t i) const
Returns:
the parent at the given position.
Version:
0.1
Definition at line 149 of file node.cpp.
bool dash::Node::hasParents () const
Returns:
true of the node has parents, false otherwise.
Version:
0.1
Definition at line 134 of file node.cpp.
void dash::Node::insert (NodePtr child)
Establish a relationship between the two nodes.
Version:
0.1
Definition at line 124 of file node.cpp.
void dash::Node::insert (AttributePtr attribute)
Add an attribute to this node.
Version:
0.1
Definition at line 210 of file node.cpp.
bool dash::Node::operator!= (const Node & rhs) const inline
Check this Node on inequality w/o traversing the children.
Version:
0.1
Definition at line 90 of file node.h.
Node & dash::Node::operator= (const Node & from)
Perform a shallow, parent-less assignment.
Version:
0.1
Definition at line 59 of file node.cpp.
bool dash::Node::operator== (const Node & rhs) const
Check this Node on equality w/o traversing the children.
Version:
0.1
Definition at line 67 of file node.cpp.
Node::ConstParentIterator dash::Node::parentsBegin () const
Returns:
an iterator pointing to the start of the parents.
Version:
0.1
Definition at line 154 of file node.cpp.
Node::ParentIterator dash::Node::parentsBegin ()
Returns:
an iterator pointing to the start of the parents.
Version:
0.1
Definition at line 164 of file node.cpp.
Node::ConstParentIterator dash::Node::parentsEnd () const
Returns:
an iterator pointing to the end of the parents.
Version:
0.1
Definition at line 159 of file node.cpp.
References getNParents().
Node::ParentIterator dash::Node::parentsEnd ()
Returns:
an iterator pointing to the end of the parents.
Version:
0.1
Definition at line 169 of file node.cpp.
References getNParents().
The documentation for this class was generated from the following files:
node.h
node.cpp