set(MONSTEER_MATURITY "EP")
set(MONSTEER_DESCRIPTION "Interactive Supercomputing - Monitoring and Steering for NEST simulations")
set(MONSTEER_GIT_ROOT_URL "https://github.com/BlueBrain/Monsteer")
set(MONSTEER_PACKAGE_URL "")
set(MONSTEER_CI_URL "https://travis-ci.org/BlueBrain/Monsteer")
set(MONSTEER_CI_PNG "https://travis-ci.org/BlueBrain/Monsteer.png")
set(MONSTEER_ISSUES_URL "https://github.com/BlueBrain/Monsteer/issues")
