Tide: RestServer Class Reference
RestServer Class Reference
A non-blocking REST Server based on ZeroEQ for use in a Qt application.
#include <RestServer.h>
Public Member Functions
RestServer ()
Start a server with an OS-chosen port.
RestServer (int port)
Start a server on a defined port.
~RestServer ()=default
Stop the server.
int getPort () const
template<typename Obj >
bool handleGET (const std::string &endpoint, const Obj &object)
Expose a JSON-serializable object on an HTTP GET endpoint.
template<typename Obj >
bool handlePUT (const std::string &endpoint, Obj &object)
Subscribe a JSON-deserializable object on an HTTP PUT endpoint.
void block (zeroeq::http::Method method)
Block requests for specified method (other than from localhost).
void unblock (zeroeq::http::Method method)
Unblock requests for specified method.
Protected Member Functions
std::future< zeroeq::http::Response > respondTo (zeroeq::http::Request &request) const final
Detailed Description
A non-blocking REST Server based on ZeroEQ for use in a Qt application.
Definition at line 53 of file RestServer.h.
Constructor & Destructor Documentation
RestServer::RestServer ()
Start a server with an OS-chosen port.
Exceptions
std::runtime_error if a connection issue occured.
RestServer::RestServer (int port) explicit
Start a server on a defined port.
Parameters
port the TCP port to listen to.
Exceptions
std::runtime_error if the port is already in use or a connection issue occured.
RestServer::~RestServer () default
Stop the server.
Member Function Documentation
void RestServer::block (zeroeq::http::Method method)
Block requests for specified method (other than from localhost).
Server will return code 403 (FORBIDDEN).
Parameters
method the method which is to be blocked
Referenced by handlePUT().
int RestServer::getPort () const
Returns
the port of the server.
template<typename Obj > bool RestServer::handleGET (const std::string & endpoint, const Obj & object) inline
Expose a JSON-serializable object on an HTTP GET endpoint.
Parameters
endpoint for accessing the object.
object to expose.
Definition at line 83 of file RestServer.h.
template<typename Obj > bool RestServer::handlePUT (const std::string & endpoint, Obj & object) inline
Subscribe a JSON-deserializable object on an HTTP PUT endpoint.
Parameters
endpoint for modifying the object.
object to subscribe.
Definition at line 99 of file RestServer.h.
References block(), and unblock().
void RestServer::unblock (zeroeq::http::Method method)
Unblock requests for specified method.
Parameters
method the method which is to be unblocked
Referenced by handlePUT().
The documentation for this class was generated from the following file:
RestServer.h