set(TIDE_MATURITY "EP")
set(TIDE_DESCRIPTION "Tiled Interactive DisplayWall Environment")
set(TIDE_GIT_ROOT_URL "https://github.com/BlueBrain/Tide.git")
set(TIDE_PACKAGE_URL "")
set(TIDE_CI_URL "https://travis-ci.org/BlueBrain/Tide")
set(TIDE_CI_PNG "https://travis-ci.org/BlueBrain/Tide.png")
set(TIDE_ISSUES_URL "https://github.com/BlueBrain/Tide/issues")
