var files =
[
    [ "AbstractCommandHandler.h", "_abstract_command_handler_8h_source.html", null ],
    [ "api.h", "api_8h.html", "api_8h" ],
    [ "Command.h", "_command_8h_source.html", null ],
    [ "CommandHandler.h", "_command_handler_8h_source.html", null ],
    [ "CommandType.h", "_command_type_8h_source.html", null ],
    [ "config.h", "config_8h_source.html", null ],
    [ "defines.h", "defines_8h.html", null ],
    [ "definesLinux.h", "defines_linux_8h_source.html", null ],
    [ "deflect.h", "deflect_8h_source.html", null ],
    [ "Event.h", "_event_8h_source.html", null ],
    [ "EventReceiver.h", "_event_receiver_8h_source.html", null ],
    [ "ImageJpegCompressor.h", "_image_jpeg_compressor_8h_source.html", null ],
    [ "ImageJpegDecompressor.h", "_image_jpeg_decompressor_8h_source.html", null ],
    [ "ImageSegmenter.h", "_image_segmenter_8h_source.html", null ],
    [ "ImageWrapper.h", "_image_wrapper_8h_source.html", null ],
    [ "MessageHeader.h", "_message_header_8h_source.html", null ],
    [ "MetaTypeRegistration.h", "_meta_type_registration_8h_source.html", null ],
    [ "NetworkListener.h", "_network_listener_8h_source.html", null ],
    [ "NetworkListenerThread.h", "_network_listener_thread_8h_source.html", null ],
    [ "NetworkListenerWorker.h", "_network_listener_worker_8h_source.html", null ],
    [ "NetworkProtocol.h", "_network_protocol_8h_source.html", null ],
    [ "PixelStreamBuffer.h", "_pixel_stream_buffer_8h_source.html", null ],
    [ "PixelStreamDispatcher.h", "_pixel_stream_dispatcher_8h_source.html", null ],
    [ "PixelStreamFrame.h", "_pixel_stream_frame_8h_source.html", null ],
    [ "PixelStreamSegment.h", "_pixel_stream_segment_8h_source.html", null ],
    [ "PixelStreamSegmentDecoder.h", "_pixel_stream_segment_decoder_8h_source.html", null ],
    [ "PixelStreamSegmentParameters.h", "_pixel_stream_segment_parameters_8h_source.html", null ],
    [ "Socket.h", "_socket_8h_source.html", null ],
    [ "Stream.h", "_stream_8h_source.html", null ],
    [ "types.h", "types_8h_source.html", null ],
    [ "version.h", "version_8h.html", "version_8h" ]
];