var files =
[
    [ "api.h", "api_8h.html", "api_8h" ],
    [ "qt/api.h", "qt_2api_8h.html", "qt_2api_8h" ],
    [ "config.h", "config_8h_source.html", null ],
    [ "defines.h", "defines_8h_source.html", null ],
    [ "qt/jenkins/04/workspace/oss.Deflect.documentation/build_type/Debug/platform/cscsviz-vm/build/include/deflect/defines.h", "qt_2jenkins_204_2workspace_2oss_8_deflect_8documentation_2build__type_2_debug_2platform_2cscsviz365a1cef2c2799e4e6919b269fda391d_source.html", null ],
    [ "deflect.h", "deflect_8h_source.html", null ],
    [ "Event.h", "_event_8h_source.html", null ],
    [ "EventReceiver.h", "_event_receiver_8h_source.html", null ],
    [ "Frame.h", "_frame_8h_source.html", null ],
    [ "FrameDispatcher.h", "_frame_dispatcher_8h_source.html", null ],
    [ "ImageWrapper.h", "_image_wrapper_8h_source.html", null ],
    [ "MTQueue.h", "_m_t_queue_8h_source.html", null ],
    [ "QmlStreamer.h", "_qml_streamer_8h_source.html", null ],
    [ "qt.h", "qt_8h_source.html", null ],
    [ "Segment.h", "_segment_8h_source.html", null ],
    [ "SegmentDecoder.h", "_segment_decoder_8h_source.html", null ],
    [ "SegmentParameters.h", "_segment_parameters_8h_source.html", null ],
    [ "Server.h", "_server_8h_source.html", null ],
    [ "SizeHints.h", "_size_hints_8h_source.html", null ],
    [ "Stream.h", "_stream_8h_source.html", null ],
    [ "types.h", "types_8h_source.html", null ],
    [ "qt/version.h", "qt_2version_8h.html", "qt_2version_8h" ],
    [ "version.h", "version_8h.html", "version_8h" ]
];