var annotated_dup =
[
    [ "boost", null, [
      [ "program_options", null, [
        [ "fixed_tokens_typed_value", "classboost_1_1program__options_1_1fixed__tokens__typed__value.html", "classboost_1_1program__options_1_1fixed__tokens__typed__value" ]
      ] ]
    ] ],
    [ "brayns", null, [
      [ "AbstractManipulator", "classbrayns_1_1_abstract_manipulator.html", "classbrayns_1_1_abstract_manipulator" ],
      [ "AbstractParameters", "classbrayns_1_1_abstract_parameters.html", "classbrayns_1_1_abstract_parameters" ],
      [ "AbstractSimulationHandler", "classbrayns_1_1_abstract_simulation_handler.html", "classbrayns_1_1_abstract_simulation_handler" ],
      [ "AbstractTask", "classbrayns_1_1_abstract_task.html", "classbrayns_1_1_abstract_task" ],
      [ "ActionInterface", "classbrayns_1_1_action_interface.html", "classbrayns_1_1_action_interface" ],
      [ "AddModelFromBlobTask", "classbrayns_1_1_add_model_from_blob_task.html", "classbrayns_1_1_add_model_from_blob_task" ],
      [ "AddModelTask", "classbrayns_1_1_add_model_task.html", "classbrayns_1_1_add_model_task" ],
      [ "AmbientLight", "classbrayns_1_1_ambient_light.html", "classbrayns_1_1_ambient_light" ],
      [ "AnimationParameters", "classbrayns_1_1_animation_parameters.html", "classbrayns_1_1_animation_parameters" ],
      [ "ApplicationParameters", "classbrayns_1_1_application_parameters.html", "classbrayns_1_1_application_parameters" ],
      [ "BaseObject", "classbrayns_1_1_base_object.html", "classbrayns_1_1_base_object" ],
      [ "BinaryParam", "structbrayns_1_1_binary_param.html", "structbrayns_1_1_binary_param" ],
      [ "Blob", "structbrayns_1_1_blob.html", "structbrayns_1_1_blob" ],
      [ "Box", "classbrayns_1_1_box.html", "classbrayns_1_1_box" ],
      [ "Brayns", "classbrayns_1_1_brayns.html", "classbrayns_1_1_brayns" ],
      [ "BrickedVolume", "classbrayns_1_1_bricked_volume.html", "classbrayns_1_1_bricked_volume" ],
      [ "Camera", "classbrayns_1_1_camera.html", "classbrayns_1_1_camera" ],
      [ "Chunk", "structbrayns_1_1_chunk.html", "structbrayns_1_1_chunk" ],
      [ "ClipPlane", "classbrayns_1_1_clip_plane.html", "classbrayns_1_1_clip_plane" ],
      [ "ColorMap", "structbrayns_1_1_color_map.html", "structbrayns_1_1_color_map" ],
      [ "DeferredTask", "classbrayns_1_1_deferred_task.html", "classbrayns_1_1_deferred_task" ],
      [ "DirectionalLight", "classbrayns_1_1_directional_light.html", "classbrayns_1_1_directional_light" ],
      [ "Engine", "classbrayns_1_1_engine.html", "classbrayns_1_1_engine" ],
      [ "ExtensionPlugin", "classbrayns_1_1_extension_plugin.html", "classbrayns_1_1_extension_plugin" ],
      [ "FlyingModeManipulator", "classbrayns_1_1_flying_mode_manipulator.html", "classbrayns_1_1_flying_mode_manipulator" ],
      [ "FrameBuffer", "classbrayns_1_1_frame_buffer.html", "classbrayns_1_1_frame_buffer" ],
      [ "GeometryParameters", "classbrayns_1_1_geometry_parameters.html", "classbrayns_1_1_geometry_parameters" ],
      [ "ImageManager", "classbrayns_1_1_image_manager.html", "classbrayns_1_1_image_manager" ],
      [ "InspectCenterManipulator", "classbrayns_1_1_inspect_center_manipulator.html", "classbrayns_1_1_inspect_center_manipulator" ],
      [ "KeyboardHandler", "classbrayns_1_1_keyboard_handler.html", "classbrayns_1_1_keyboard_handler" ],
      [ "Light", "classbrayns_1_1_light.html", "classbrayns_1_1_light" ],
      [ "LightManager", "classbrayns_1_1_light_manager.html", "classbrayns_1_1_light_manager" ],
      [ "Loader", "classbrayns_1_1_loader.html", "classbrayns_1_1_loader" ],
      [ "LoaderInfo", "structbrayns_1_1_loader_info.html", "structbrayns_1_1_loader_info" ],
      [ "LoaderProgress", "classbrayns_1_1_loader_progress.html", "classbrayns_1_1_loader_progress" ],
      [ "LoaderRegistry", "classbrayns_1_1_loader_registry.html", "classbrayns_1_1_loader_registry" ],
      [ "LoadModelFunctor", "classbrayns_1_1_load_model_functor.html", "classbrayns_1_1_load_model_functor" ],
      [ "Material", "classbrayns_1_1_material.html", "classbrayns_1_1_material" ],
      [ "MHDVolumeLoader", "classbrayns_1_1_m_h_d_volume_loader.html", "classbrayns_1_1_m_h_d_volume_loader" ],
      [ "Model", "classbrayns_1_1_model.html", "classbrayns_1_1_model" ],
      [ "ModelDescriptor", "classbrayns_1_1_model_descriptor.html", "classbrayns_1_1_model_descriptor" ],
      [ "ModelInstance", "classbrayns_1_1_model_instance.html", "classbrayns_1_1_model_instance" ],
      [ "ModelParams", "classbrayns_1_1_model_params.html", "classbrayns_1_1_model_params" ],
      [ "ParametersManager", "classbrayns_1_1_parameters_manager.html", "classbrayns_1_1_parameters_manager" ],
      [ "PluginAPI", "classbrayns_1_1_plugin_a_p_i.html", "classbrayns_1_1_plugin_a_p_i" ],
      [ "Progress", "classbrayns_1_1_progress.html", "classbrayns_1_1_progress" ],
      [ "Property", "structbrayns_1_1_property.html", "structbrayns_1_1_property" ],
      [ "PropertyMap", "classbrayns_1_1_property_map.html", "classbrayns_1_1_property_map" ],
      [ "PropertyObject", "classbrayns_1_1_property_object.html", "classbrayns_1_1_property_object" ],
      [ "ProteinLoader", "classbrayns_1_1_protein_loader.html", "classbrayns_1_1_protein_loader" ],
      [ "QuadLight", "classbrayns_1_1_quad_light.html", "classbrayns_1_1_quad_light" ],
      [ "RawVolumeLoader", "classbrayns_1_1_raw_volume_loader.html", "classbrayns_1_1_raw_volume_loader" ],
      [ "Renderer", "classbrayns_1_1_renderer.html", "classbrayns_1_1_renderer" ],
      [ "RenderingParameters", "classbrayns_1_1_rendering_parameters.html", "classbrayns_1_1_rendering_parameters" ],
      [ "RenderInput", "structbrayns_1_1_render_input.html", "structbrayns_1_1_render_input" ],
      [ "RenderOutput", "structbrayns_1_1_render_output.html", "structbrayns_1_1_render_output" ],
      [ "RpcDescription", "structbrayns_1_1_rpc_description.html", "structbrayns_1_1_rpc_description" ],
      [ "RpcParameterDescription", "structbrayns_1_1_rpc_parameter_description.html", "structbrayns_1_1_rpc_parameter_description" ],
      [ "Scene", "classbrayns_1_1_scene.html", "classbrayns_1_1_scene" ],
      [ "SDFBezier", "structbrayns_1_1_s_d_f_bezier.html", "structbrayns_1_1_s_d_f_bezier" ],
      [ "SDFGeometry", "structbrayns_1_1_s_d_f_geometry.html", "structbrayns_1_1_s_d_f_geometry" ],
      [ "SDFGeometryData", "structbrayns_1_1_s_d_f_geometry_data.html", "structbrayns_1_1_s_d_f_geometry_data" ],
      [ "SharedDataVolume", "classbrayns_1_1_shared_data_volume.html", "classbrayns_1_1_shared_data_volume" ],
      [ "ShortcutInformation", "structbrayns_1_1_shortcut_information.html", "structbrayns_1_1_shortcut_information" ],
      [ "SphereLight", "classbrayns_1_1_sphere_light.html", "classbrayns_1_1_sphere_light" ],
      [ "SpotLight", "classbrayns_1_1_spot_light.html", "classbrayns_1_1_spot_light" ],
      [ "Statistics", "classbrayns_1_1_statistics.html", "classbrayns_1_1_statistics" ],
      [ "Streamline", "structbrayns_1_1_streamline.html", "structbrayns_1_1_streamline" ],
      [ "StreamlinesData", "structbrayns_1_1_streamlines_data.html", "structbrayns_1_1_streamlines_data" ],
      [ "Task", "classbrayns_1_1_task.html", "classbrayns_1_1_task" ],
      [ "TaskFunctor", "classbrayns_1_1_task_functor.html", "classbrayns_1_1_task_functor" ],
      [ "TaskRuntimeError", "classbrayns_1_1_task_runtime_error.html", "classbrayns_1_1_task_runtime_error" ],
      [ "Texture2D", "classbrayns_1_1_texture2_d.html", "classbrayns_1_1_texture2_d" ],
      [ "Timer", "classbrayns_1_1_timer.html", "classbrayns_1_1_timer" ],
      [ "TransferFunction", "classbrayns_1_1_transfer_function.html", "classbrayns_1_1_transfer_function" ],
      [ "Transformation", "classbrayns_1_1_transformation.html", "classbrayns_1_1_transformation" ],
      [ "TriangleMesh", "structbrayns_1_1_triangle_mesh.html", "structbrayns_1_1_triangle_mesh" ],
      [ "Version", "classbrayns_1_1_version.html", "classbrayns_1_1_version" ],
      [ "Volume", "classbrayns_1_1_volume.html", "classbrayns_1_1_volume" ],
      [ "VolumeParameters", "classbrayns_1_1_volume_parameters.html", "classbrayns_1_1_volume_parameters" ],
      [ "XYZBLoader", "classbrayns_1_1_x_y_z_b_loader.html", "classbrayns_1_1_x_y_z_b_loader" ]
    ] ],
    [ "linb", null, [
      [ "any", "classlinb_1_1any.html", "classlinb_1_1any" ],
      [ "bad_any_cast", "classlinb_1_1bad__any__cast.html", "classlinb_1_1bad__any__cast" ]
    ] ],
    [ "Application", "class_application.html", "class_application" ],
    [ "Cone", "struct_cone.html", "struct_cone" ],
    [ "Cylinder", "struct_cylinder.html", "struct_cylinder" ],
    [ "InputEvent", "struct_input_event.html", "struct_input_event" ],
    [ "Sphere", "struct_sphere.html", "struct_sphere" ]
];