Brayns: brayns::Camera Class Reference
brayns::Camera Class Reference
Camera object.
#include <Camera.h>
Public Member Functions
Camera & operator= (const Camera &rhs)
void set (const Vector3d &position, const Quaterniond &orientation, const Vector3d &target=Vector3d(0.0, 0.0, 0.0))
Sets position, and quaternion.
void setInitialState (const Vector3d &position, const Quaterniond &orientation, const Vector3d &target=Vector3d(0.0, 0.0, 0.0))
void setPosition (const Vector3d &position)
Sets camera position.
void setTarget (const Vector3d &target)
Sets camera target.
const Vector3d & getPosition () const
Gets camera position.
const Vector3d & getTarget () const
Gets camera target.
void setOrientation (Quaterniond orientation)
Sets camera orientation quaternion.
const Quaterniond & getOrientation () const
Gets the camera orientation quaternion.
void reset ()
Resets the camera to its initial values.
void setBufferTarget (const std::string &target)
const std::string & getBufferTarget () const
API for engine-specific code
virtual void commit ()
Commits the changes held by the camera object so that attributes become available to the underlying rendering engine.
Public Member Functions inherited from brayns::PropertyObject
void setCurrentType (const std::string &type)
Set the current type to use for 'type-less' queries and updates.
const std::string & getCurrentType () const
template<typename T >
void updateProperty (const std::string &name, const T &value, const bool triggerCallback=true)
Update the value of the given property for the current type.
bool hasProperty (const std::string &name) const
template<typename T >
T getProperty (const std::string &name) const
template<typename T >
T getPropertyOrValue (const std::string &name, T val) const
void setProperties (const PropertyMap &properties)
Assign a new set of properties to the current type.
void setProperties (const std::string &type, const PropertyMap &properties)
Assign a new set of properties to the given type.
void updateProperties (const PropertyMap &properties)
Update or add all the properties from the given map to the current type.
const auto & getPropertyMap () const
const auto & getPropertyMap (const std::string &type) const
strings getTypes () const
void clonePropertiesFrom (const PropertyObject &obj)
Clear all current properties and clone new properties from object.
Public Member Functions inherited from brayns::BaseObject
BaseObject (const BaseObject &)
Custom copy constructor to not copy changedCallback and solve non-copyable atomic modified state.
BaseObject & operator= (const BaseObject &rhs)
Custom assignment operator that does not copy the changedCallback.
bool isModified () const
void resetModified ()
Reset the modified state, typically done after changes have been applied.
void markModified (const bool triggerCallback=true)
void onModified (const ModifiedCallback &callback)
Set a function that is called after this object has been modified.
void clearModifiedCallback ()
Additional Inherited Members
Public Types inherited from brayns::BaseObject
using ModifiedCallback = std::function< void(const BaseObject &)>
Protected Member Functions inherited from brayns::BaseObject
template<typename T >
void _updateValue (T &member, const T &newValue, const bool triggerCallback=true)
Helper function for derived classes to update a parameter and mark it modified if it has changed.
template<class T >
bool _isEqual (const T &a, const T &b, typename std::enable_if< std::is_floating_point< T >::value >::type *=0)
template<class T >
bool _isEqual (const T &a, const T &b, typename std::enable_if<!std::is_floating_point< T >::value >::type *=0)
Protected Attributes inherited from brayns::PropertyObject
std::string _currentType
std::map< std::string, PropertyMap > _properties
Detailed Description
Camera object.
This object in an abstract interface to a camera which is defined by a position and a quaternion
Definition at line 38 of file Camera.h.
Member Function Documentation
getOrientation()
const Quaterniond& brayns::Camera::getOrientation () const inline
Gets the camera orientation quaternion.
Returns
the orientation quaternion
Definition at line 108 of file Camera.h.
getPosition()
const Vector3d& brayns::Camera::getPosition () const inline
Gets camera position.
Returns
The x, y, z coordinates of the camera position
Definition at line 89 of file Camera.h.
getTarget()
const Vector3d& brayns::Camera::getTarget () const inline
Gets camera target.
Returns
The x, y, z coordinates of the camera target
Definition at line 94 of file Camera.h.
set()
void brayns::Camera::set (const Vector3d & position, const Quaterniond & orientation, const Vector3d & target = Vector3d(0.0, 0.0, 0.0))
Sets position, and quaternion.
Parameters
position The x, y, z coordinates of the camera position
orientation The x, y, z, w values of the quaternion describing the camera orientation
target The x, y, z coordinates of the camera target
setOrientation()
void brayns::Camera::setOrientation (Quaterniond orientation) inline
Sets camera orientation quaternion.
Parameters
orientation The orientation quaternion
Definition at line 99 of file Camera.h.
References brayns::BaseObject::_updateValue().
setPosition()
void brayns::Camera::setPosition (const Vector3d & position) inline
Sets camera position.
Parameters
position The x, y, z coordinates of the camera position
Definition at line 76 of file Camera.h.
References brayns::BaseObject::_updateValue().
setTarget()
void brayns::Camera::setTarget (const Vector3d & target) inline
Sets camera target.
Parameters
target The x, y, z coordinates of the camera target
Definition at line 84 of file Camera.h.
References brayns::BaseObject::_updateValue().
The documentation for this class was generated from the following file:
Camera.h