Brayns: brayns::AnimationParameters Class Reference
brayns::AnimationParameters Class Reference
Public Types
using IsReadyCallback = std::function< bool()>
Public Types inherited from brayns::BaseObject
using ModifiedCallback = std::function< void(const BaseObject &)>
Public Member Functions
void print () final
Displays values of registered parameters.
void reset ()
Reset to a 'no animation' state: 0 for dt, start and end.
void setFrame (uint32_t value)
The current frame number of the animation.
uint32_t getFrame () const
void setDelta (const int32_t delta)
The (frame) delta to apply for animations to select the next frame.
int32_t getDelta () const
void setNumFrames (const uint32_t numFrames, const bool triggerCallback=true)
uint32_t getNumFrames () const
void setDt (const double dt, const bool triggerCallback=true)
The dt of a simulation.
double getDt () const
void setUnit (const std::string &unit, const bool triggerCallback=true)
The time unit of a simulation.
void setIsReadyCallback (const IsReadyCallback &callback)
Set a callback to report if the current animation frame is ready (e.g.
void removeIsReadyCallback ()
Remove the given callback from the list of IsReadyCallbacks.
bool hasIsReadyCallback () const
void update ()
Update the current frame if delta is set and all listeners are ready.
void jumpFrames (int frames)
Jump 'frames' from current frame if all listeners are ready.
void togglePlayback ()
bool isPlaying () const
Public Member Functions inherited from brayns::AbstractParameters
AbstractParameters (const std::string &name)
Constructor.
virtual void parse (const po::variables_map &)
Parses parameters managed by the class.
po::options_description & parameters ()
Public Member Functions inherited from brayns::BaseObject
BaseObject (const BaseObject &)
Custom copy constructor to not copy changedCallback and solve non-copyable atomic modified state.
BaseObject & operator= (const BaseObject &rhs)
Custom assignment operator that does not copy the changedCallback.
bool isModified () const
void resetModified ()
Reset the modified state, typically done after changes have been applied.
void markModified (const bool triggerCallback=true)
void onModified (const ModifiedCallback &callback)
Set a function that is called after this object has been modified.
void clearModifiedCallback ()
Additional Inherited Members
Protected Member Functions inherited from brayns::BaseObject
template<typename T >
void _updateValue (T &member, const T &newValue, const bool triggerCallback=true)
Helper function for derived classes to update a parameter and mark it modified if it has changed.
template<class T >
bool _isEqual (const T &a, const T &b, typename std::enable_if< std::is_floating_point< T >::value >::type *=0)
template<class T >
bool _isEqual (const T &a, const T &b, typename std::enable_if<!std::is_floating_point< T >::value >::type *=0)
Static Protected Member Functions inherited from brayns::AbstractParameters
static std::string asString (const bool flag)
Protected Attributes inherited from brayns::AbstractParameters
std::string _name
po::options_description _parameters
Detailed Description
Definition at line 31 of file AnimationParameters.h.
Member Function Documentation
jumpFrames()
void brayns::AnimationParameters::jumpFrames (int frames)
Jump 'frames' from current frame if all listeners are ready.
print()
void brayns::AnimationParameters::print () final virtual
Displays values of registered parameters.
Reimplemented from brayns::AbstractParameters.
removeIsReadyCallback()
void brayns::AnimationParameters::removeIsReadyCallback () inline
Remove the given callback from the list of IsReadyCallbacks.
Definition at line 82 of file AnimationParameters.h.
References reset().
reset()
void brayns::AnimationParameters::reset ()
Reset to a 'no animation' state: 0 for dt, start and end.
Referenced by removeIsReadyCallback().
setDelta()
void brayns::AnimationParameters::setDelta (const int32_t delta)
The (frame) delta to apply for animations to select the next frame.
setDt()
void brayns::AnimationParameters::setDt (const double dt, const bool triggerCallback = true) inline
The dt of a simulation.
Definition at line 59 of file AnimationParameters.h.
References brayns::BaseObject::_updateValue().
setFrame()
void brayns::AnimationParameters::setFrame (uint32_t value) inline
The current frame number of the animation.
Definition at line 43 of file AnimationParameters.h.
References brayns::BaseObject::_updateValue().
setIsReadyCallback()
void brayns::AnimationParameters::setIsReadyCallback (const IsReadyCallback & callback) inline
Set a callback to report if the current animation frame is ready (e.g.
simulation has been loaded) and the animation can advance to the next frame.
Definition at line 76 of file AnimationParameters.h.
setUnit()
void brayns::AnimationParameters::setUnit (const std::string & unit, const bool triggerCallback = true) inline
The time unit of a simulation.
Definition at line 65 of file AnimationParameters.h.
References brayns::BaseObject::_updateValue().
update()
void brayns::AnimationParameters::update ()
Update the current frame if delta is set and all listeners are ready.
The documentation for this class was generated from the following file:
AnimationParameters.h