Brayns: brayns::PropertyObject Class Reference
brayns::PropertyObject Class Reference
Maps generic properties to user-defined types/keys/names and tracks the current type/key/name for querying, setting and updating its properties.
#include <PropertyObject.h>
Public Member Functions
void setCurrentType (const std::string &type)
Set the current type to use for 'type-less' queries and updates.
const std::string & getCurrentType () const
template<typename T >
void updateProperty (const std::string &name, const T &value, const bool triggerCallback=true)
Update the value of the given property for the current type.
bool hasProperty (const std::string &name) const
template<typename T >
T getProperty (const std::string &name) const
template<typename T >
T getPropertyOrValue (const std::string &name, T val) const
void setProperties (const PropertyMap &properties)
Assign a new set of properties to the current type.
void setProperties (const std::string &type, const PropertyMap &properties)
Assign a new set of properties to the given type.
void updateProperties (const PropertyMap &properties)
Update or add all the properties from the given map to the current type.
const auto & getPropertyMap () const
const auto & getPropertyMap (const std::string &type) const
strings getTypes () const
void clonePropertiesFrom (const PropertyObject &obj)
Clear all current properties and clone new properties from object.
Public Member Functions inherited from brayns::BaseObject
BaseObject (const BaseObject &)
Custom copy constructor to not copy changedCallback and solve non-copyable atomic modified state.
BaseObject & operator= (const BaseObject &rhs)
Custom assignment operator that does not copy the changedCallback.
bool isModified () const
void resetModified ()
Reset the modified state, typically done after changes have been applied.
void markModified (const bool triggerCallback=true)
void onModified (const ModifiedCallback &callback)
Set a function that is called after this object has been modified.
void clearModifiedCallback ()
Protected Attributes
std::string _currentType
std::map< std::string, PropertyMap > _properties
Additional Inherited Members
Public Types inherited from brayns::BaseObject
using ModifiedCallback = std::function< void(const BaseObject &)>
Protected Member Functions inherited from brayns::BaseObject
template<typename T >
void _updateValue (T &member, const T &newValue, const bool triggerCallback=true)
Helper function for derived classes to update a parameter and mark it modified if it has changed.
template<class T >
bool _isEqual (const T &a, const T &b, typename std::enable_if< std::is_floating_point< T >::value >::type *=0)
template<class T >
bool _isEqual (const T &a, const T &b, typename std::enable_if<!std::is_floating_point< T >::value >::type *=0)
Detailed Description
Maps generic properties to user-defined types/keys/names and tracks the current type/key/name for querying, setting and updating its properties.
Definition at line 35 of file PropertyObject.h.
Member Function Documentation
getCurrentType()
const std::string& brayns::PropertyObject::getCurrentType () const inline
Returns
the current set type.
Definition at line 49 of file PropertyObject.h.
getProperty()
template<typename T > T brayns::PropertyObject::getProperty (const std::string & name) const inline
Returns
the value of the property with the given name for the current type.
Definition at line 78 of file PropertyObject.h.
getPropertyMap() [1/2]
const auto& brayns::PropertyObject::getPropertyMap () const inline
Returns
the entire property map for the current type.
Definition at line 116 of file PropertyObject.h.
getPropertyMap() [2/2]
const auto& brayns::PropertyObject::getPropertyMap (const std::string & type) const inline
Returns
the entire property map for the given type.
Definition at line 118 of file PropertyObject.h.
getPropertyOrValue()
template<typename T > T brayns::PropertyObject::getPropertyOrValue (const std::string & name, T val) const inline
Returns
the value of the property with the given name for the current type. If it does not exist return the given value.
Definition at line 88 of file PropertyObject.h.
References hasProperty().
getTypes()
strings brayns::PropertyObject::getTypes () const inline
Returns
the list of all registered types.
Definition at line 124 of file PropertyObject.h.
hasProperty()
bool brayns::PropertyObject::hasProperty (const std::string & name) const inline
Returns
true if the property with the given name exists for the current type.
Definition at line 68 of file PropertyObject.h.
Referenced by getPropertyOrValue().
setCurrentType()
void brayns::PropertyObject::setCurrentType (const std::string & type) inline
Set the current type to use for 'type-less' queries and updates.
Definition at line 39 of file PropertyObject.h.
References brayns::BaseObject::_updateValue().
setProperties() [1/2]
void brayns::PropertyObject::setProperties (const PropertyMap & properties) inline
Assign a new set of properties to the current type.
Definition at line 94 of file PropertyObject.h.
setProperties() [2/2]
void brayns::PropertyObject::setProperties (const std::string & type, const PropertyMap & properties) inline
Assign a new set of properties to the given type.
Definition at line 100 of file PropertyObject.h.
updateProperty()
template<typename T > void brayns::PropertyObject::updateProperty (const std::string & name, const T & value, const bool triggerCallback = true) inline
Update the value of the given property for the current type.
Definition at line 52 of file PropertyObject.h.
The documentation for this class was generated from the following file:
PropertyObject.h