Brion: brion::SpikeReportPlugin Class Reference
brion::SpikeReportPlugin Class Reference abstract
Base interface for spike report readers plugins.
#include <spikeReportPlugin.h>
Public Types
typedef SpikeReportPlugin InterfaceT
typedef PluginInitData InitDataT
using State = SpikeReport::State
Public Member Functions
SpikeReportPlugin (const PluginInitData &initData)
virtual void close ()
Close the report.
virtual Spikes read (float min)
Read spikes until getCurrentTime becomes > min, the end of the report is reached or the report closed.
virtual Spikes readUntil (float max)
Read spikes until getCurrentTime() >= max, the end of the report is reached or the report closed.
virtual void readSeek (float toTimeStamp)
Seek to a given absolute timestamp.
virtual void writeSeek (float toTimeStamp)
virtual void write (const Spikes &spikes)
Write the given spikes to the output.
virtual bool supportsBackwardSeek () const =0
void setFilter (const GIDSet &ids)
virtual const URI & getURI () const
State getState () const
int getAccessMode () const
virtual float getCurrentTime () const
virtual float getEndTime () const
bool isClosed () const
bool isInInterruptedState () const
Protected Types
typedef void(SpikeReportPlugin::* SpikeInsertFunction) (const Spike &, Spikes &) const
Protected Member Functions
void pushBack (const Spike &spike, Spikes &spikes) const
void checkNotInterrupted ()
Protected Attributes
URI _uri
brion::GIDSet _idsSubset
int _accessMode = brion::MODE_READ
float _currentTime = 0
float _endTime = 0
State _state = State::ok
Friends
class ::brion::SpikeReport
Detailed Description
Base interface for spike report readers plugins.
The following example creates a new plugin and registers it:
class MyReport : public SpikeReportPlugin
{
    MyReport( const SpikeReportInitData& initData );
    static bool handles( const SpikeReportInitData& initData );
    ...
};
...
// in the .cpp file
namespace
{
    PluginRegisterer< MyReport > registerer;
}
Plugins can also be provided by shared libraries discovered at runtime.
In this case, the registration must be occur from an extern C function named LunchboxPluginRegister():
// in the .cpp file
extern "C" int LunchboxPluginGetVersion() { return BRION_VERSION_ABI; }
extern "C" bool LunchboxPluginRegister()
{
    PluginRegisterer< MyReport > registerer;
    return true;
}
Plugin libraries in the LD_LIBRARY_PATH will be automatically registered if they provide the abovementioned C functions and follow the naming convention: <lib_prefix>Brion<MyReportName>SpikeReport.<lib_extension>
Version
2.0
Definition at line 82 of file spikeReportPlugin.h.
Member Function Documentation
virtual void brion::SpikeReportPlugin::close () inline virtual
Close the report.
The close operation is blocking and it interrupts all the pending read/seek operations.
Version
2.0
Definition at line 100 of file spikeReportPlugin.h.
virtual Spikes brion::SpikeReportPlugin::read (float min) inline virtual
Read spikes until getCurrentTime becomes > min, the end of the report is reached or the report closed.
This function fetches all the available data from the source. If no error occurs and the end is not reached, the min value passed is also guaranteed to be inside the time window of the data returned.
Preconditions:
r.getState() is State::ok
The report was open in read mode.
There is no previous read or seek operation with a pending future.
Postconditions: Let:
r be the SpikeReport
f be the returned future by r.read(min)
and s = r.getCurrentTime() before read is called: After f.wait() returns the following are all true:
r.getCurrentTime() >= s
If r.getState() == State::ok, then r.getCurrentTime() > min
For each spike timestamp t_s in f.get(), s <= t_s < r.getCurrentTime() (Note this could collapse to an empty interval if r.getState() != State::ok)
After successful f.wait_for or f.wait_until, the result is the same as above. If they time out, no observable state changes.
If the state is FAILED or some other operation is still pending when read is called the result is undefined.
Parameters
min The minimum end time until which spikes will be read. If UNDEFINED_TIMESTAMP, it will be considered as -infinite. This means that as much data as possible will be fetched without a minimum.
Exceptions
std::logic_error if one of the preconditions is not fulfilled.
Note
Until the completion of this operation, the internal state of the SpikeReport may change.
Version
2.0
Definition at line 107 of file spikeReportPlugin.h.
virtual void brion::SpikeReportPlugin::readSeek (float toTimeStamp) inline virtual
Seek to a given absolute timestamp.
If toTimestamp >= getCurrentTime() and the report was open for reading, data will be skipped forward until the timestamp is made current. In write mode for streams, consumers are notified about the new timestamp.
The case toTimestamp < getCurrentTime() is only supported by file based reports. In write mode, seeks are only supported in binary reports. Forward seeking simply updates getCurrentTime() and backward seeking followed by a write, will overwrite the existing data.
If the seek operation is not supported, a std::runtime_error will be thrown if this method is called.
Preconditions:
There is no standing read or readUntil operation.
Postconditions: Let:
r be the SpikeReport
f be the returned future by r.seek(toTimestamp) Then:
After f.wait() returns r.getCurrentTime() == toTimestamp.
The postconditions of read operations imply that in forward skips this function throws away the data previous to toTimestamp (or avoids reading it at all if possible).
Exceptions
std::runtime_error if a precondition does not hold or the operation is not supported by the implementation.
Note
Until the completion of this operation, the internal state of the SpikeReport may change.
Version
2.0
Definition at line 121 of file spikeReportPlugin.h.
virtual Spikes brion::SpikeReportPlugin::readUntil (float max) inline virtual
Read spikes until getCurrentTime() >= max, the end of the report is reached or the report closed.
This function is very similar to the normal read, but instead of specifying a lower bound of getCurrentTime at return, it specifies a requested strict value. The preconditions and postconditions are the same except for those involving the parameter min which become:
Precondition: max > getCurrentTime() Postcondition: If r.getState() == State::ok, then r.getCurrentTime() >= max
Exceptions
std::runtime_error if the precondition does not hold.
Note
Until the completion of this operation, the internal state of the SpikeReport may change.
See also
seek()
Version
2.0
Definition at line 114 of file spikeReportPlugin.h.
virtual bool brion::SpikeReportPlugin::supportsBackwardSeek () const pure virtual
Returns
Whether the report supports seek to t < getCurrentTime() or not.
Version
2.0
Referenced by write().
virtual void brion::SpikeReportPlugin::write (const Spikes & spikes) inline virtual
Write the given spikes to the output.
Preconditions:
spikes is a sorted by time stamp
spikes.front().first < getCurrentTime()
Upon return getCurrenTime() is the greatest of all the spike times plus an epsilon.
Parameters
spikes A collection of spikes sorted by timestamp in ascending order. For every spike, its timestamp must be >= getCurrentTime().
Exceptions
std::runtime_error if the report is read-only,
std::logic_error if a precondition does not hold
Version
2.0
Definition at line 136 of file spikeReportPlugin.h.
References brion::PluginInitData::getURI(), and supportsBackwardSeek().
virtual void brion::SpikeReportPlugin::writeSeek (float toTimeStamp) inline virtual
Definition at line 129 of file spikeReportPlugin.h.
The documentation for this class was generated from the following file:
spikeReportPlugin.h