Keyv: keyv::Plugin Class Reference
keyv::Plugin Class Reference abstract
Interface for all Map plugins.
#include <Plugin.h>
Public Types
typedef Plugin InterfaceT
typedef servus::URI InitDataT
Public Member Functions
virtual size_t setQueueDepth (size_t size)
Set the maximum number of asynchronous outstanding write operations.
virtual bool insert (const std::string &key, const void *data, size_t size)=0
Insert or update a value in the database.
virtual void erase (const std::string &key)=0
Erase the given key from the store.
virtual bool flush ()=0
Flush outstanding operations to the backend storage.
virtual std::string operator[] (const std::string &key) const =0
Retrieve a value for a key.
virtual void getValues (const Strings &keys, const ConstValueFunc &func) const =0
Retrieve values from a list of keys and calls back for each found value.
virtual void takeValues (const Strings &keys, const ValueFunc &func) const =0
Retrieve values from a list of keys and calls back for each found value.
Detailed Description
Interface for all Map plugins.
Definition at line 31 of file Plugin.h.
Member Function Documentation
virtual void keyv::Plugin::erase (const std::string & key) pure virtual
Erase the given key from the store.
Version
1.1
Referenced by setQueueDepth().
virtual bool keyv::Plugin::flush () pure virtual
Flush outstanding operations to the backend storage.
Version
1.0
Referenced by setQueueDepth().
virtual void keyv::Plugin::getValues (const Strings & keys, const ConstValueFunc & func) const pure virtual
Retrieve values from a list of keys and calls back for each found value.
Depending on the backend implementation, this is more optimal than calling get() for each key.
The ownership of the returned data in the callback is not transfered, so the value needs to be copied if needed.
Parameters
keys list of keys to obtain
func callback function which is called for each found key
Version
1.14
Referenced by setQueueDepth().
virtual bool keyv::Plugin::insert (const std::string & key, const void * data, size_t size) pure virtual
Insert or update a value in the database.
Parameters
key the key to store the value.
value the value stored at the key.
Returns
true on success, false otherwise
Exceptions
std::runtime_error if the value is not copyable
Version
1.9.2
Referenced by setQueueDepth().
virtual std::string keyv::Plugin::operator[] (const std::string & key) const pure virtual
Retrieve a value for a key.
Parameters
key the key to retrieve.
Returns
the value, or an empty string if the key is not available.
Version
1.9.2
Referenced by setQueueDepth().
virtual size_t keyv::Plugin::setQueueDepth (size_t size) inline virtual
Set the maximum number of asynchronous outstanding write operations.
Some backend implementations support asynchronous writes, which can be enabled by setting a non-zero queue depth. Applications then need to quarantee that the inserted values stay valid until 'depth' other elements have been inserted or flush() has been called. Implementations which do not support asynchronous writes return 0.
Returns
the queue depth chosen by the implementation, smaller or equal to the given depth.
Version
1.11
Definition at line 43 of file Plugin.h.
References erase(), flush(), getValues(), insert(), operator[](), and takeValues().
virtual void keyv::Plugin::takeValues (const Strings & keys, const ValueFunc & func) const pure virtual
Retrieve values from a list of keys and calls back for each found value.
Depending on the backend implementation, this is more optimal than calling get() for each key.
The ownership of the returned data in the callback is transfered, so the data must be free'd by the caller.
Parameters
keys list of keys to obtain
func callback function which is called for each found key
Version
1.14
Referenced by setQueueDepth().
The documentation for this class was generated from the following file:
Plugin.h