set(DISPLAYCLUSTER_MATURITY "EP")
set(DISPLAYCLUSTER_DESCRIPTION "A collaborative software for driving large display walls")
set(DISPLAYCLUSTER_GIT_ROOT_URL "https://github.com/BlueBrain/DisplayCluster.git")
set(DISPLAYCLUSTER_PACKAGE_URL "")
set(DISPLAYCLUSTER_CI_URL "https://travis-ci.org/BlueBrain/DisplayCluster")
set(DISPLAYCLUSTER_CI_PNG "https://travis-ci.org/BlueBrain/DisplayCluster.png")
set(DISPLAYCLUSTER_ISSUES_URL "https://github.com/BlueBrain/DisplayCluster/issues")
