Brayns: brayns::Scene Class Reference
brayns::Scene Class Reference abstract
Scene object.
#include <Scene.h>
Public Member Functions
Scene (Renderers renderers, ParametersManager &parametersManager)
Creates a scene object responsible for handling geometry, volumes, materials and light sources.
virtual void commit ()=0
Called after scene-related changes have been made before rendering the scene.
virtual void commitLights ()=0
Commit lights to renderers.
virtual void buildGeometry ()=0
Converts scene geometry into rendering engine specific data structures.
virtual void serializeGeometry ()=0
Serializes scene geometry into rendering engine specific data structures.
virtual void commitSimulationData ()=0
Attach simulation data to renderer.
virtual void commitVolumeData ()=0
Attach volume data to renderer.
virtual void commitTransferFunctionData ()=0
Commit transfer function data to renderer.
Boxf & getWorldBounds ()
Returns the bounding box for the whole scene.
const Boxf & getWorldBounds () const
void buildEnvironment ()
Build an environment in addition to the loaded data, and according to the geometry parameters (command line parameter –scene-environment).
void addLight (LightPtr light)
Attaches a light source to the scene.
LightPtr getLight (const size_t index)
Gets a light source from the scene for a given index.
void removeLight (LightPtr light)
Removes a light source from the scene for a given index.
void clearLights ()
Removes all light sources from the scene.
void buildDefault ()
Builds a default scene made of a Cornell box, a refelctive cube, and a transparent sphere.
bool empty () const
Return true if the scene does not contain any geometry.
ParametersManager & getParametersManager ()
SpheresMap & getSpheres ()
Returns spheres handled by the scene.
CylindersMap & getCylinders ()
Returns cylinders handled by the scene.
ConesMap & getCones ()
Returns cones handled by the scene.
TexturesMap & getTextures ()
Returns textures handled by the scene.
TrianglesMeshMap & getTriangleMeshes ()
Returns triangle meshes handled by the scene.
AbstractSimulationHandlerPtr getSimulationHandler () const
Returns the simulutation handler.
void setSimulationHandler (AbstractSimulationHandlerPtr handler)
Sets the simulation handler.
VolumeHandlerPtr getVolumeHandler ()
Returns volume data.
void setCADiffusionSimulationHandler (CADiffusionSimulationHandlerPtr handler)
Sets the Calcium diffusion simulation handler.
CADiffusionSimulationHandlerPtr getCADiffusionSimulationHandler () const
Gets the Calcium diffusion simulation handler.
TransferFunction & getTransferFunction ()
Build a color map from a file, according to the colormap-file scene parameters.
virtual void unload ()
Unloads geometry, materials, lights, models, etc.
void loadFromCacheFile ()
Loads geometry a binary cache file defined by the –load-cache-file command line parameter.
void saveToCacheFile ()
Saves geometry a binary cache file defined by the –save-cache-file command line parameter.
virtual bool isVolumeSupported (const std::string &volumeFile) const =0
void setSpheresDirty (const bool value)
Sets spheres as dirty, meaning that they need to be serialized and sent to the rendering engine.
virtual void reset ()
uint64_t addSphere (const size_t materialId, const Sphere &sphere)
Adds a sphere to the scene.
uint64_t addCone (const size_t materialId, const Cone &cone)
Adds a cone to the scene.
uint64_t addCylinder (const size_t materialId, const Cylinder &cylinder)
Adds a cylinder to the scene.
void setSphere (const size_t materialId, const uint64_t index, const Sphere &sphere)
Replaces a sphere in the scene.
void setCone (const size_t materialId, const uint64_t index, const Cone &cone)
Replaces a cone in the scene.
void setCylinder (const size_t materialId, const uint64_t index, const Cylinder &cylinder)
Replaces a cylinder in the scene.
size_t addMaterial (const Material &material)
Adds a material to the scene.
Material & getMaterial (size_t index)
Returns the material object for a given index.
void setMaterial (const size_t index, const Material &material)
Set the material object for a given index.
void resetMaterials ()
Resets materials and builds the system ones (Bounding box, skymap, etc)
virtual void commitMaterials (const Action action=Action::create)=0
Commit materials to renderers.
Materials & getMaterials ()
Returns materials handled by the scene.
void setMaterialsColorMap (MaterialsColorMap colorMap=MaterialsColorMap::none)
Sets the materials handled by the scene, and available to the scene geometry.
size_t getSizeInBytes () const
Protected Member Functions
void _buildMissingMaterials (const size_t materialId)
void _processVolumeAABBGeometry ()
Protected Attributes
ParametersManager & _parametersManager
Renderers _renderers
SpheresMap _spheres
bool _spheresDirty
CylindersMap _cylinders
bool _cylindersDirty
ConesMap _cones
bool _conesDirty
TrianglesMeshMap _trianglesMeshes
bool _trianglesMeshesDirty
Materials _materials
TexturesMap _textures
Lights _lights
VolumeHandlerPtr _volumeHandler
AbstractSimulationHandlerPtr _simulationHandler
TransferFunction _transferFunction
CADiffusionSimulationHandlerPtr _caDiffusionSimulationHandler
Boxf _bounds
size_t _sizeInBytes {0}
Detailed Description
Scene object.
This object contains collections of geometries, materials and light sources that are used to describe the 3D scene to be rendered. Scene is the base class for rendering-engine-specific inherited scenes.
Definition at line 46 of file Scene.h.
Constructor & Destructor Documentation
brayns::Scene::Scene (Renderers renderers, ParametersManager & parametersManager)
Creates a scene object responsible for handling geometry, volumes, materials and light sources.
Parameters
renderers Renderers to be used to render the scene
parametersManager Parameters for the scene (Geometry, volume, rendering, etc)
Todo:
The scene must not know about the renderer https://bbpteam.epfl.ch/project/issues/browse/VIZTM-574
Member Function Documentation
uint64_t brayns::Scene::addCone (const size_t materialId, const Cone & cone)
Adds a cone to the scene.
Parameters
materialId Material of the cone
cone Cone to add
Returns
Index of the sphere for the specified material
Referenced by setSpheresDirty().
uint64_t brayns::Scene::addCylinder (const size_t materialId, const Cylinder & cylinder)
Adds a cylinder to the scene.
Parameters
materialId Material of the cylinder
cylinder Cylinder to add
Returns
Index of the sphere for the specified material
Referenced by setSpheresDirty().
void brayns::Scene::addLight (LightPtr light)
Attaches a light source to the scene.
Parameters
light Object representing the light source
Referenced by getWorldBounds().
size_t brayns::Scene::addMaterial (const Material & material)
Adds a material to the scene.
Parameters
material Material to add
Returns
index of the new material
Referenced by setSpheresDirty().
uint64_t brayns::Scene::addSphere (const size_t materialId, const Sphere & sphere)
Adds a sphere to the scene.
Parameters
materialId Material of the sphere
sphere Sphere to add
Returns
Index of the sphere for the specified material
Referenced by setSpheresDirty().
virtual void brayns::Scene::commitMaterials (const Action action = Action::create) pure virtual
Commit materials to renderers.
Parameters
action Defines if materials should be created or updated
Implemented in brayns::OSPRayScene.
Referenced by setSpheresDirty().
bool brayns::Scene::empty () const
Return true if the scene does not contain any geometry.
False otherwise
Referenced by getWorldBounds().
LightPtr brayns::Scene::getLight (const size_t index)
Gets a light source from the scene for a given index.
Returns
Pointer to light source
Referenced by getWorldBounds().
Material& brayns::Scene::getMaterial (size_t index)
Returns the material object for a given index.
Returns
Reference to material object
Referenced by setSpheresDirty().
size_t brayns::Scene::getSizeInBytes () const inline
Returns
the current size in bytes of the loaded geometry.
Definition at line 363 of file Scene.h.
virtual bool brayns::Scene::isVolumeSupported (const std::string & volumeFile) const pure virtual
Returns
true if the given volume file is supported by the engines' scene. If false, a default scene will be constructed.
Implemented in brayns::OSPRayScene.
Referenced by getTransferFunction().
void brayns::Scene::loadFromCacheFile ()
Loads geometry a binary cache file defined by the –load-cache-file command line parameter.
The cache file is a binary representation of the following structure:
Version
Number of materials
Materials
For each material:
Number of spheres
Spheres
Number of cylinders
Cylinders
Number of cones
Cones
Number of vertices
Vertices
Number of indices
Indices
Number of normals
Normals
Number of texture coordinates
Texture coordinates
Scene bounds
Referenced by getTransferFunction().
void brayns::Scene::removeLight (LightPtr light)
Removes a light source from the scene for a given index.
Parameters
light Light source to be removed
Referenced by getWorldBounds().
void brayns::Scene::saveToCacheFile ()
Saves geometry a binary cache file defined by the –save-cache-file command line parameter.
See loadFromCacheFile for file structure
Referenced by getTransferFunction().
void brayns::Scene::setCone (const size_t materialId, const uint64_t index, const Cone & cone)
Replaces a cone in the scene.
Parameters
materialId Material of the cone
index Index of the cone in the scene, for the given material
cone New sphere
Referenced by setSpheresDirty().
void brayns::Scene::setCylinder (const size_t materialId, const uint64_t index, const Cylinder & cylinder)
Replaces a cylinder in the scene.
Parameters
materialId Material of the cylinder
index Index of the cylinder in the scene, for the given material
cylinder New cylinder
Referenced by setSpheresDirty().
void brayns::Scene::setMaterial (const size_t index, const Material & material)
Set the material object for a given index.
Parameters
index Index of material in the scene
material Material object
Referenced by setSpheresDirty().
void brayns::Scene::setMaterialsColorMap (MaterialsColorMap colorMap = MaterialsColorMap::none)
Sets the materials handled by the scene, and available to the scene geometry.
Parameters
materialType Specifies the algorithm that is used to create the materials. For instance MT_RANDOM creates materials with random colors, transparency, reflection, and light emission
Referenced by getMaterials().
void brayns::Scene::setSphere (const size_t materialId, const uint64_t index, const Sphere & sphere)
Replaces a sphere in the scene.
Parameters
materialId Material of the sphere
index Index of the sphere in the scene, for the given material
sphere New sphere
Referenced by setSpheresDirty().
virtual void brayns::Scene::unload () virtual
Unloads geometry, materials, lights, models, etc.
to free memory.
Reimplemented in brayns::OSPRayScene.
Referenced by getTransferFunction().
The documentation for this class was generated from the following file:
Scene.h