Brayns: brayns::AbstractSimulationHandler Class Reference
brayns::AbstractSimulationHandler Class Reference abstract
The AbstractSimulationHandler class handles simulation frames for the current circuit.
#include <AbstractSimulationHandler.h>
Public Member Functions
AbstractSimulationHandler (const GeometryParameters &geometryParameters)
Default contructor.
virtual ~AbstractSimulationHandler ()
Default desctuctor.
bool attachSimulationToCacheFile (const std::string &cacheFile)
Attaches a memory mapped file to the scene so that renderers can access the data as if it was in memory.
void writeHeader (std::ofstream &stream)
Writes the header to a stream.
void writeFrame (std::ofstream &stream, const floats &values)
Writes a frame to a stream.
uint32_t getCurrentFrame () const
virtual void * getFrameData (uint32_t frame)=0
returns a void pointer to the simulation data for the given frame or nullptr if the frame is not loaded yet.
uint64_t getFrameSize () const
getFrameSize return the size of the current simulation frame
void setFrameSize (const uint64_t frameSize)
setFrameSize Sets the size of the current simulation frame
uint32_t getNbFrames () const
getNbFrames returns the number of frame for the current simulation
void setNbFrames (const uint32_t nbFrames)
setNbFrames sets the number of frame for the current simulation
double getDt () const
const std::string & getUnit () const
Histogram & getHistogram ()
getHistogram returns the Histogram of the values in the current simulation frame.
bool histogramChanged () const
virtual bool isReady () const
Protected Member Functions
uint32_t _getBoundedFrame (const uint32_t frame) const
Protected Attributes
const GeometryParameters & _geometryParameters
uint32_t _currentFrame {std::numeric_limits<uint32_t>::max()}
uint32_t _nbFrames {0}
uint64_t _frameSize {0}
double _dt {0}
std::string _unit
uint64_t _headerSize {0}
void * _memoryMapPtr {nullptr}
int _cacheFileDescriptor {-1}
Histogram _histogram
float * _frameData {nullptr}
Detailed Description
The AbstractSimulationHandler class handles simulation frames for the current circuit.
Definition at line 33 of file AbstractSimulationHandler.h.
Constructor & Destructor Documentation
brayns::AbstractSimulationHandler::AbstractSimulationHandler (const GeometryParameters & geometryParameters)
Default contructor.
Parameters
geometryParameters Geometry parameters
Member Function Documentation
bool brayns::AbstractSimulationHandler::attachSimulationToCacheFile (const std::string & cacheFile)
Attaches a memory mapped file to the scene so that renderers can access the data as if it was in memory.
The OS is in charge of dealing with the map file in system memory.
Parameters
cacheFile File containing the simulation values
Returns
True if the file was successfully attached, false otherwise
uint32_t brayns::AbstractSimulationHandler::getCurrentFrame () const inline
Returns
the current loaded frame for the simulation.
Definition at line 74 of file AbstractSimulationHandler.h.
References getFrameData().
double brayns::AbstractSimulationHandler::getDt () const inline
Returns
the dt of the simulation in getUnit() time unit; 0 if not reported
Definition at line 101 of file AbstractSimulationHandler.h.
Histogram& brayns::AbstractSimulationHandler::getHistogram ()
getHistogram returns the Histogram of the values in the current simulation frame.
The size of the histogram is defined by the –simulation-histogram-size command line parameter (128 by default). To build the histogram, occurrences of the same value are counted and spread along the histogram according to the calculated range. The range is defined by the minimum and maximum value of the current frame. The Histogram is specific to the current frame, not to the whole simulation.
Referenced by getUnit().
const std::string& brayns::AbstractSimulationHandler::getUnit () const inline
Returns
the time unit of the simulation; empty if not reported.
Definition at line 103 of file AbstractSimulationHandler.h.
References getHistogram(), and histogramChanged().
bool brayns::AbstractSimulationHandler::histogramChanged () const
Returns
true if the histogram has changed since the last update.
Referenced by getUnit().
virtual bool brayns::AbstractSimulationHandler::isReady () const inline virtual
Returns
true if the requested frame from getFrameData() is ready to consume and if it is allowed to advance to the next frame.
Definition at line 124 of file AbstractSimulationHandler.h.
void brayns::AbstractSimulationHandler::writeFrame (std::ofstream & stream, const floats & values)
Writes a frame to a stream.
A frame is a set of float values.
Parameters
stream Stream where the header should be written
values Frame values
void brayns::AbstractSimulationHandler::writeHeader (std::ofstream & stream)
Writes the header to a stream.
The header contains the number of frames and the frame size.
Parameters
stream Stream where the header should be written
The documentation for this class was generated from the following file:
AbstractSimulationHandler.h