set(BRION_MATURITY "EP")
set(BRION_DESCRIPTION "The Blue Brain C++ I/O library")
set(BRION_GIT_ROOT_URL "ssh://git@github.com/BlueBrain/Brion")
set(BRION_PACKAGE_URL "")
set(BRION_CI_URL "ssh://git@travis-ci.org/BlueBrain/Brion")
set(BRION_CI_PNG "ssh://git@travis-ci.org/BlueBrain/Brion.png")
set(BRION_ISSUES_URL "ssh://git@github.com/BlueBrain/Brion")
