var annotated =
[
    [ "brayns", null, [
      [ "obj", null, [
        [ "ExtendedOBJMaterial", "structbrayns_1_1obj_1_1_extended_o_b_j_material.html", "structbrayns_1_1obj_1_1_extended_o_b_j_material" ]
      ] ],
      [ "AbstractManipulator", "classbrayns_1_1_abstract_manipulator.html", "classbrayns_1_1_abstract_manipulator" ],
      [ "AbstractParameters", "classbrayns_1_1_abstract_parameters.html", "classbrayns_1_1_abstract_parameters" ],
      [ "ApplicationParameters", "classbrayns_1_1_application_parameters.html", "classbrayns_1_1_application_parameters" ],
      [ "BadParameter", "classbrayns_1_1_bad_parameter.html", "classbrayns_1_1_bad_parameter" ],
      [ "BaseWindow", "classbrayns_1_1_base_window.html", "classbrayns_1_1_base_window" ],
      [ "Brayns", "classbrayns_1_1_brayns.html", "classbrayns_1_1_brayns" ],
      [ "Camera", "classbrayns_1_1_camera.html", "classbrayns_1_1_camera" ],
      [ "Cone", "classbrayns_1_1_cone.html", "classbrayns_1_1_cone" ],
      [ "Cylinder", "classbrayns_1_1_cylinder.html", "classbrayns_1_1_cylinder" ],
      [ "DeflectPlugin", "classbrayns_1_1_deflect_plugin.html", "classbrayns_1_1_deflect_plugin" ],
      [ "DirectionalLight", "classbrayns_1_1_directional_light.html", "classbrayns_1_1_directional_light" ],
      [ "Exception", "classbrayns_1_1_exception.html", "classbrayns_1_1_exception" ],
      [ "ExtendedCones", "structbrayns_1_1_extended_cones.html", "structbrayns_1_1_extended_cones" ],
      [ "ExtendedCylinders", "structbrayns_1_1_extended_cylinders.html", "structbrayns_1_1_extended_cylinders" ],
      [ "ExtendedOBJRenderer", "structbrayns_1_1_extended_o_b_j_renderer.html", "structbrayns_1_1_extended_o_b_j_renderer" ],
      [ "ExtendedSpheres", "structbrayns_1_1_extended_spheres.html", "structbrayns_1_1_extended_spheres" ],
      [ "ExtensionPlugin", "classbrayns_1_1_extension_plugin.html", "classbrayns_1_1_extension_plugin" ],
      [ "ExtensionPluginFactory", "classbrayns_1_1_extension_plugin_factory.html", "classbrayns_1_1_extension_plugin_factory" ],
      [ "FlyingModeManipulator", "classbrayns_1_1_flying_mode_manipulator.html", "classbrayns_1_1_flying_mode_manipulator" ],
      [ "FPSCounter", "structbrayns_1_1_f_p_s_counter.html", "structbrayns_1_1_f_p_s_counter" ],
      [ "FrameBuffer", "classbrayns_1_1_frame_buffer.html", "classbrayns_1_1_frame_buffer" ],
      [ "Geometry", "classbrayns_1_1_geometry.html", "classbrayns_1_1_geometry" ],
      [ "GeometryParameters", "classbrayns_1_1_geometry_parameters.html", "classbrayns_1_1_geometry_parameters" ],
      [ "InspectCenterManipulator", "classbrayns_1_1_inspect_center_manipulator.html", "classbrayns_1_1_inspect_center_manipulator" ],
      [ "Light", "classbrayns_1_1_light.html", "classbrayns_1_1_light" ],
      [ "Material", "classbrayns_1_1_material.html", "classbrayns_1_1_material" ],
      [ "MeshContainer", "structbrayns_1_1_mesh_container.html", "structbrayns_1_1_mesh_container" ],
      [ "MeshLoader", "classbrayns_1_1_mesh_loader.html", "classbrayns_1_1_mesh_loader" ],
      [ "MorphologyLayout", "structbrayns_1_1_morphology_layout.html", "structbrayns_1_1_morphology_layout" ],
      [ "MorphologyLoader", "classbrayns_1_1_morphology_loader.html", "classbrayns_1_1_morphology_loader" ],
      [ "OSPRayCamera", "classbrayns_1_1_o_s_p_ray_camera.html", "classbrayns_1_1_o_s_p_ray_camera" ],
      [ "OSPRayFrameBuffer", "classbrayns_1_1_o_s_p_ray_frame_buffer.html", "classbrayns_1_1_o_s_p_ray_frame_buffer" ],
      [ "OSPRayRenderer", "classbrayns_1_1_o_s_p_ray_renderer.html", "classbrayns_1_1_o_s_p_ray_renderer" ],
      [ "OSPRayScene", "classbrayns_1_1_o_s_p_ray_scene.html", "classbrayns_1_1_o_s_p_ray_scene" ],
      [ "ParametersManager", "classbrayns_1_1_parameters_manager.html", "classbrayns_1_1_parameters_manager" ],
      [ "PointLight", "classbrayns_1_1_point_light.html", "classbrayns_1_1_point_light" ],
      [ "Primitive", "classbrayns_1_1_primitive.html", "classbrayns_1_1_primitive" ],
      [ "ProteinLoader", "classbrayns_1_1_protein_loader.html", "classbrayns_1_1_protein_loader" ],
      [ "ProximityRenderer", "structbrayns_1_1_proximity_renderer.html", "structbrayns_1_1_proximity_renderer" ],
      [ "Renderer", "classbrayns_1_1_renderer.html", "classbrayns_1_1_renderer" ],
      [ "RenderingParameters", "classbrayns_1_1_rendering_parameters.html", "classbrayns_1_1_rendering_parameters" ],
      [ "RenderInput", "structbrayns_1_1_render_input.html", "structbrayns_1_1_render_input" ],
      [ "RenderOutput", "structbrayns_1_1_render_output.html", "structbrayns_1_1_render_output" ],
      [ "Scene", "classbrayns_1_1_scene.html", "classbrayns_1_1_scene" ],
      [ "SceneParameters", "classbrayns_1_1_scene_parameters.html", "classbrayns_1_1_scene_parameters" ],
      [ "SimulationData", "structbrayns_1_1_simulation_data.html", "structbrayns_1_1_simulation_data" ],
      [ "SimulationRenderer", "structbrayns_1_1_simulation_renderer.html", "structbrayns_1_1_simulation_renderer" ],
      [ "Sphere", "classbrayns_1_1_sphere.html", "classbrayns_1_1_sphere" ],
      [ "StereoCamera", "structbrayns_1_1_stereo_camera.html", "structbrayns_1_1_stereo_camera" ],
      [ "Texture2D", "classbrayns_1_1_texture2_d.html", "classbrayns_1_1_texture2_d" ],
      [ "TextureLoader", "classbrayns_1_1_texture_loader.html", "classbrayns_1_1_texture_loader" ],
      [ "TrianglesMesh", "classbrayns_1_1_triangles_mesh.html", "classbrayns_1_1_triangles_mesh" ],
      [ "Version", "classbrayns_1_1_version.html", "classbrayns_1_1_version" ],
      [ "Viewport", "classbrayns_1_1_viewport.html", "classbrayns_1_1_viewport" ],
      [ "ZeroBufPlugin", "classbrayns_1_1_zero_buf_plugin.html", "classbrayns_1_1_zero_buf_plugin" ]
    ] ]
];