set(BRAYNS_MATURITY "EP")
set(BRAYNS_DESCRIPTION "Hardware Agnostic Ray-Tracer")
set(BRAYNS_GIT_ROOT_URL "https://github.com/bluebrain/Brayns.git")
set(BRAYNS_PACKAGE_URL "")
set(BRAYNS_CI_URL "https://travis-ci.org/bluebrain/Brayns")
set(BRAYNS_CI_PNG "https://travis-ci.org/bluebrain/Brayns.png")
set(BRAYNS_ISSUES_URL "https://github.com/bluebrain/Brayns/issues")
